package roles

import "context"

// ActionFunc is the signature for an action primitive executor.
type ActionFunc func(ctx context.Context, agent *RoleAgent, deps *AgentDeps) error

// ActionRegistry maps primitive names to their executor functions.
// Populated by init() in capabilities.go.
var ActionRegistry = map[string]ActionFunc{}

// ActionDescription describes an available action primitive for LLM prompt injection.
type ActionDescription struct {
	Name        string
	Description string
}

// AvailableActions returns descriptions of all registered action primitives.
// Used by OrgEngine to tell the LLM what primitives are available.
func AvailableActions() []ActionDescription {
	return []ActionDescription{
		{Name: "chase_missing", Description: "追踪未提交报告的员工并发送提醒 / Chase employees who haven't submitted reports"},
		{Name: "daily_summary", Description: "生成每日团队状态摘要 / Generate daily team status summary"},
		{Name: "weekly_summary", Description: "生成每周运营回顾 / Generate weekly operations review"},
		{Name: "check_alerts", Description: "检查告警条件并创建建议 / Check alert conditions and create suggestions"},
		{Name: "create_suggestion", Description: "生成战略建议供管理者审批 / Generate strategic suggestion for boss approval"},
		{Name: "send_branded_msg", Description: "以角色身份发送消息给管理者 / Send role-branded message to boss"},
	}
}

// ValidAction checks if an action name is registered.
func ValidAction(name string) bool {
	_, ok := ActionRegistry[name]
	return ok
}

// DynamicRoleConfig defines a role as generated by the LLM/mentor.
// Stored in ai_role_instances.config JSONB.
type DynamicRoleConfig struct {
	Title       string              `json:"title"`
	TitleEn     string              `json:"title_en"`
	RoleID      string              `json:"role_id"`
	Scope       string              `json:"scope"`
	Personality string              `json:"personality"`
	Capabilities []DynamicCapability `json:"capabilities"`
}

// DynamicCapability defines one thing a role can do.
type DynamicCapability struct {
	Action   string `json:"action"`
	Schedule string `json:"schedule,omitempty"` // cron expression
	Trigger  string `json:"trigger,omitempty"`  // event name
}
