// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_roles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIRoleInstance = `-- name: CreateAIRoleInstance :one
INSERT INTO ai_role_instances (tenant_id, role_id, title, mentor_id, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, role_id) DO UPDATE SET
    title = EXCLUDED.title,
    mentor_id = EXCLUDED.mentor_id,
    config = EXCLUDED.config,
    is_active = true
RETURNING id, tenant_id, role_id, title, mentor_id, config, is_active, created_at
`

type CreateAIRoleInstanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleID   string      `json:"role_id"`
	Title    string      `json:"title"`
	MentorID string      `json:"mentor_id"`
	Config   []byte      `json:"config"`
}

func (q *Queries) CreateAIRoleInstance(ctx context.Context, arg CreateAIRoleInstanceParams) (AiRoleInstance, error) {
	row := q.db.QueryRow(ctx, createAIRoleInstance,
		arg.TenantID,
		arg.RoleID,
		arg.Title,
		arg.MentorID,
		arg.Config,
	)
	var i AiRoleInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Title,
		&i.MentorID,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createAISuggestion = `-- name: CreateAISuggestion :one
INSERT INTO ai_suggestions (tenant_id, role_id, role_title, capability, title, content, context_data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, role_id, role_title, capability, title, content, context_data, status, reviewed_at, created_at
`

type CreateAISuggestionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	RoleID      string      `json:"role_id"`
	RoleTitle   string      `json:"role_title"`
	Capability  string      `json:"capability"`
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	ContextData []byte      `json:"context_data"`
}

func (q *Queries) CreateAISuggestion(ctx context.Context, arg CreateAISuggestionParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, createAISuggestion,
		arg.TenantID,
		arg.RoleID,
		arg.RoleTitle,
		arg.Capability,
		arg.Title,
		arg.Content,
		arg.ContextData,
	)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.RoleTitle,
		&i.Capability,
		&i.Title,
		&i.Content,
		&i.ContextData,
		&i.Status,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAIRoles = `-- name: DeactivateAIRoles :exec
UPDATE ai_role_instances SET is_active = false
WHERE tenant_id = $1
`

func (q *Queries) DeactivateAIRoles(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateAIRoles, tenantID)
	return err
}

const getAIRoleInstance = `-- name: GetAIRoleInstance :one
SELECT id, tenant_id, role_id, title, mentor_id, config, is_active, created_at FROM ai_role_instances
WHERE tenant_id = $1 AND role_id = $2
`

type GetAIRoleInstanceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleID   string      `json:"role_id"`
}

func (q *Queries) GetAIRoleInstance(ctx context.Context, arg GetAIRoleInstanceParams) (AiRoleInstance, error) {
	row := q.db.QueryRow(ctx, getAIRoleInstance, arg.TenantID, arg.RoleID)
	var i AiRoleInstance
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RoleID,
		&i.Title,
		&i.MentorID,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAIRoles = `-- name: ListActiveAIRoles :many
SELECT id, tenant_id, role_id, title, mentor_id, config, is_active, created_at FROM ai_role_instances
WHERE tenant_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveAIRoles(ctx context.Context, tenantID pgtype.UUID) ([]AiRoleInstance, error) {
	rows, err := q.db.Query(ctx, listActiveAIRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiRoleInstance{}
	for rows.Next() {
		var i AiRoleInstance
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleID,
			&i.Title,
			&i.MentorID,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSuggestions = `-- name: ListPendingSuggestions :many
SELECT id, tenant_id, role_id, role_title, capability, title, content, context_data, status, reviewed_at, created_at FROM ai_suggestions
WHERE tenant_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingSuggestions(ctx context.Context, tenantID pgtype.UUID) ([]AiSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingSuggestions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiSuggestion{}
	for rows.Next() {
		var i AiSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleID,
			&i.RoleTitle,
			&i.Capability,
			&i.Title,
			&i.Content,
			&i.ContextData,
			&i.Status,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSuggestionsForTenant = `-- name: ListRecentSuggestionsForTenant :many
SELECT id, tenant_id, role_id, role_title, capability, title, content, context_data, status, reviewed_at, created_at FROM ai_suggestions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentSuggestionsForTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListRecentSuggestionsForTenant(ctx context.Context, arg ListRecentSuggestionsForTenantParams) ([]AiSuggestion, error) {
	rows, err := q.db.Query(ctx, listRecentSuggestionsForTenant, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiSuggestion{}
	for rows.Next() {
		var i AiSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RoleID,
			&i.RoleTitle,
			&i.Capability,
			&i.Title,
			&i.Content,
			&i.ContextData,
			&i.Status,
			&i.ReviewedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSuggestionStatus = `-- name: UpdateSuggestionStatus :exec
UPDATE ai_suggestions SET status = $1, reviewed_at = now()
WHERE id = $2 AND tenant_id = $3
`

type UpdateSuggestionStatusParams struct {
	Status   string      `json:"status"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateSuggestionStatus(ctx context.Context, arg UpdateSuggestionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSuggestionStatus, arg.Status, arg.ID, arg.TenantID)
	return err
}
