// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, tenant_id, prefix, key_hash, name, scopes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tenant_id, prefix, key_hash, name, scopes, is_active, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Prefix   string      `json:"prefix"`
	KeyHash  string      `json:"key_hash"`
	Name     string      `json:"name"`
	Scopes   []string    `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.TenantID,
		arg.Prefix,
		arg.KeyHash,
		arg.Name,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Prefix,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT ak.id, ak.user_id, ak.tenant_id, ak.prefix, ak.key_hash, ak.name, ak.scopes, ak.is_active, ak.last_used_at, ak.created_at,
       u.role
FROM api_keys ak
JOIN users u ON u.id = ak.user_id AND u.is_active = true
WHERE ak.key_hash = $1 AND ak.is_active = true
`

type GetAPIKeyByHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Role       string             `json:"role"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Prefix,
		&i.KeyHash,
		&i.Name,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getTenantPlan = `-- name: GetTenantPlan :one
SELECT plan FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantPlan(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTenantPlan, id)
	var plan string
	err := row.Scan(&plan)
	return plan, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, tenant_id, prefix, key_hash, name, scopes, is_active, last_used_at, created_at
FROM api_keys
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Prefix,
			&i.KeyHash,
			&i.Name,
			&i.Scopes,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET is_active = false WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
