// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: career.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCareerLevel = `-- name: CreateCareerLevel :one
INSERT INTO career_levels (tenant_id, title, level_order, description, requirements)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, title, level_order, description, requirements, created_at
`

type CreateCareerLevelParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	Title        string      `json:"title"`
	LevelOrder   int32       `json:"level_order"`
	Description  string      `json:"description"`
	Requirements string      `json:"requirements"`
}

func (q *Queries) CreateCareerLevel(ctx context.Context, arg CreateCareerLevelParams) (CareerLevel, error) {
	row := q.db.QueryRow(ctx, createCareerLevel,
		arg.TenantID,
		arg.Title,
		arg.LevelOrder,
		arg.Description,
		arg.Requirements,
	)
	var i CareerLevel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.LevelOrder,
		&i.Description,
		&i.Requirements,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCareerLevel = `-- name: DeleteCareerLevel :exec
DELETE FROM career_levels WHERE id = $1
`

func (q *Queries) DeleteCareerLevel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCareerLevel, id)
	return err
}

const deleteCareerPath = `-- name: DeleteCareerPath :exec
DELETE FROM career_paths WHERE id = $1
`

func (q *Queries) DeleteCareerPath(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCareerPath, id)
	return err
}

const getCareerLevel = `-- name: GetCareerLevel :one
SELECT id, tenant_id, title, level_order, description, requirements, created_at FROM career_levels WHERE id = $1
`

func (q *Queries) GetCareerLevel(ctx context.Context, id pgtype.UUID) (CareerLevel, error) {
	row := q.db.QueryRow(ctx, getCareerLevel, id)
	var i CareerLevel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.LevelOrder,
		&i.Description,
		&i.Requirements,
		&i.CreatedAt,
	)
	return i, err
}

const getCareerPath = `-- name: GetCareerPath :one
SELECT id, employee_id, current_level_id, target_level_id, target_date, notes, created_at, updated_at FROM career_paths WHERE id = $1
`

func (q *Queries) GetCareerPath(ctx context.Context, id pgtype.UUID) (CareerPath, error) {
	row := q.db.QueryRow(ctx, getCareerPath, id)
	var i CareerPath
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CurrentLevelID,
		&i.TargetLevelID,
		&i.TargetDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCareerLevels = `-- name: ListCareerLevels :many
SELECT id, tenant_id, title, level_order, description, requirements, created_at FROM career_levels
WHERE tenant_id = $1
ORDER BY level_order ASC
`

func (q *Queries) ListCareerLevels(ctx context.Context, tenantID pgtype.UUID) ([]CareerLevel, error) {
	rows, err := q.db.Query(ctx, listCareerLevels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerLevel{}
	for rows.Next() {
		var i CareerLevel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.LevelOrder,
			&i.Description,
			&i.Requirements,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCareerPaths = `-- name: ListCareerPaths :many
SELECT cp.id, cp.employee_id, cp.current_level_id, cp.target_level_id, cp.target_date, cp.notes, cp.created_at, cp.updated_at,
       e.name AS employee_name,
       cl_cur.title AS current_level_title,
       cl_cur.level_order AS current_level_order,
       cl_tgt.title AS target_level_title,
       cl_tgt.level_order AS target_level_order
FROM career_paths cp
JOIN employees e ON e.id = cp.employee_id
LEFT JOIN career_levels cl_cur ON cl_cur.id = cp.current_level_id
LEFT JOIN career_levels cl_tgt ON cl_tgt.id = cp.target_level_id
WHERE e.tenant_id = $1
ORDER BY e.name
`

type ListCareerPathsRow struct {
	ID                pgtype.UUID        `json:"id"`
	EmployeeID        pgtype.UUID        `json:"employee_id"`
	CurrentLevelID    pgtype.UUID        `json:"current_level_id"`
	TargetLevelID     pgtype.UUID        `json:"target_level_id"`
	TargetDate        pgtype.Date        `json:"target_date"`
	Notes             string             `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	EmployeeName      string             `json:"employee_name"`
	CurrentLevelTitle pgtype.Text        `json:"current_level_title"`
	CurrentLevelOrder pgtype.Int4        `json:"current_level_order"`
	TargetLevelTitle  pgtype.Text        `json:"target_level_title"`
	TargetLevelOrder  pgtype.Int4        `json:"target_level_order"`
}

func (q *Queries) ListCareerPaths(ctx context.Context, tenantID pgtype.UUID) ([]ListCareerPathsRow, error) {
	rows, err := q.db.Query(ctx, listCareerPaths, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCareerPathsRow{}
	for rows.Next() {
		var i ListCareerPathsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.CurrentLevelID,
			&i.TargetLevelID,
			&i.TargetDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.CurrentLevelTitle,
			&i.CurrentLevelOrder,
			&i.TargetLevelTitle,
			&i.TargetLevelOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCareerLevel = `-- name: UpdateCareerLevel :one
UPDATE career_levels SET
    title = $2,
    level_order = $3,
    description = $4,
    requirements = $5
WHERE id = $1
RETURNING id, tenant_id, title, level_order, description, requirements, created_at
`

type UpdateCareerLevelParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	LevelOrder   int32       `json:"level_order"`
	Description  string      `json:"description"`
	Requirements string      `json:"requirements"`
}

func (q *Queries) UpdateCareerLevel(ctx context.Context, arg UpdateCareerLevelParams) (CareerLevel, error) {
	row := q.db.QueryRow(ctx, updateCareerLevel,
		arg.ID,
		arg.Title,
		arg.LevelOrder,
		arg.Description,
		arg.Requirements,
	)
	var i CareerLevel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.LevelOrder,
		&i.Description,
		&i.Requirements,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCareerPath = `-- name: UpsertCareerPath :one
INSERT INTO career_paths (employee_id, current_level_id, target_level_id, target_date, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (employee_id) DO UPDATE SET
    current_level_id = EXCLUDED.current_level_id,
    target_level_id = EXCLUDED.target_level_id,
    target_date = EXCLUDED.target_date,
    notes = EXCLUDED.notes,
    updated_at = NOW()
RETURNING id, employee_id, current_level_id, target_level_id, target_date, notes, created_at, updated_at
`

type UpsertCareerPathParams struct {
	EmployeeID     pgtype.UUID `json:"employee_id"`
	CurrentLevelID pgtype.UUID `json:"current_level_id"`
	TargetLevelID  pgtype.UUID `json:"target_level_id"`
	TargetDate     pgtype.Date `json:"target_date"`
	Notes          string      `json:"notes"`
}

func (q *Queries) UpsertCareerPath(ctx context.Context, arg UpsertCareerPathParams) (CareerPath, error) {
	row := q.db.QueryRow(ctx, upsertCareerPath,
		arg.EmployeeID,
		arg.CurrentLevelID,
		arg.TargetLevelID,
		arg.TargetDate,
		arg.Notes,
	)
	var i CareerPath
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.CurrentLevelID,
		&i.TargetLevelID,
		&i.TargetDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyCareerLevelTenant = `-- name: VerifyCareerLevelTenant :one
SELECT tenant_id FROM career_levels WHERE id = $1
`

func (q *Queries) VerifyCareerLevelTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyCareerLevelTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
