// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chase_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChaseLog = `-- name: CreateChaseLog :one
INSERT INTO chase_logs (tenant_id, employee_id, report_date, step, action, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, employee_id, report_date, step, action, message, chased_at, channel
`

type CreateChaseLogParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
	Step       int32       `json:"step"`
	Action     string      `json:"action"`
	Message    string      `json:"message"`
}

func (q *Queries) CreateChaseLog(ctx context.Context, arg CreateChaseLogParams) (ChaseLog, error) {
	row := q.db.QueryRow(ctx, createChaseLog,
		arg.TenantID,
		arg.EmployeeID,
		arg.ReportDate,
		arg.Step,
		arg.Action,
		arg.Message,
	)
	var i ChaseLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ReportDate,
		&i.Step,
		&i.Action,
		&i.Message,
		&i.ChasedAt,
		&i.Channel,
	)
	return i, err
}

const getChaseLogsForDate = `-- name: GetChaseLogsForDate :many
SELECT id, tenant_id, employee_id, report_date, step, action, message, chased_at
FROM chase_logs
WHERE employee_id = $1 AND report_date = $2
ORDER BY step
`

type GetChaseLogsForDateParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

type GetChaseLogsForDateRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	ReportDate pgtype.Date        `json:"report_date"`
	Step       int32              `json:"step"`
	Action     string             `json:"action"`
	Message    string             `json:"message"`
	ChasedAt   pgtype.Timestamptz `json:"chased_at"`
}

func (q *Queries) GetChaseLogsForDate(ctx context.Context, arg GetChaseLogsForDateParams) ([]GetChaseLogsForDateRow, error) {
	rows, err := q.db.Query(ctx, getChaseLogsForDate, arg.EmployeeID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChaseLogsForDateRow{}
	for rows.Next() {
		var i GetChaseLogsForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ReportDate,
			&i.Step,
			&i.Action,
			&i.Message,
			&i.ChasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastChaseStep = `-- name: GetLastChaseStep :one
SELECT COALESCE(MAX(step), 0) as last_step FROM chase_logs
WHERE employee_id = $1 AND report_date = $2
`

type GetLastChaseStepParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) GetLastChaseStep(ctx context.Context, arg GetLastChaseStepParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getLastChaseStep, arg.EmployeeID, arg.ReportDate)
	var last_step interface{}
	err := row.Scan(&last_step)
	return last_step, err
}
