// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: communication_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByType = `-- name: CountEventsByType :many
SELECT event_type, COUNT(*)::int AS count
FROM communication_events
WHERE tenant_id = $1 AND occurred_at >= $2
GROUP BY event_type
ORDER BY count DESC
`

type CountEventsByTypeParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type CountEventsByTypeRow struct {
	EventType string `json:"event_type"`
	Count     int32  `json:"count"`
}

func (q *Queries) CountEventsByType(ctx context.Context, arg CountEventsByTypeParams) ([]CountEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countEventsByType, arg.TenantID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByTypeRow{}
	for rows.Next() {
		var i CountEventsByTypeRow
		if err := rows.Scan(&i.EventType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCommunicationEvent = `-- name: CreateCommunicationEvent :one
INSERT INTO communication_events (tenant_id, source_type, source_id, platform,
  event_type, actor_id, target_id, related_task_id, related_project_id,
  related_goal_id, payload, confidence, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, source_type, source_id, platform, event_type, actor_id, target_id, related_task_id, related_project_id, related_goal_id, payload, confidence, occurred_at, created_at
`

type CreateCommunicationEventParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	SourceType       string             `json:"source_type"`
	SourceID         pgtype.UUID        `json:"source_id"`
	Platform         string             `json:"platform"`
	EventType        string             `json:"event_type"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	TargetID         pgtype.UUID        `json:"target_id"`
	RelatedTaskID    pgtype.UUID        `json:"related_task_id"`
	RelatedProjectID pgtype.UUID        `json:"related_project_id"`
	RelatedGoalID    pgtype.UUID        `json:"related_goal_id"`
	Payload          []byte             `json:"payload"`
	Confidence       pgtype.Numeric     `json:"confidence"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateCommunicationEvent(ctx context.Context, arg CreateCommunicationEventParams) (CommunicationEvent, error) {
	row := q.db.QueryRow(ctx, createCommunicationEvent,
		arg.TenantID,
		arg.SourceType,
		arg.SourceID,
		arg.Platform,
		arg.EventType,
		arg.ActorID,
		arg.TargetID,
		arg.RelatedTaskID,
		arg.RelatedProjectID,
		arg.RelatedGoalID,
		arg.Payload,
		arg.Confidence,
		arg.OccurredAt,
	)
	var i CommunicationEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SourceType,
		&i.SourceID,
		&i.Platform,
		&i.EventType,
		&i.ActorID,
		&i.TargetID,
		&i.RelatedTaskID,
		&i.RelatedProjectID,
		&i.RelatedGoalID,
		&i.Payload,
		&i.Confidence,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCommunicationEvents = `-- name: ListCommunicationEvents :many
SELECT ce.id, ce.tenant_id, ce.source_type, ce.source_id, ce.platform, ce.event_type, ce.actor_id, ce.target_id, ce.related_task_id, ce.related_project_id, ce.related_goal_id, ce.payload, ce.confidence, ce.occurred_at, ce.created_at,
  actor.name AS actor_name,
  target.name AS target_name
FROM communication_events ce
LEFT JOIN employees actor ON ce.actor_id = actor.id
LEFT JOIN employees target ON ce.target_id = target.id
WHERE ce.tenant_id = $1
  AND ce.occurred_at >= $2
ORDER BY ce.occurred_at DESC
LIMIT $3
`

type ListCommunicationEventsParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Limit      int32              `json:"limit"`
}

type ListCommunicationEventsRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	SourceType       string             `json:"source_type"`
	SourceID         pgtype.UUID        `json:"source_id"`
	Platform         string             `json:"platform"`
	EventType        string             `json:"event_type"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	TargetID         pgtype.UUID        `json:"target_id"`
	RelatedTaskID    pgtype.UUID        `json:"related_task_id"`
	RelatedProjectID pgtype.UUID        `json:"related_project_id"`
	RelatedGoalID    pgtype.UUID        `json:"related_goal_id"`
	Payload          []byte             `json:"payload"`
	Confidence       pgtype.Numeric     `json:"confidence"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActorName        pgtype.Text        `json:"actor_name"`
	TargetName       pgtype.Text        `json:"target_name"`
}

func (q *Queries) ListCommunicationEvents(ctx context.Context, arg ListCommunicationEventsParams) ([]ListCommunicationEventsRow, error) {
	rows, err := q.db.Query(ctx, listCommunicationEvents, arg.TenantID, arg.OccurredAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommunicationEventsRow{}
	for rows.Next() {
		var i ListCommunicationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.SourceID,
			&i.Platform,
			&i.EventType,
			&i.ActorID,
			&i.TargetID,
			&i.RelatedTaskID,
			&i.RelatedProjectID,
			&i.RelatedGoalID,
			&i.Payload,
			&i.Confidence,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ActorName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByPerson = `-- name: ListEventsByPerson :many
SELECT id, tenant_id, source_type, source_id, platform, event_type, actor_id, target_id, related_task_id, related_project_id, related_goal_id, payload, confidence, occurred_at, created_at FROM communication_events
WHERE tenant_id = $1
  AND (actor_id = $2 OR target_id = $2)
  AND occurred_at >= $3
ORDER BY occurred_at DESC
`

type ListEventsByPersonParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListEventsByPerson(ctx context.Context, arg ListEventsByPersonParams) ([]CommunicationEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByPerson, arg.TenantID, arg.ActorID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommunicationEvent{}
	for rows.Next() {
		var i CommunicationEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.SourceID,
			&i.Platform,
			&i.EventType,
			&i.ActorID,
			&i.TargetID,
			&i.RelatedTaskID,
			&i.RelatedProjectID,
			&i.RelatedGoalID,
			&i.Payload,
			&i.Confidence,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByType = `-- name: ListEventsByType :many
SELECT ce.id, ce.tenant_id, ce.source_type, ce.source_id, ce.platform, ce.event_type, ce.actor_id, ce.target_id, ce.related_task_id, ce.related_project_id, ce.related_goal_id, ce.payload, ce.confidence, ce.occurred_at, ce.created_at,
  actor.name AS actor_name,
  target.name AS target_name
FROM communication_events ce
LEFT JOIN employees actor ON ce.actor_id = actor.id
LEFT JOIN employees target ON ce.target_id = target.id
WHERE ce.tenant_id = $1
  AND ce.event_type = $2
  AND ce.occurred_at >= $3
ORDER BY ce.occurred_at DESC
LIMIT $4
`

type ListEventsByTypeParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Limit      int32              `json:"limit"`
}

type ListEventsByTypeRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	SourceType       string             `json:"source_type"`
	SourceID         pgtype.UUID        `json:"source_id"`
	Platform         string             `json:"platform"`
	EventType        string             `json:"event_type"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	TargetID         pgtype.UUID        `json:"target_id"`
	RelatedTaskID    pgtype.UUID        `json:"related_task_id"`
	RelatedProjectID pgtype.UUID        `json:"related_project_id"`
	RelatedGoalID    pgtype.UUID        `json:"related_goal_id"`
	Payload          []byte             `json:"payload"`
	Confidence       pgtype.Numeric     `json:"confidence"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ActorName        pgtype.Text        `json:"actor_name"`
	TargetName       pgtype.Text        `json:"target_name"`
}

func (q *Queries) ListEventsByType(ctx context.Context, arg ListEventsByTypeParams) ([]ListEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listEventsByType,
		arg.TenantID,
		arg.EventType,
		arg.OccurredAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByTypeRow{}
	for rows.Next() {
		var i ListEventsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SourceType,
			&i.SourceID,
			&i.Platform,
			&i.EventType,
			&i.ActorID,
			&i.TargetID,
			&i.RelatedTaskID,
			&i.RelatedProjectID,
			&i.RelatedGoalID,
			&i.Payload,
			&i.Confidence,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.ActorName,
			&i.TargetName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
