// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (tenant_id, name, telegram_id, culture_code, role, invite_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at
`

type CreateEmployeeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	TelegramID  pgtype.Int8 `json:"telegram_id"`
	CultureCode string      `json:"culture_code"`
	Role        string      `json:"role"`
	InviteCode  pgtype.Text `json:"invite_code"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.TenantID,
		arg.Name,
		arg.TelegramID,
		arg.CultureCode,
		arg.Role,
		arg.InviteCode,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at FROM employees WHERE id = $1 AND tenant_id = $2
`

type GetEmployeeParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.ID, arg.TenantID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByInviteCode = `-- name: GetEmployeeByInviteCode :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at FROM employees WHERE invite_code = $1 AND telegram_id IS NULL
`

func (q *Queries) GetEmployeeByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByInviteCode, inviteCode)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getEmployeeByTelegramID = `-- name: GetEmployeeByTelegramID :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at FROM employees WHERE telegram_id = $1
`

func (q *Queries) GetEmployeeByTelegramID(ctx context.Context, telegramID pgtype.Int8) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByTelegramID, telegramID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at FROM employees WHERE tenant_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListActiveEmployees(ctx context.Context, tenantID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithoutReport = `-- name: ListEmployeesWithoutReport :many
SELECT e.id, e.tenant_id, e.name, e.telegram_id, e.culture_code, e.role, e.invite_code, e.is_active, e.created_at FROM employees e
LEFT JOIN reports r ON e.id = r.employee_id AND r.report_date = $2
WHERE e.tenant_id = $1 AND e.is_active = true AND e.role = 'member' AND r.id IS NULL
`

type ListEmployeesWithoutReportParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) ListEmployeesWithoutReport(ctx context.Context, arg ListEmployeesWithoutReportParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithoutReport, arg.TenantID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeCulture = `-- name: UpdateEmployeeCulture :exec
UPDATE employees SET culture_code = $2 WHERE id = $1
`

type UpdateEmployeeCultureParams struct {
	ID          pgtype.UUID `json:"id"`
	CultureCode string      `json:"culture_code"`
}

func (q *Queries) UpdateEmployeeCulture(ctx context.Context, arg UpdateEmployeeCultureParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeCulture, arg.ID, arg.CultureCode)
	return err
}

const updateEmployeeTelegramID = `-- name: UpdateEmployeeTelegramID :exec
UPDATE employees SET telegram_id = $2 WHERE id = $1
`

type UpdateEmployeeTelegramIDParams struct {
	ID         pgtype.UUID `json:"id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

func (q *Queries) UpdateEmployeeTelegramID(ctx context.Context, arg UpdateEmployeeTelegramIDParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeTelegramID, arg.ID, arg.TelegramID)
	return err
}
