// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (tenant_id, name, telegram_id, culture_code, role, invite_code)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel
`

type CreateEmployeeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	TelegramID  pgtype.Int8 `json:"telegram_id"`
	CultureCode string      `json:"culture_code"`
	Role        string      `json:"role"`
	InviteCode  pgtype.Text `json:"invite_code"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.TenantID,
		arg.Name,
		arg.TelegramID,
		arg.CultureCode,
		arg.Role,
		arg.InviteCode,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE id = $1 AND tenant_id = $2
`

type GetEmployeeParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEmployee(ctx context.Context, arg GetEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployee, arg.ID, arg.TenantID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployeeByInviteCode = `-- name: GetEmployeeByInviteCode :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE invite_code = $1 AND telegram_id IS NULL
`

func (q *Queries) GetEmployeeByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByInviteCode, inviteCode)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployeeByLarkID = `-- name: GetEmployeeByLarkID :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE lark_id = $1 AND is_active = true
`

func (q *Queries) GetEmployeeByLarkID(ctx context.Context, larkID pgtype.Text) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByLarkID, larkID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployeeBySignalPhone = `-- name: GetEmployeeBySignalPhone :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE signal_phone = $1 AND is_active = true
`

func (q *Queries) GetEmployeeBySignalPhone(ctx context.Context, signalPhone pgtype.Text) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeBySignalPhone, signalPhone)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployeeBySlackID = `-- name: GetEmployeeBySlackID :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE slack_id = $1 AND is_active = true
`

func (q *Queries) GetEmployeeBySlackID(ctx context.Context, slackID pgtype.Text) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeBySlackID, slackID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const getEmployeeByTelegramID = `-- name: GetEmployeeByTelegramID :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE telegram_id = $1
`

func (q *Queries) GetEmployeeByTelegramID(ctx context.Context, telegramID pgtype.Int8) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByTelegramID, telegramID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
	)
	return i, err
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel FROM employees WHERE tenant_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListActiveEmployees(ctx context.Context, tenantID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.SignalPhone,
			&i.SlackID,
			&i.LarkID,
			&i.PreferredChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithChannels = `-- name: ListEmployeesWithChannels :many
SELECT id, tenant_id, name, telegram_id, signal_phone, slack_id, lark_id, preferred_channel, culture_code, role, is_active
FROM employees
WHERE tenant_id = $1 AND is_active = true
ORDER BY name
`

type ListEmployeesWithChannelsRow struct {
	ID               pgtype.UUID `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	Name             string      `json:"name"`
	TelegramID       pgtype.Int8 `json:"telegram_id"`
	SignalPhone      pgtype.Text `json:"signal_phone"`
	SlackID          pgtype.Text `json:"slack_id"`
	LarkID           pgtype.Text `json:"lark_id"`
	PreferredChannel string      `json:"preferred_channel"`
	CultureCode      string      `json:"culture_code"`
	Role             string      `json:"role"`
	IsActive         bool        `json:"is_active"`
}

func (q *Queries) ListEmployeesWithChannels(ctx context.Context, tenantID pgtype.UUID) ([]ListEmployeesWithChannelsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithChannels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesWithChannelsRow{}
	for rows.Next() {
		var i ListEmployeesWithChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.SignalPhone,
			&i.SlackID,
			&i.LarkID,
			&i.PreferredChannel,
			&i.CultureCode,
			&i.Role,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithoutReport = `-- name: ListEmployeesWithoutReport :many
SELECT e.id, e.tenant_id, e.name, e.telegram_id, e.culture_code, e.role, e.invite_code, e.is_active, e.created_at, e.signal_phone, e.slack_id, e.lark_id, e.preferred_channel FROM employees e
LEFT JOIN reports r ON e.id = r.employee_id AND r.report_date = $2
WHERE e.tenant_id = $1 AND e.is_active = true AND e.role = 'member' AND r.id IS NULL
`

type ListEmployeesWithoutReportParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) ListEmployeesWithoutReport(ctx context.Context, arg ListEmployeesWithoutReportParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithoutReport, arg.TenantID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.SignalPhone,
			&i.SlackID,
			&i.LarkID,
			&i.PreferredChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployeeChannels = `-- name: UpdateEmployeeChannels :exec
UPDATE employees
SET signal_phone = $2, slack_id = $3, lark_id = $4, preferred_channel = $5
WHERE id = $1
`

type UpdateEmployeeChannelsParams struct {
	ID               pgtype.UUID `json:"id"`
	SignalPhone      pgtype.Text `json:"signal_phone"`
	SlackID          pgtype.Text `json:"slack_id"`
	LarkID           pgtype.Text `json:"lark_id"`
	PreferredChannel string      `json:"preferred_channel"`
}

func (q *Queries) UpdateEmployeeChannels(ctx context.Context, arg UpdateEmployeeChannelsParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeChannels,
		arg.ID,
		arg.SignalPhone,
		arg.SlackID,
		arg.LarkID,
		arg.PreferredChannel,
	)
	return err
}

const updateEmployeeCulture = `-- name: UpdateEmployeeCulture :exec
UPDATE employees SET culture_code = $2 WHERE id = $1
`

type UpdateEmployeeCultureParams struct {
	ID          pgtype.UUID `json:"id"`
	CultureCode string      `json:"culture_code"`
}

func (q *Queries) UpdateEmployeeCulture(ctx context.Context, arg UpdateEmployeeCultureParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeCulture, arg.ID, arg.CultureCode)
	return err
}

const updateEmployeePreferredChannel = `-- name: UpdateEmployeePreferredChannel :exec
UPDATE employees SET preferred_channel = $2 WHERE id = $1
`

type UpdateEmployeePreferredChannelParams struct {
	ID               pgtype.UUID `json:"id"`
	PreferredChannel string      `json:"preferred_channel"`
}

func (q *Queries) UpdateEmployeePreferredChannel(ctx context.Context, arg UpdateEmployeePreferredChannelParams) error {
	_, err := q.db.Exec(ctx, updateEmployeePreferredChannel, arg.ID, arg.PreferredChannel)
	return err
}

const updateEmployeeTelegramID = `-- name: UpdateEmployeeTelegramID :exec
UPDATE employees SET telegram_id = $2 WHERE id = $1
`

type UpdateEmployeeTelegramIDParams struct {
	ID         pgtype.UUID `json:"id"`
	TelegramID pgtype.Int8 `json:"telegram_id"`
}

func (q *Queries) UpdateEmployeeTelegramID(ctx context.Context, arg UpdateEmployeeTelegramIDParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeTelegramID, arg.ID, arg.TelegramID)
	return err
}
