// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: engagements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveEngagementAction = `-- name: ApproveEngagementAction :exec
UPDATE engagement_actions SET status = 'approved', approved_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) ApproveEngagementAction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, approveEngagementAction, id)
	return err
}

const closeEngagement = `-- name: CloseEngagement :exec
UPDATE engagements SET phase = 'closed', closed_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) CloseEngagement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, closeEngagement, id)
	return err
}

const countEngagementActionsByStatus = `-- name: CountEngagementActionsByStatus :many
SELECT status, COUNT(*)::int AS count
FROM engagement_actions WHERE engagement_id = $1
GROUP BY status
`

type CountEngagementActionsByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountEngagementActionsByStatus(ctx context.Context, engagementID pgtype.UUID) ([]CountEngagementActionsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countEngagementActionsByStatus, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEngagementActionsByStatusRow{}
	for rows.Next() {
		var i CountEngagementActionsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEngagement = `-- name: CreateEngagement :one
INSERT INTO engagements (tenant_id, title, problem_statement, tier, category, phase,
  diagnosis_data, mentor_id, culture_code, next_check_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, title, problem_statement, tier, category, phase, diagnosis_questions, diagnosis_answers, diagnosis_data, analysis, plan, progress_pct, next_check_at, mentor_id, culture_code, created_at, updated_at, closed_at
`

type CreateEngagementParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Title            string             `json:"title"`
	ProblemStatement string             `json:"problem_statement"`
	Tier             string             `json:"tier"`
	Category         pgtype.Text        `json:"category"`
	Phase            string             `json:"phase"`
	DiagnosisData    []byte             `json:"diagnosis_data"`
	MentorID         pgtype.Text        `json:"mentor_id"`
	CultureCode      pgtype.Text        `json:"culture_code"`
	NextCheckAt      pgtype.Timestamptz `json:"next_check_at"`
}

func (q *Queries) CreateEngagement(ctx context.Context, arg CreateEngagementParams) (Engagement, error) {
	row := q.db.QueryRow(ctx, createEngagement,
		arg.TenantID,
		arg.Title,
		arg.ProblemStatement,
		arg.Tier,
		arg.Category,
		arg.Phase,
		arg.DiagnosisData,
		arg.MentorID,
		arg.CultureCode,
		arg.NextCheckAt,
	)
	var i Engagement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ProblemStatement,
		&i.Tier,
		&i.Category,
		&i.Phase,
		&i.DiagnosisQuestions,
		&i.DiagnosisAnswers,
		&i.DiagnosisData,
		&i.Analysis,
		&i.Plan,
		&i.ProgressPct,
		&i.NextCheckAt,
		&i.MentorID,
		&i.CultureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createEngagementAction = `-- name: CreateEngagementAction :one
INSERT INTO engagement_actions (engagement_id, action_type, title, description,
  params, owner_name, priority, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, engagement_id, action_type, title, description, params, owner_name, priority, due_at, status, approved_at, executed_at, result, linked_task_id, linked_meeting_id, created_at, updated_at
`

type CreateEngagementActionParams struct {
	EngagementID pgtype.UUID        `json:"engagement_id"`
	ActionType   string             `json:"action_type"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Params       []byte             `json:"params"`
	OwnerName    pgtype.Text        `json:"owner_name"`
	Priority     pgtype.Text        `json:"priority"`
	DueAt        pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateEngagementAction(ctx context.Context, arg CreateEngagementActionParams) (EngagementAction, error) {
	row := q.db.QueryRow(ctx, createEngagementAction,
		arg.EngagementID,
		arg.ActionType,
		arg.Title,
		arg.Description,
		arg.Params,
		arg.OwnerName,
		arg.Priority,
		arg.DueAt,
	)
	var i EngagementAction
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.ActionType,
		&i.Title,
		&i.Description,
		&i.Params,
		&i.OwnerName,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.ApprovedAt,
		&i.ExecutedAt,
		&i.Result,
		&i.LinkedTaskID,
		&i.LinkedMeetingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEngagement = `-- name: GetEngagement :one
SELECT id, tenant_id, title, problem_statement, tier, category, phase, diagnosis_questions, diagnosis_answers, diagnosis_data, analysis, plan, progress_pct, next_check_at, mentor_id, culture_code, created_at, updated_at, closed_at FROM engagements WHERE id = $1
`

func (q *Queries) GetEngagement(ctx context.Context, id pgtype.UUID) (Engagement, error) {
	row := q.db.QueryRow(ctx, getEngagement, id)
	var i Engagement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ProblemStatement,
		&i.Tier,
		&i.Category,
		&i.Phase,
		&i.DiagnosisQuestions,
		&i.DiagnosisAnswers,
		&i.DiagnosisData,
		&i.Analysis,
		&i.Plan,
		&i.ProgressPct,
		&i.NextCheckAt,
		&i.MentorID,
		&i.CultureCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getEngagementAction = `-- name: GetEngagementAction :one
SELECT id, engagement_id, action_type, title, description, params, owner_name, priority, due_at, status, approved_at, executed_at, result, linked_task_id, linked_meeting_id, created_at, updated_at FROM engagement_actions WHERE id = $1
`

func (q *Queries) GetEngagementAction(ctx context.Context, id pgtype.UUID) (EngagementAction, error) {
	row := q.db.QueryRow(ctx, getEngagementAction, id)
	var i EngagementAction
	err := row.Scan(
		&i.ID,
		&i.EngagementID,
		&i.ActionType,
		&i.Title,
		&i.Description,
		&i.Params,
		&i.OwnerName,
		&i.Priority,
		&i.DueAt,
		&i.Status,
		&i.ApprovedAt,
		&i.ExecutedAt,
		&i.Result,
		&i.LinkedTaskID,
		&i.LinkedMeetingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkEngagementActionMeeting = `-- name: LinkEngagementActionMeeting :exec
UPDATE engagement_actions SET linked_meeting_id = $2, updated_at = now() WHERE id = $1
`

type LinkEngagementActionMeetingParams struct {
	ID              pgtype.UUID `json:"id"`
	LinkedMeetingID pgtype.UUID `json:"linked_meeting_id"`
}

func (q *Queries) LinkEngagementActionMeeting(ctx context.Context, arg LinkEngagementActionMeetingParams) error {
	_, err := q.db.Exec(ctx, linkEngagementActionMeeting, arg.ID, arg.LinkedMeetingID)
	return err
}

const linkEngagementActionTask = `-- name: LinkEngagementActionTask :exec
UPDATE engagement_actions SET linked_task_id = $2, updated_at = now() WHERE id = $1
`

type LinkEngagementActionTaskParams struct {
	ID           pgtype.UUID `json:"id"`
	LinkedTaskID pgtype.UUID `json:"linked_task_id"`
}

func (q *Queries) LinkEngagementActionTask(ctx context.Context, arg LinkEngagementActionTaskParams) error {
	_, err := q.db.Exec(ctx, linkEngagementActionTask, arg.ID, arg.LinkedTaskID)
	return err
}

const listActiveEngagements = `-- name: ListActiveEngagements :many
SELECT id, tenant_id, title, problem_statement, tier, category, phase, diagnosis_questions, diagnosis_answers, diagnosis_data, analysis, plan, progress_pct, next_check_at, mentor_id, culture_code, created_at, updated_at, closed_at FROM engagements
WHERE tenant_id = $1 AND phase NOT IN ('closed')
ORDER BY updated_at DESC
`

func (q *Queries) ListActiveEngagements(ctx context.Context, tenantID pgtype.UUID) ([]Engagement, error) {
	rows, err := q.db.Query(ctx, listActiveEngagements, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Engagement{}
	for rows.Next() {
		var i Engagement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ProblemStatement,
			&i.Tier,
			&i.Category,
			&i.Phase,
			&i.DiagnosisQuestions,
			&i.DiagnosisAnswers,
			&i.DiagnosisData,
			&i.Analysis,
			&i.Plan,
			&i.ProgressPct,
			&i.NextCheckAt,
			&i.MentorID,
			&i.CultureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedEngagementActions = `-- name: ListApprovedEngagementActions :many
SELECT id, engagement_id, action_type, title, description, params, owner_name, priority, due_at, status, approved_at, executed_at, result, linked_task_id, linked_meeting_id, created_at, updated_at FROM engagement_actions
WHERE engagement_id = $1 AND status = 'approved'
ORDER BY created_at
`

func (q *Queries) ListApprovedEngagementActions(ctx context.Context, engagementID pgtype.UUID) ([]EngagementAction, error) {
	rows, err := q.db.Query(ctx, listApprovedEngagementActions, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngagementAction{}
	for rows.Next() {
		var i EngagementAction
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ActionType,
			&i.Title,
			&i.Description,
			&i.Params,
			&i.OwnerName,
			&i.Priority,
			&i.DueAt,
			&i.Status,
			&i.ApprovedAt,
			&i.ExecutedAt,
			&i.Result,
			&i.LinkedTaskID,
			&i.LinkedMeetingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementActions = `-- name: ListEngagementActions :many
SELECT id, engagement_id, action_type, title, description, params, owner_name, priority, due_at, status, approved_at, executed_at, result, linked_task_id, linked_meeting_id, created_at, updated_at FROM engagement_actions
WHERE engagement_id = $1
ORDER BY
  CASE priority
    WHEN 'critical' THEN 0
    WHEN 'high' THEN 1
    WHEN 'medium' THEN 2
    WHEN 'low' THEN 3
    ELSE 4
  END,
  created_at
`

func (q *Queries) ListEngagementActions(ctx context.Context, engagementID pgtype.UUID) ([]EngagementAction, error) {
	rows, err := q.db.Query(ctx, listEngagementActions, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EngagementAction{}
	for rows.Next() {
		var i EngagementAction
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ActionType,
			&i.Title,
			&i.Description,
			&i.Params,
			&i.OwnerName,
			&i.Priority,
			&i.DueAt,
			&i.Status,
			&i.ApprovedAt,
			&i.ExecutedAt,
			&i.Result,
			&i.LinkedTaskID,
			&i.LinkedMeetingID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementActionsWithLinks = `-- name: ListEngagementActionsWithLinks :many
SELECT ea.id, ea.engagement_id, ea.action_type, ea.title, ea.description, ea.params, ea.owner_name, ea.priority, ea.due_at, ea.status, ea.approved_at, ea.executed_at, ea.result, ea.linked_task_id, ea.linked_meeting_id, ea.created_at, ea.updated_at,
  t.status AS task_status,
  m.mood AS meeting_mood
FROM engagement_actions ea
LEFT JOIN tasks t ON ea.linked_task_id = t.id
LEFT JOIN meetings m ON ea.linked_meeting_id = m.id
WHERE ea.engagement_id = $1
ORDER BY ea.created_at
`

type ListEngagementActionsWithLinksRow struct {
	ID              pgtype.UUID        `json:"id"`
	EngagementID    pgtype.UUID        `json:"engagement_id"`
	ActionType      string             `json:"action_type"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Params          []byte             `json:"params"`
	OwnerName       pgtype.Text        `json:"owner_name"`
	Priority        pgtype.Text        `json:"priority"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	Status          string             `json:"status"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	ExecutedAt      pgtype.Timestamptz `json:"executed_at"`
	Result          []byte             `json:"result"`
	LinkedTaskID    pgtype.UUID        `json:"linked_task_id"`
	LinkedMeetingID pgtype.UUID        `json:"linked_meeting_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TaskStatus      pgtype.Text        `json:"task_status"`
	MeetingMood     pgtype.Text        `json:"meeting_mood"`
}

func (q *Queries) ListEngagementActionsWithLinks(ctx context.Context, engagementID pgtype.UUID) ([]ListEngagementActionsWithLinksRow, error) {
	rows, err := q.db.Query(ctx, listEngagementActionsWithLinks, engagementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEngagementActionsWithLinksRow{}
	for rows.Next() {
		var i ListEngagementActionsWithLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.EngagementID,
			&i.ActionType,
			&i.Title,
			&i.Description,
			&i.Params,
			&i.OwnerName,
			&i.Priority,
			&i.DueAt,
			&i.Status,
			&i.ApprovedAt,
			&i.ExecutedAt,
			&i.Result,
			&i.LinkedTaskID,
			&i.LinkedMeetingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskStatus,
			&i.MeetingMood,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementsByTenant = `-- name: ListEngagementsByTenant :many
SELECT id, tenant_id, title, problem_statement, tier, category, phase, diagnosis_questions, diagnosis_answers, diagnosis_data, analysis, plan, progress_pct, next_check_at, mentor_id, culture_code, created_at, updated_at, closed_at FROM engagements
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEngagementsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListEngagementsByTenant(ctx context.Context, arg ListEngagementsByTenantParams) ([]Engagement, error) {
	rows, err := q.db.Query(ctx, listEngagementsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Engagement{}
	for rows.Next() {
		var i Engagement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ProblemStatement,
			&i.Tier,
			&i.Category,
			&i.Phase,
			&i.DiagnosisQuestions,
			&i.DiagnosisAnswers,
			&i.DiagnosisData,
			&i.Analysis,
			&i.Plan,
			&i.ProgressPct,
			&i.NextCheckAt,
			&i.MentorID,
			&i.CultureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementsForTracking = `-- name: ListEngagementsForTracking :many
SELECT id, tenant_id, title, problem_statement, tier, category, phase, diagnosis_questions, diagnosis_answers, diagnosis_data, analysis, plan, progress_pct, next_check_at, mentor_id, culture_code, created_at, updated_at, closed_at FROM engagements
WHERE phase IN ('executing', 'tracking')
  AND (next_check_at IS NULL OR next_check_at <= now())
`

func (q *Queries) ListEngagementsForTracking(ctx context.Context) ([]Engagement, error) {
	rows, err := q.db.Query(ctx, listEngagementsForTracking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Engagement{}
	for rows.Next() {
		var i Engagement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ProblemStatement,
			&i.Tier,
			&i.Category,
			&i.Phase,
			&i.DiagnosisQuestions,
			&i.DiagnosisAnswers,
			&i.DiagnosisData,
			&i.Analysis,
			&i.Plan,
			&i.ProgressPct,
			&i.NextCheckAt,
			&i.MentorID,
			&i.CultureCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEngagementActionDone = `-- name: MarkEngagementActionDone :exec
UPDATE engagement_actions SET
  status = 'done', executed_at = now(), result = $2, updated_at = now()
WHERE id = $1
`

type MarkEngagementActionDoneParams struct {
	ID     pgtype.UUID `json:"id"`
	Result []byte      `json:"result"`
}

func (q *Queries) MarkEngagementActionDone(ctx context.Context, arg MarkEngagementActionDoneParams) error {
	_, err := q.db.Exec(ctx, markEngagementActionDone, arg.ID, arg.Result)
	return err
}

const markEngagementActionFailed = `-- name: MarkEngagementActionFailed :exec
UPDATE engagement_actions SET
  status = 'failed', result = $2, updated_at = now()
WHERE id = $1
`

type MarkEngagementActionFailedParams struct {
	ID     pgtype.UUID `json:"id"`
	Result []byte      `json:"result"`
}

func (q *Queries) MarkEngagementActionFailed(ctx context.Context, arg MarkEngagementActionFailedParams) error {
	_, err := q.db.Exec(ctx, markEngagementActionFailed, arg.ID, arg.Result)
	return err
}

const rejectEngagementAction = `-- name: RejectEngagementAction :exec
UPDATE engagement_actions SET status = 'rejected', updated_at = now() WHERE id = $1
`

func (q *Queries) RejectEngagementAction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectEngagementAction, id)
	return err
}

const updateEngagementAnalysis = `-- name: UpdateEngagementAnalysis :exec
UPDATE engagements SET analysis = $2, updated_at = now() WHERE id = $1
`

type UpdateEngagementAnalysisParams struct {
	ID       pgtype.UUID `json:"id"`
	Analysis []byte      `json:"analysis"`
}

func (q *Queries) UpdateEngagementAnalysis(ctx context.Context, arg UpdateEngagementAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateEngagementAnalysis, arg.ID, arg.Analysis)
	return err
}

const updateEngagementDiagnosis = `-- name: UpdateEngagementDiagnosis :exec
UPDATE engagements SET
  diagnosis_questions = $2, diagnosis_answers = $3, updated_at = now()
WHERE id = $1
`

type UpdateEngagementDiagnosisParams struct {
	ID                 pgtype.UUID `json:"id"`
	DiagnosisQuestions []byte      `json:"diagnosis_questions"`
	DiagnosisAnswers   []byte      `json:"diagnosis_answers"`
}

func (q *Queries) UpdateEngagementDiagnosis(ctx context.Context, arg UpdateEngagementDiagnosisParams) error {
	_, err := q.db.Exec(ctx, updateEngagementDiagnosis, arg.ID, arg.DiagnosisQuestions, arg.DiagnosisAnswers)
	return err
}

const updateEngagementPhase = `-- name: UpdateEngagementPhase :exec
UPDATE engagements SET phase = $2, updated_at = now() WHERE id = $1
`

type UpdateEngagementPhaseParams struct {
	ID    pgtype.UUID `json:"id"`
	Phase string      `json:"phase"`
}

func (q *Queries) UpdateEngagementPhase(ctx context.Context, arg UpdateEngagementPhaseParams) error {
	_, err := q.db.Exec(ctx, updateEngagementPhase, arg.ID, arg.Phase)
	return err
}

const updateEngagementPlan = `-- name: UpdateEngagementPlan :exec
UPDATE engagements SET plan = $2, updated_at = now() WHERE id = $1
`

type UpdateEngagementPlanParams struct {
	ID   pgtype.UUID `json:"id"`
	Plan []byte      `json:"plan"`
}

func (q *Queries) UpdateEngagementPlan(ctx context.Context, arg UpdateEngagementPlanParams) error {
	_, err := q.db.Exec(ctx, updateEngagementPlan, arg.ID, arg.Plan)
	return err
}

const updateEngagementProgress = `-- name: UpdateEngagementProgress :exec
UPDATE engagements SET
  progress_pct = $2, next_check_at = $3, updated_at = now()
WHERE id = $1
`

type UpdateEngagementProgressParams struct {
	ID          pgtype.UUID        `json:"id"`
	ProgressPct pgtype.Numeric     `json:"progress_pct"`
	NextCheckAt pgtype.Timestamptz `json:"next_check_at"`
}

func (q *Queries) UpdateEngagementProgress(ctx context.Context, arg UpdateEngagementProgressParams) error {
	_, err := q.db.Exec(ctx, updateEngagementProgress, arg.ID, arg.ProgressPct, arg.NextCheckAt)
	return err
}

const verifyEngagementTenant = `-- name: VerifyEngagementTenant :one
SELECT tenant_id FROM engagements WHERE id = $1
`

func (q *Queries) VerifyEngagementTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyEngagementTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
