// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_signals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecutionSignal = `-- name: CreateExecutionSignal :one
INSERT INTO execution_signals (tenant_id, subject_type, subject_id,
  signal_type, score, reasons, time_window)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at
`

type CreateExecutionSignalParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	SubjectType string         `json:"subject_type"`
	SubjectID   pgtype.UUID    `json:"subject_id"`
	SignalType  string         `json:"signal_type"`
	Score       pgtype.Numeric `json:"score"`
	Reasons     []byte         `json:"reasons"`
	TimeWindow  pgtype.Text    `json:"time_window"`
}

func (q *Queries) CreateExecutionSignal(ctx context.Context, arg CreateExecutionSignalParams) (ExecutionSignal, error) {
	row := q.db.QueryRow(ctx, createExecutionSignal,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.SignalType,
		arg.Score,
		arg.Reasons,
		arg.TimeWindow,
	)
	var i ExecutionSignal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.SignalType,
		&i.Score,
		&i.Reasons,
		&i.TimeWindow,
		&i.GeneratedAt,
	)
	return i, err
}

const deleteOldSignals = `-- name: DeleteOldSignals :exec
DELETE FROM execution_signals
WHERE tenant_id = $1 AND generated_at < $2
`

type DeleteOldSignalsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

func (q *Queries) DeleteOldSignals(ctx context.Context, arg DeleteOldSignalsParams) error {
	_, err := q.db.Exec(ctx, deleteOldSignals, arg.TenantID, arg.GeneratedAt)
	return err
}

const getSignalsBySubject = `-- name: GetSignalsBySubject :many
SELECT id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at FROM execution_signals
WHERE subject_type = $1 AND subject_id = $2
ORDER BY generated_at DESC
LIMIT $3
`

type GetSignalsBySubjectParams struct {
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) GetSignalsBySubject(ctx context.Context, arg GetSignalsBySubjectParams) ([]ExecutionSignal, error) {
	rows, err := q.db.Query(ctx, getSignalsBySubject, arg.SubjectType, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionSignal{}
	for rows.Next() {
		var i ExecutionSignal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SignalType,
			&i.Score,
			&i.Reasons,
			&i.TimeWindow,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopRisks = `-- name: GetTopRisks :many
SELECT id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at FROM execution_signals
WHERE tenant_id = $1
  AND signal_type IN ('slow_response', 'missed_deadline', 'overloaded', 'blocker_risk', 'declining')
  AND generated_at >= $2
ORDER BY score DESC
LIMIT $3
`

type GetTopRisksParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetTopRisks(ctx context.Context, arg GetTopRisksParams) ([]ExecutionSignal, error) {
	rows, err := q.db.Query(ctx, getTopRisks, arg.TenantID, arg.GeneratedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionSignal{}
	for rows.Next() {
		var i ExecutionSignal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SignalType,
			&i.Score,
			&i.Reasons,
			&i.TimeWindow,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionSignals = `-- name: ListExecutionSignals :many
SELECT id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at FROM execution_signals
WHERE tenant_id = $1
  AND generated_at >= $2
ORDER BY score DESC, generated_at DESC
LIMIT $3
`

type ListExecutionSignalsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListExecutionSignals(ctx context.Context, arg ListExecutionSignalsParams) ([]ExecutionSignal, error) {
	rows, err := q.db.Query(ctx, listExecutionSignals, arg.TenantID, arg.GeneratedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionSignal{}
	for rows.Next() {
		var i ExecutionSignal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SignalType,
			&i.Score,
			&i.Reasons,
			&i.TimeWindow,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignalsByType = `-- name: ListSignalsByType :many
SELECT id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at FROM execution_signals
WHERE tenant_id = $1
  AND subject_type = $2
  AND generated_at >= $3
ORDER BY score DESC
LIMIT $4
`

type ListSignalsByTypeParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SubjectType string             `json:"subject_type"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListSignalsByType(ctx context.Context, arg ListSignalsByTypeParams) ([]ExecutionSignal, error) {
	rows, err := q.db.Query(ctx, listSignalsByType,
		arg.TenantID,
		arg.SubjectType,
		arg.GeneratedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionSignal{}
	for rows.Next() {
		var i ExecutionSignal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.SignalType,
			&i.Score,
			&i.Reasons,
			&i.TimeWindow,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
