// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (tenant_id, owner_id, title, description, status, cycle)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, owner_id, title, description, status, cycle, created_at, updated_at, level, goal_type, source_system, source_ref
`

type CreateGoalParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
	Cycle       string      `json:"cycle"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.TenantID,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Cycle,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Cycle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Level,
		&i.GoalType,
		&i.SourceSystem,
		&i.SourceRef,
	)
	return i, err
}

const createGoalSnapshot = `-- name: CreateGoalSnapshot :exec
INSERT INTO goal_snapshots (goal_id, overall_progress, snapshot_date)
VALUES ($1, $2, $3)
ON CONFLICT (goal_id, snapshot_date) DO UPDATE SET overall_progress = EXCLUDED.overall_progress
`

type CreateGoalSnapshotParams struct {
	GoalID          pgtype.UUID    `json:"goal_id"`
	OverallProgress pgtype.Numeric `json:"overall_progress"`
	SnapshotDate    pgtype.Date    `json:"snapshot_date"`
}

func (q *Queries) CreateGoalSnapshot(ctx context.Context, arg CreateGoalSnapshotParams) error {
	_, err := q.db.Exec(ctx, createGoalSnapshot, arg.GoalID, arg.OverallProgress, arg.SnapshotDate)
	return err
}

const createKeyResult = `-- name: CreateKeyResult :one
INSERT INTO key_results (goal_id, title, target, current_value, unit, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, goal_id, title, target, current_value, unit, due_date, created_at, updated_at, metric_id, baseline_value, formula_note, status, owner_id
`

type CreateKeyResultParams struct {
	GoalID       pgtype.UUID    `json:"goal_id"`
	Title        string         `json:"title"`
	Target       pgtype.Numeric `json:"target"`
	CurrentValue pgtype.Numeric `json:"current_value"`
	Unit         string         `json:"unit"`
	DueDate      pgtype.Date    `json:"due_date"`
}

func (q *Queries) CreateKeyResult(ctx context.Context, arg CreateKeyResultParams) (KeyResult, error) {
	row := q.db.QueryRow(ctx, createKeyResult,
		arg.GoalID,
		arg.Title,
		arg.Target,
		arg.CurrentValue,
		arg.Unit,
		arg.DueDate,
	)
	var i KeyResult
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Title,
		&i.Target,
		&i.CurrentValue,
		&i.Unit,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MetricID,
		&i.BaselineValue,
		&i.FormulaNote,
		&i.Status,
		&i.OwnerID,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1 AND tenant_id = $2
`

type DeleteGoalParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.TenantID)
	return err
}

const deleteKeyResult = `-- name: DeleteKeyResult :exec
DELETE FROM key_results WHERE id = $1
`

func (q *Queries) DeleteKeyResult(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKeyResult, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, tenant_id, owner_id, title, description, status, cycle, created_at, updated_at, level, goal_type, source_system, source_ref FROM goals WHERE id = $1 AND tenant_id = $2
`

type GetGoalParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.TenantID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Cycle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Level,
		&i.GoalType,
		&i.SourceSystem,
		&i.SourceRef,
	)
	return i, err
}

const getKeyResultsByGoal = `-- name: GetKeyResultsByGoal :many
SELECT id, goal_id, title, target, current_value, unit, due_date, created_at, updated_at, metric_id, baseline_value, formula_note, status, owner_id FROM key_results WHERE goal_id = $1 ORDER BY created_at
`

func (q *Queries) GetKeyResultsByGoal(ctx context.Context, goalID pgtype.UUID) ([]KeyResult, error) {
	rows, err := q.db.Query(ctx, getKeyResultsByGoal, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyResult{}
	for rows.Next() {
		var i KeyResult
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Title,
			&i.Target,
			&i.CurrentValue,
			&i.Unit,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MetricID,
			&i.BaselineValue,
			&i.FormulaNote,
			&i.Status,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGoalsByTenant = `-- name: ListActiveGoalsByTenant :many
SELECT g.id, g.title
FROM goals g
WHERE g.tenant_id = $1 AND g.status = 'active'
`

type ListActiveGoalsByTenantRow struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) ListActiveGoalsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveGoalsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveGoalsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGoalsByTenantRow{}
	for rows.Next() {
		var i ListActiveGoalsByTenantRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalSnapshots = `-- name: ListGoalSnapshots :many
SELECT id, goal_id, overall_progress, snapshot_date, created_at FROM goal_snapshots
WHERE goal_id = $1
ORDER BY snapshot_date
`

func (q *Queries) ListGoalSnapshots(ctx context.Context, goalID pgtype.UUID) ([]GoalSnapshot, error) {
	rows, err := q.db.Query(ctx, listGoalSnapshots, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalSnapshot{}
	for rows.Next() {
		var i GoalSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.OverallProgress,
			&i.SnapshotDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByCycle = `-- name: ListGoalsByCycle :many
SELECT g.id, g.tenant_id, g.owner_id, g.title, g.description, g.status, g.cycle, g.created_at, g.updated_at, g.level, g.goal_type, g.source_system, g.source_ref,
       COALESCE(
         (SELECT json_agg(kr ORDER BY kr.created_at)
          FROM key_results kr WHERE kr.goal_id = g.id),
         '[]'
       ) AS key_results_json
FROM goals g
WHERE g.tenant_id = $1 AND g.cycle = $2
ORDER BY g.created_at
`

type ListGoalsByCycleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Cycle    string      `json:"cycle"`
}

type ListGoalsByCycleRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	Cycle          string             `json:"cycle"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Level          string             `json:"level"`
	GoalType       string             `json:"goal_type"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	KeyResultsJson interface{}        `json:"key_results_json"`
}

func (q *Queries) ListGoalsByCycle(ctx context.Context, arg ListGoalsByCycleParams) ([]ListGoalsByCycleRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByCycle, arg.TenantID, arg.Cycle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsByCycleRow{}
	for rows.Next() {
		var i ListGoalsByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Cycle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Level,
			&i.GoalType,
			&i.SourceSystem,
			&i.SourceRef,
			&i.KeyResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsWithActiveGoals = `-- name: ListTenantsWithActiveGoals :many
SELECT DISTINCT g.tenant_id
FROM goals g
WHERE g.status = 'active'
`

func (q *Queries) ListTenantsWithActiveGoals(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantsWithActiveGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = $3, description = $4, status = $5, cycle = $6, owner_id = $7, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, owner_id, title, description, status, cycle, created_at, updated_at, level, goal_type, source_system, source_ref
`

type UpdateGoalParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
	Cycle       string      `json:"cycle"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Cycle,
		arg.OwnerID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Cycle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Level,
		&i.GoalType,
		&i.SourceSystem,
		&i.SourceRef,
	)
	return i, err
}

const updateKeyResult = `-- name: UpdateKeyResult :exec
UPDATE key_results
SET title = $2, target = $3, current_value = $4, unit = $5, due_date = $6, updated_at = now()
WHERE id = $1
`

type UpdateKeyResultParams struct {
	ID           pgtype.UUID    `json:"id"`
	Title        string         `json:"title"`
	Target       pgtype.Numeric `json:"target"`
	CurrentValue pgtype.Numeric `json:"current_value"`
	Unit         string         `json:"unit"`
	DueDate      pgtype.Date    `json:"due_date"`
}

func (q *Queries) UpdateKeyResult(ctx context.Context, arg UpdateKeyResultParams) error {
	_, err := q.db.Exec(ctx, updateKeyResult,
		arg.ID,
		arg.Title,
		arg.Target,
		arg.CurrentValue,
		arg.Unit,
		arg.DueDate,
	)
	return err
}
