// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_chats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupChat = `-- name: CreateGroupChat :one
INSERT INTO group_chats (tenant_id, platform, platform_chat_id, name, group_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at
`

type CreateGroupChatParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Platform       string      `json:"platform"`
	PlatformChatID string      `json:"platform_chat_id"`
	Name           string      `json:"name"`
	GroupType      string      `json:"group_type"`
}

func (q *Queries) CreateGroupChat(ctx context.Context, arg CreateGroupChatParams) (GroupChat, error) {
	row := q.db.QueryRow(ctx, createGroupChat,
		arg.TenantID,
		arg.Platform,
		arg.PlatformChatID,
		arg.Name,
		arg.GroupType,
	)
	var i GroupChat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.PlatformChatID,
		&i.Name,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupChatByID = `-- name: GetGroupChatByID :one
SELECT id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at FROM group_chats
WHERE id = $1
`

func (q *Queries) GetGroupChatByID(ctx context.Context, id pgtype.UUID) (GroupChat, error) {
	row := q.db.QueryRow(ctx, getGroupChatByID, id)
	var i GroupChat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.PlatformChatID,
		&i.Name,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupChatByPlatformID = `-- name: GetGroupChatByPlatformID :one
SELECT id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at FROM group_chats
WHERE platform = $1 AND platform_chat_id = $2
`

type GetGroupChatByPlatformIDParams struct {
	Platform       string `json:"platform"`
	PlatformChatID string `json:"platform_chat_id"`
}

func (q *Queries) GetGroupChatByPlatformID(ctx context.Context, arg GetGroupChatByPlatformIDParams) (GroupChat, error) {
	row := q.db.QueryRow(ctx, getGroupChatByPlatformID, arg.Platform, arg.PlatformChatID)
	var i GroupChat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.PlatformChatID,
		&i.Name,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGroupChatsByTenant = `-- name: ListActiveGroupChatsByTenant :many
SELECT id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at FROM group_chats
WHERE tenant_id = $1 AND is_active = true
ORDER BY created_at
`

func (q *Queries) ListActiveGroupChatsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]GroupChat, error) {
	rows, err := q.db.Query(ctx, listActiveGroupChatsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupChat{}
	for rows.Next() {
		var i GroupChat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Platform,
			&i.PlatformChatID,
			&i.Name,
			&i.GroupType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupChatsByTenant = `-- name: ListGroupChatsByTenant :many
SELECT id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at FROM group_chats
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListGroupChatsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]GroupChat, error) {
	rows, err := q.db.Query(ctx, listGroupChatsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupChat{}
	for rows.Next() {
		var i GroupChat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Platform,
			&i.PlatformChatID,
			&i.Name,
			&i.GroupType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGroupChat = `-- name: SoftDeleteGroupChat :exec
UPDATE group_chats
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteGroupChat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteGroupChat, id)
	return err
}

const updateGroupChat = `-- name: UpdateGroupChat :one
UPDATE group_chats
SET name = $2, group_type = $3, is_active = $4, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, platform, platform_chat_id, name, group_type, is_active, created_at, updated_at
`

type UpdateGroupChatParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	GroupType string      `json:"group_type"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateGroupChat(ctx context.Context, arg UpdateGroupChatParams) (GroupChat, error) {
	row := q.db.QueryRow(ctx, updateGroupChat,
		arg.ID,
		arg.Name,
		arg.GroupType,
		arg.IsActive,
	)
	var i GroupChat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Platform,
		&i.PlatformChatID,
		&i.Name,
		&i.GroupType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
