// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: halaos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHRSignalsByType = `-- name: CountHRSignalsByType :many
SELECT signal_type, COUNT(*) AS count
FROM execution_signals
WHERE tenant_id = $1
  AND signal_type IN ('flight_risk', 'burnout_risk', 'team_health', 'org_health')
  AND generated_at >= $2
GROUP BY signal_type
`

type CountHRSignalsByTypeParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

type CountHRSignalsByTypeRow struct {
	SignalType string `json:"signal_type"`
	Count      int64  `json:"count"`
}

func (q *Queries) CountHRSignalsByType(ctx context.Context, arg CountHRSignalsByTypeParams) ([]CountHRSignalsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countHRSignalsByType, arg.TenantID, arg.GeneratedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHRSignalsByTypeRow{}
	for rows.Next() {
		var i CountHRSignalsByTypeRow
		if err := rows.Scan(&i.SignalType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countHighRiskSignals = `-- name: CountHighRiskSignals :one
SELECT COUNT(*) FROM execution_signals
WHERE tenant_id = $1
  AND signal_type = $2
  AND score >= $3::numeric
  AND generated_at >= $4
`

type CountHighRiskSignalsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SignalType  string             `json:"signal_type"`
	Column3     pgtype.Numeric     `json:"column_3"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

func (q *Queries) CountHighRiskSignals(ctx context.Context, arg CountHighRiskSignalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHighRiskSignals,
		arg.TenantID,
		arg.SignalType,
		arg.Column3,
		arg.GeneratedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentCommunicationEvents = `-- name: CountRecentCommunicationEvents :one
SELECT COUNT(*) FROM communication_events
WHERE tenant_id = $1
  AND source_type = 'halaos'
  AND event_type = $2
  AND occurred_at >= $3
`

type CountRecentCommunicationEventsParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EventType  string             `json:"event_type"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CountRecentCommunicationEvents(ctx context.Context, arg CountRecentCommunicationEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCommunicationEvents, arg.TenantID, arg.EventType, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployeeFromHalaOS = `-- name: CreateEmployeeFromHalaOS :one
INSERT INTO employees (tenant_id, name, role, halaos_employee_id, halaos_employee_no)
VALUES ($1, $2, 'member', $3, $4)
RETURNING id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel, job_title, responsibilities, country, language, org_unit_id, execution_score, current_load, strengths, risk_flags, work_scope, halaos_employee_id, halaos_employee_no
`

type CreateEmployeeFromHalaOSParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Name             string      `json:"name"`
	HalaosEmployeeID pgtype.Int8 `json:"halaos_employee_id"`
	HalaosEmployeeNo pgtype.Text `json:"halaos_employee_no"`
}

func (q *Queries) CreateEmployeeFromHalaOS(ctx context.Context, arg CreateEmployeeFromHalaOSParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployeeFromHalaOS,
		arg.TenantID,
		arg.Name,
		arg.HalaosEmployeeID,
		arg.HalaosEmployeeNo,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
		&i.JobTitle,
		&i.Responsibilities,
		&i.Country,
		&i.Language,
		&i.OrgUnitID,
		&i.ExecutionScore,
		&i.CurrentLoad,
		&i.Strengths,
		&i.RiskFlags,
		&i.WorkScope,
		&i.HalaosEmployeeID,
		&i.HalaosEmployeeNo,
	)
	return i, err
}

const createHalaOSEvent = `-- name: CreateHalaOSEvent :one
INSERT INTO halaos_events (tenant_id, event_type, idempotency_key, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, event_type, idempotency_key, payload, processed_at
`

type CreateHalaOSEventParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	EventType      string      `json:"event_type"`
	IdempotencyKey string      `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
}

func (q *Queries) CreateHalaOSEvent(ctx context.Context, arg CreateHalaOSEventParams) (HalaosEvent, error) {
	row := q.db.QueryRow(ctx, createHalaOSEvent,
		arg.TenantID,
		arg.EventType,
		arg.IdempotencyKey,
		arg.Payload,
	)
	var i HalaosEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.IdempotencyKey,
		&i.Payload,
		&i.ProcessedAt,
	)
	return i, err
}

const createHalaOSLink = `-- name: CreateHalaOSLink :one
INSERT INTO halaos_links (tenant_id, webhook_secret, halaos_company_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, webhook_secret, halaos_company_id, is_active, created_at
`

type CreateHalaOSLinkParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	WebhookSecret   string      `json:"webhook_secret"`
	HalaosCompanyID int64       `json:"halaos_company_id"`
}

func (q *Queries) CreateHalaOSLink(ctx context.Context, arg CreateHalaOSLinkParams) (HalaosLink, error) {
	row := q.db.QueryRow(ctx, createHalaOSLink, arg.TenantID, arg.WebhookSecret, arg.HalaosCompanyID)
	var i HalaosLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WebhookSecret,
		&i.HalaosCompanyID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHalaOSLink = `-- name: DeleteHalaOSLink :exec
DELETE FROM halaos_links WHERE id = $1 AND tenant_id = $2
`

type DeleteHalaOSLinkParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteHalaOSLink(ctx context.Context, arg DeleteHalaOSLinkParams) error {
	_, err := q.db.Exec(ctx, deleteHalaOSLink, arg.ID, arg.TenantID)
	return err
}

const getEmployeeByHalaOSID = `-- name: GetEmployeeByHalaOSID :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel, job_title, responsibilities, country, language, org_unit_id, execution_score, current_load, strengths, risk_flags, work_scope, halaos_employee_id, halaos_employee_no FROM employees
WHERE tenant_id = $1 AND halaos_employee_id = $2
LIMIT 1
`

type GetEmployeeByHalaOSIDParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	HalaosEmployeeID pgtype.Int8 `json:"halaos_employee_id"`
}

func (q *Queries) GetEmployeeByHalaOSID(ctx context.Context, arg GetEmployeeByHalaOSIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByHalaOSID, arg.TenantID, arg.HalaosEmployeeID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
		&i.JobTitle,
		&i.Responsibilities,
		&i.Country,
		&i.Language,
		&i.OrgUnitID,
		&i.ExecutionScore,
		&i.CurrentLoad,
		&i.Strengths,
		&i.RiskFlags,
		&i.WorkScope,
		&i.HalaosEmployeeID,
		&i.HalaosEmployeeNo,
	)
	return i, err
}

const getEmployeeByHalaOSNo = `-- name: GetEmployeeByHalaOSNo :one
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel, job_title, responsibilities, country, language, org_unit_id, execution_score, current_load, strengths, risk_flags, work_scope, halaos_employee_id, halaos_employee_no FROM employees
WHERE tenant_id = $1 AND halaos_employee_no = $2
LIMIT 1
`

type GetEmployeeByHalaOSNoParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	HalaosEmployeeNo pgtype.Text `json:"halaos_employee_no"`
}

func (q *Queries) GetEmployeeByHalaOSNo(ctx context.Context, arg GetEmployeeByHalaOSNoParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByHalaOSNo, arg.TenantID, arg.HalaosEmployeeNo)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
		&i.JobTitle,
		&i.Responsibilities,
		&i.Country,
		&i.Language,
		&i.OrgUnitID,
		&i.ExecutionScore,
		&i.CurrentLoad,
		&i.Strengths,
		&i.RiskFlags,
		&i.WorkScope,
		&i.HalaosEmployeeID,
		&i.HalaosEmployeeNo,
	)
	return i, err
}

const getHalaOSEventByKey = `-- name: GetHalaOSEventByKey :one
SELECT id FROM halaos_events
WHERE tenant_id = $1 AND idempotency_key = $2
LIMIT 1
`

type GetHalaOSEventByKeyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetHalaOSEventByKey(ctx context.Context, arg GetHalaOSEventByKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getHalaOSEventByKey, arg.TenantID, arg.IdempotencyKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getHalaOSLinkByCompanyID = `-- name: GetHalaOSLinkByCompanyID :one
SELECT id, tenant_id, webhook_secret, halaos_company_id, is_active, created_at FROM halaos_links
WHERE halaos_company_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetHalaOSLinkByCompanyID(ctx context.Context, halaosCompanyID int64) (HalaosLink, error) {
	row := q.db.QueryRow(ctx, getHalaOSLinkByCompanyID, halaosCompanyID)
	var i HalaosLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WebhookSecret,
		&i.HalaosCompanyID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getHalaOSLinkByTenant = `-- name: GetHalaOSLinkByTenant :one
SELECT id, tenant_id, webhook_secret, halaos_company_id, is_active, created_at FROM halaos_links
WHERE tenant_id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetHalaOSLinkByTenant(ctx context.Context, tenantID pgtype.UUID) (HalaosLink, error) {
	row := q.db.QueryRow(ctx, getHalaOSLinkByTenant, tenantID)
	var i HalaosLink
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WebhookSecret,
		&i.HalaosCompanyID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOrgHealthSignal = `-- name: GetLatestOrgHealthSignal :one
SELECT id, tenant_id, subject_type, subject_id, signal_type, score, reasons, time_window, generated_at FROM execution_signals
WHERE tenant_id = $1
  AND signal_type = 'org_health'
  AND subject_type = 'organization'
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOrgHealthSignal(ctx context.Context, tenantID pgtype.UUID) (ExecutionSignal, error) {
	row := q.db.QueryRow(ctx, getLatestOrgHealthSignal, tenantID)
	var i ExecutionSignal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.SignalType,
		&i.Score,
		&i.Reasons,
		&i.TimeWindow,
		&i.GeneratedAt,
	)
	return i, err
}

const updateEmployeeHalaOSLink = `-- name: UpdateEmployeeHalaOSLink :exec
UPDATE employees
SET halaos_employee_id = $2, halaos_employee_no = $3
WHERE id = $1
`

type UpdateEmployeeHalaOSLinkParams struct {
	ID               pgtype.UUID `json:"id"`
	HalaosEmployeeID pgtype.Int8 `json:"halaos_employee_id"`
	HalaosEmployeeNo pgtype.Text `json:"halaos_employee_no"`
}

func (q *Queries) UpdateEmployeeHalaOSLink(ctx context.Context, arg UpdateEmployeeHalaOSLinkParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeHalaOSLink, arg.ID, arg.HalaosEmployeeID, arg.HalaosEmployeeNo)
	return err
}
