// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incentive_rules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncentiveRule = `-- name: CreateIncentiveRule :one
INSERT INTO incentive_rules (tenant_id, name, reward_model, payout_cycle,
  attribution_rules, penalty_rules, scoring_formula, applies_to)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, reward_model, payout_cycle, attribution_rules, penalty_rules, scoring_formula, applies_to, is_active, created_at, updated_at
`

type CreateIncentiveRuleParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Name             string      `json:"name"`
	RewardModel      string      `json:"reward_model"`
	PayoutCycle      string      `json:"payout_cycle"`
	AttributionRules []byte      `json:"attribution_rules"`
	PenaltyRules     []byte      `json:"penalty_rules"`
	ScoringFormula   []byte      `json:"scoring_formula"`
	AppliesTo        []byte      `json:"applies_to"`
}

func (q *Queries) CreateIncentiveRule(ctx context.Context, arg CreateIncentiveRuleParams) (IncentiveRule, error) {
	row := q.db.QueryRow(ctx, createIncentiveRule,
		arg.TenantID,
		arg.Name,
		arg.RewardModel,
		arg.PayoutCycle,
		arg.AttributionRules,
		arg.PenaltyRules,
		arg.ScoringFormula,
		arg.AppliesTo,
	)
	var i IncentiveRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RewardModel,
		&i.PayoutCycle,
		&i.AttributionRules,
		&i.PenaltyRules,
		&i.ScoringFormula,
		&i.AppliesTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIncentiveScore = `-- name: CreateIncentiveScore :one
INSERT INTO incentive_scores (tenant_id, rule_id, person_id, period,
  score, score_breakdown, payout_weight, attribution_confidence, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (rule_id, person_id, period)
DO UPDATE SET
  score = EXCLUDED.score,
  score_breakdown = EXCLUDED.score_breakdown,
  payout_weight = EXCLUDED.payout_weight,
  attribution_confidence = EXCLUDED.attribution_confidence,
  calculated_at = now()
RETURNING id, tenant_id, rule_id, person_id, period, score, score_breakdown, payout_weight, attribution_confidence, status, calculated_at, reviewed_at
`

type CreateIncentiveScoreParams struct {
	TenantID              pgtype.UUID    `json:"tenant_id"`
	RuleID                pgtype.UUID    `json:"rule_id"`
	PersonID              pgtype.UUID    `json:"person_id"`
	Period                string         `json:"period"`
	Score                 pgtype.Numeric `json:"score"`
	ScoreBreakdown        []byte         `json:"score_breakdown"`
	PayoutWeight          pgtype.Numeric `json:"payout_weight"`
	AttributionConfidence pgtype.Numeric `json:"attribution_confidence"`
	Status                string         `json:"status"`
}

func (q *Queries) CreateIncentiveScore(ctx context.Context, arg CreateIncentiveScoreParams) (IncentiveScore, error) {
	row := q.db.QueryRow(ctx, createIncentiveScore,
		arg.TenantID,
		arg.RuleID,
		arg.PersonID,
		arg.Period,
		arg.Score,
		arg.ScoreBreakdown,
		arg.PayoutWeight,
		arg.AttributionConfidence,
		arg.Status,
	)
	var i IncentiveScore
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RuleID,
		&i.PersonID,
		&i.Period,
		&i.Score,
		&i.ScoreBreakdown,
		&i.PayoutWeight,
		&i.AttributionConfidence,
		&i.Status,
		&i.CalculatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const deleteIncentiveRule = `-- name: DeleteIncentiveRule :exec
UPDATE incentive_rules SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeleteIncentiveRule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncentiveRule, id)
	return err
}

const getIncentiveRule = `-- name: GetIncentiveRule :one
SELECT id, tenant_id, name, reward_model, payout_cycle, attribution_rules, penalty_rules, scoring_formula, applies_to, is_active, created_at, updated_at FROM incentive_rules WHERE id = $1
`

func (q *Queries) GetIncentiveRule(ctx context.Context, id pgtype.UUID) (IncentiveRule, error) {
	row := q.db.QueryRow(ctx, getIncentiveRule, id)
	var i IncentiveRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RewardModel,
		&i.PayoutCycle,
		&i.AttributionRules,
		&i.PenaltyRules,
		&i.ScoringFormula,
		&i.AppliesTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncentiveScoresByPerson = `-- name: GetIncentiveScoresByPerson :many
SELECT ics.id, ics.tenant_id, ics.rule_id, ics.person_id, ics.period, ics.score, ics.score_breakdown, ics.payout_weight, ics.attribution_confidence, ics.status, ics.calculated_at, ics.reviewed_at, ir.name AS rule_name
FROM incentive_scores ics
JOIN incentive_rules ir ON ics.rule_id = ir.id
WHERE ics.person_id = $1
ORDER BY ics.period DESC, ir.name
`

type GetIncentiveScoresByPersonRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	RuleID                pgtype.UUID        `json:"rule_id"`
	PersonID              pgtype.UUID        `json:"person_id"`
	Period                string             `json:"period"`
	Score                 pgtype.Numeric     `json:"score"`
	ScoreBreakdown        []byte             `json:"score_breakdown"`
	PayoutWeight          pgtype.Numeric     `json:"payout_weight"`
	AttributionConfidence pgtype.Numeric     `json:"attribution_confidence"`
	Status                string             `json:"status"`
	CalculatedAt          pgtype.Timestamptz `json:"calculated_at"`
	ReviewedAt            pgtype.Timestamptz `json:"reviewed_at"`
	RuleName              string             `json:"rule_name"`
}

func (q *Queries) GetIncentiveScoresByPerson(ctx context.Context, personID pgtype.UUID) ([]GetIncentiveScoresByPersonRow, error) {
	rows, err := q.db.Query(ctx, getIncentiveScoresByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncentiveScoresByPersonRow{}
	for rows.Next() {
		var i GetIncentiveScoresByPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuleID,
			&i.PersonID,
			&i.Period,
			&i.Score,
			&i.ScoreBreakdown,
			&i.PayoutWeight,
			&i.AttributionConfidence,
			&i.Status,
			&i.CalculatedAt,
			&i.ReviewedAt,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncentiveRules = `-- name: ListIncentiveRules :many
SELECT id, tenant_id, name, reward_model, payout_cycle, attribution_rules, penalty_rules, scoring_formula, applies_to, is_active, created_at, updated_at FROM incentive_rules
WHERE tenant_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListIncentiveRules(ctx context.Context, tenantID pgtype.UUID) ([]IncentiveRule, error) {
	rows, err := q.db.Query(ctx, listIncentiveRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncentiveRule{}
	for rows.Next() {
		var i IncentiveRule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.RewardModel,
			&i.PayoutCycle,
			&i.AttributionRules,
			&i.PenaltyRules,
			&i.ScoringFormula,
			&i.AppliesTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncentiveScores = `-- name: ListIncentiveScores :many
SELECT ics.id, ics.tenant_id, ics.rule_id, ics.person_id, ics.period, ics.score, ics.score_breakdown, ics.payout_weight, ics.attribution_confidence, ics.status, ics.calculated_at, ics.reviewed_at, e.name AS person_name, ir.name AS rule_name
FROM incentive_scores ics
JOIN employees e ON ics.person_id = e.id
JOIN incentive_rules ir ON ics.rule_id = ir.id
WHERE ics.tenant_id = $1 AND ics.period = $2
ORDER BY ics.score DESC
`

type ListIncentiveScoresParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Period   string      `json:"period"`
}

type ListIncentiveScoresRow struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	RuleID                pgtype.UUID        `json:"rule_id"`
	PersonID              pgtype.UUID        `json:"person_id"`
	Period                string             `json:"period"`
	Score                 pgtype.Numeric     `json:"score"`
	ScoreBreakdown        []byte             `json:"score_breakdown"`
	PayoutWeight          pgtype.Numeric     `json:"payout_weight"`
	AttributionConfidence pgtype.Numeric     `json:"attribution_confidence"`
	Status                string             `json:"status"`
	CalculatedAt          pgtype.Timestamptz `json:"calculated_at"`
	ReviewedAt            pgtype.Timestamptz `json:"reviewed_at"`
	PersonName            string             `json:"person_name"`
	RuleName              string             `json:"rule_name"`
}

func (q *Queries) ListIncentiveScores(ctx context.Context, arg ListIncentiveScoresParams) ([]ListIncentiveScoresRow, error) {
	rows, err := q.db.Query(ctx, listIncentiveScores, arg.TenantID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncentiveScoresRow{}
	for rows.Next() {
		var i ListIncentiveScoresRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RuleID,
			&i.PersonID,
			&i.Period,
			&i.Score,
			&i.ScoreBreakdown,
			&i.PayoutWeight,
			&i.AttributionConfidence,
			&i.Status,
			&i.CalculatedAt,
			&i.ReviewedAt,
			&i.PersonName,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncentiveRule = `-- name: UpdateIncentiveRule :one
UPDATE incentive_rules SET
  name = $2, reward_model = $3, payout_cycle = $4,
  attribution_rules = $5, scoring_formula = $6,
  applies_to = $7, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, reward_model, payout_cycle, attribution_rules, penalty_rules, scoring_formula, applies_to, is_active, created_at, updated_at
`

type UpdateIncentiveRuleParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	RewardModel      string      `json:"reward_model"`
	PayoutCycle      string      `json:"payout_cycle"`
	AttributionRules []byte      `json:"attribution_rules"`
	ScoringFormula   []byte      `json:"scoring_formula"`
	AppliesTo        []byte      `json:"applies_to"`
}

func (q *Queries) UpdateIncentiveRule(ctx context.Context, arg UpdateIncentiveRuleParams) (IncentiveRule, error) {
	row := q.db.QueryRow(ctx, updateIncentiveRule,
		arg.ID,
		arg.Name,
		arg.RewardModel,
		arg.PayoutCycle,
		arg.AttributionRules,
		arg.ScoringFormula,
		arg.AppliesTo,
	)
	var i IncentiveRule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RewardModel,
		&i.PayoutCycle,
		&i.AttributionRules,
		&i.PenaltyRules,
		&i.ScoringFormula,
		&i.AppliesTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyIncentiveRuleTenant = `-- name: VerifyIncentiveRuleTenant :one
SELECT tenant_id FROM incentive_rules WHERE id = $1
`

func (q *Queries) VerifyIncentiveRuleTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyIncentiveRuleTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
