// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meetings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActionItem = `-- name: CreateActionItem :one
INSERT INTO meeting_action_items (meeting_id, title, assignee_id, due_date)
VALUES ($1, $2, $3, $4)
RETURNING id, meeting_id, title, assignee_id, status, due_date, created_at, updated_at
`

type CreateActionItemParams struct {
	MeetingID  pgtype.UUID `json:"meeting_id"`
	Title      string      `json:"title"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	DueDate    pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateActionItem(ctx context.Context, arg CreateActionItemParams) (MeetingActionItem, error) {
	row := q.db.QueryRow(ctx, createActionItem,
		arg.MeetingID,
		arg.Title,
		arg.AssigneeID,
		arg.DueDate,
	)
	var i MeetingActionItem
	err := row.Scan(
		&i.ID,
		&i.MeetingID,
		&i.Title,
		&i.AssigneeID,
		&i.Status,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeeting = `-- name: CreateMeeting :one
INSERT INTO meetings (tenant_id, employee_id, manager_id, meeting_date, duration_min, notes, mood, follow_up)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, employee_id, manager_id, meeting_date, duration_min, notes, mood, follow_up, created_at, updated_at
`

type CreateMeetingParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EmployeeID  pgtype.UUID `json:"employee_id"`
	ManagerID   pgtype.UUID `json:"manager_id"`
	MeetingDate pgtype.Date `json:"meeting_date"`
	DurationMin int16       `json:"duration_min"`
	Notes       string      `json:"notes"`
	Mood        string      `json:"mood"`
	FollowUp    string      `json:"follow_up"`
}

func (q *Queries) CreateMeeting(ctx context.Context, arg CreateMeetingParams) (Meeting, error) {
	row := q.db.QueryRow(ctx, createMeeting,
		arg.TenantID,
		arg.EmployeeID,
		arg.ManagerID,
		arg.MeetingDate,
		arg.DurationMin,
		arg.Notes,
		arg.Mood,
		arg.FollowUp,
	)
	var i Meeting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ManagerID,
		&i.MeetingDate,
		&i.DurationMin,
		&i.Notes,
		&i.Mood,
		&i.FollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActionItem = `-- name: DeleteActionItem :exec
DELETE FROM meeting_action_items WHERE id = $1
`

func (q *Queries) DeleteActionItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActionItem, id)
	return err
}

const deleteMeeting = `-- name: DeleteMeeting :exec
DELETE FROM meetings WHERE id = $1 AND tenant_id = $2
`

type DeleteMeetingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMeeting(ctx context.Context, arg DeleteMeetingParams) error {
	_, err := q.db.Exec(ctx, deleteMeeting, arg.ID, arg.TenantID)
	return err
}

const getMeeting = `-- name: GetMeeting :one
SELECT m.id, m.tenant_id, m.employee_id, m.manager_id, m.meeting_date, m.duration_min, m.notes, m.mood, m.follow_up, m.created_at, m.updated_at, e.name AS employee_name
FROM meetings m
JOIN employees e ON e.id = m.employee_id
WHERE m.id = $1 AND m.tenant_id = $2
`

type GetMeetingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetMeetingRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	ManagerID    pgtype.UUID        `json:"manager_id"`
	MeetingDate  pgtype.Date        `json:"meeting_date"`
	DurationMin  int16              `json:"duration_min"`
	Notes        string             `json:"notes"`
	Mood         string             `json:"mood"`
	FollowUp     string             `json:"follow_up"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) GetMeeting(ctx context.Context, arg GetMeetingParams) (GetMeetingRow, error) {
	row := q.db.QueryRow(ctx, getMeeting, arg.ID, arg.TenantID)
	var i GetMeetingRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ManagerID,
		&i.MeetingDate,
		&i.DurationMin,
		&i.Notes,
		&i.Mood,
		&i.FollowUp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
	)
	return i, err
}

const listActionItems = `-- name: ListActionItems :many
SELECT ai.id, ai.meeting_id, ai.title, ai.assignee_id, ai.status, ai.due_date, ai.created_at, ai.updated_at, e.name AS assignee_name
FROM meeting_action_items ai
LEFT JOIN employees e ON e.id = ai.assignee_id
WHERE ai.meeting_id = $1
ORDER BY ai.created_at
`

type ListActionItemsRow struct {
	ID           pgtype.UUID        `json:"id"`
	MeetingID    pgtype.UUID        `json:"meeting_id"`
	Title        string             `json:"title"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	Status       string             `json:"status"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
}

func (q *Queries) ListActionItems(ctx context.Context, meetingID pgtype.UUID) ([]ListActionItemsRow, error) {
	rows, err := q.db.Query(ctx, listActionItems, meetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionItemsRow{}
	for rows.Next() {
		var i ListActionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Title,
			&i.AssigneeID,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetings = `-- name: ListMeetings :many
SELECT m.id, m.tenant_id, m.employee_id, m.manager_id, m.meeting_date, m.duration_min, m.notes, m.mood, m.follow_up, m.created_at, m.updated_at, e.name AS employee_name, mg.name AS manager_name
FROM meetings m
JOIN employees e ON e.id = m.employee_id
LEFT JOIN employees mg ON mg.id = m.manager_id
WHERE m.tenant_id = $1
ORDER BY m.meeting_date DESC
LIMIT $2 OFFSET $3
`

type ListMeetingsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListMeetingsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	ManagerID    pgtype.UUID        `json:"manager_id"`
	MeetingDate  pgtype.Date        `json:"meeting_date"`
	DurationMin  int16              `json:"duration_min"`
	Notes        string             `json:"notes"`
	Mood         string             `json:"mood"`
	FollowUp     string             `json:"follow_up"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EmployeeName string             `json:"employee_name"`
	ManagerName  pgtype.Text        `json:"manager_name"`
}

func (q *Queries) ListMeetings(ctx context.Context, arg ListMeetingsParams) ([]ListMeetingsRow, error) {
	rows, err := q.db.Query(ctx, listMeetings, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsRow{}
	for rows.Next() {
		var i ListMeetingsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ManagerID,
			&i.MeetingDate,
			&i.DurationMin,
			&i.Notes,
			&i.Mood,
			&i.FollowUp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ManagerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeetingsByEmployee = `-- name: ListMeetingsByEmployee :many
SELECT m.id, m.tenant_id, m.employee_id, m.manager_id, m.meeting_date, m.duration_min, m.notes, m.mood, m.follow_up, m.created_at, m.updated_at, e.name AS employee_name
FROM meetings m
JOIN employees e ON e.id = m.employee_id
WHERE m.employee_id = $1 AND m.tenant_id = $2
ORDER BY m.meeting_date DESC
LIMIT $3 OFFSET $4
`

type ListMeetingsByEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListMeetingsByEmployeeRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	ManagerID    pgtype.UUID        `json:"manager_id"`
	MeetingDate  pgtype.Date        `json:"meeting_date"`
	DurationMin  int16              `json:"duration_min"`
	Notes        string             `json:"notes"`
	Mood         string             `json:"mood"`
	FollowUp     string             `json:"follow_up"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListMeetingsByEmployee(ctx context.Context, arg ListMeetingsByEmployeeParams) ([]ListMeetingsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listMeetingsByEmployee,
		arg.EmployeeID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMeetingsByEmployeeRow{}
	for rows.Next() {
		var i ListMeetingsByEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ManagerID,
			&i.MeetingDate,
			&i.DurationMin,
			&i.Notes,
			&i.Mood,
			&i.FollowUp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenActionItemsByTenant = `-- name: ListOpenActionItemsByTenant :many
SELECT ai.id, ai.meeting_id, ai.title, ai.assignee_id, ai.status, ai.due_date, ai.created_at, ai.updated_at, e.name AS assignee_name, m.meeting_date, emp.name AS employee_name
FROM meeting_action_items ai
JOIN meetings m ON m.id = ai.meeting_id
JOIN employees emp ON emp.id = m.employee_id
LEFT JOIN employees e ON e.id = ai.assignee_id
WHERE m.tenant_id = $1 AND ai.status != 'done'
ORDER BY ai.due_date NULLS LAST, ai.created_at
`

type ListOpenActionItemsByTenantRow struct {
	ID           pgtype.UUID        `json:"id"`
	MeetingID    pgtype.UUID        `json:"meeting_id"`
	Title        string             `json:"title"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	Status       string             `json:"status"`
	DueDate      pgtype.Date        `json:"due_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
	MeetingDate  pgtype.Date        `json:"meeting_date"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListOpenActionItemsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListOpenActionItemsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listOpenActionItemsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenActionItemsByTenantRow{}
	for rows.Next() {
		var i ListOpenActionItemsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.MeetingID,
			&i.Title,
			&i.AssigneeID,
			&i.Status,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeName,
			&i.MeetingDate,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActionItem = `-- name: UpdateActionItem :exec
UPDATE meeting_action_items
SET title = $2, status = $3, assignee_id = $4, due_date = $5, updated_at = now()
WHERE id = $1
`

type UpdateActionItemParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Status     string      `json:"status"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
	DueDate    pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateActionItem(ctx context.Context, arg UpdateActionItemParams) error {
	_, err := q.db.Exec(ctx, updateActionItem,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.DueDate,
	)
	return err
}

const updateMeeting = `-- name: UpdateMeeting :exec
UPDATE meetings
SET notes = $3, mood = $4, follow_up = $5, duration_min = $6, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateMeetingParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Notes       string      `json:"notes"`
	Mood        string      `json:"mood"`
	FollowUp    string      `json:"follow_up"`
	DurationMin int16       `json:"duration_min"`
}

func (q *Queries) UpdateMeeting(ctx context.Context, arg UpdateMeetingParams) error {
	_, err := q.db.Exec(ctx, updateMeeting,
		arg.ID,
		arg.TenantID,
		arg.Notes,
		arg.Mood,
		arg.FollowUp,
		arg.DurationMin,
	)
	return err
}

const verifyMeetingTenant = `-- name: VerifyMeetingTenant :one
SELECT tenant_id FROM meetings WHERE id = $1
`

func (q *Queries) VerifyMeetingTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyMeetingTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
