// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const backfillEmbedding = `-- name: BackfillEmbedding :exec
UPDATE memories SET embedding = $2, updated_at = NOW()
WHERE id = $1 AND embedding IS NULL
`

type BackfillEmbeddingParams struct {
	ID        pgtype.UUID     `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) BackfillEmbedding(ctx context.Context, arg BackfillEmbeddingParams) error {
	_, err := q.db.Exec(ctx, backfillEmbedding, arg.ID, arg.Embedding)
	return err
}

const countMemoriesByTenant = `-- name: CountMemoriesByTenant :one
SELECT COUNT(*) FROM memories
WHERE tenant_id = $1 AND merged_into IS NULL
`

func (q *Queries) CountMemoriesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoriesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one

INSERT INTO memories (
    tenant_id, memory_type, memory_tier, employee_id, source_type, source_id,
    content, summary, embedding, importance, metadata, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at
`

type CreateMemoryParams struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	MemoryType string             `json:"memory_type"`
	MemoryTier string             `json:"memory_tier"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	SourceType pgtype.Text        `json:"source_type"`
	SourceID   pgtype.UUID        `json:"source_id"`
	Content    string             `json:"content"`
	Summary    pgtype.Text        `json:"summary"`
	Embedding  pgvector.Vector    `json:"embedding"`
	Importance pgtype.Float8      `json:"importance"`
	Metadata   []byte             `json:"metadata"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// sql/queries/memories.sql
func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.TenantID,
		arg.MemoryType,
		arg.MemoryTier,
		arg.EmployeeID,
		arg.SourceType,
		arg.SourceID,
		arg.Content,
		arg.Summary,
		arg.Embedding,
		arg.Importance,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemoryType,
		&i.MemoryTier,
		&i.EmployeeID,
		&i.SourceType,
		&i.SourceID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.Importance,
		&i.AccessCount,
		&i.Metadata,
		&i.ExpiresAt,
		&i.MergedInto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredMemories = `-- name: DeleteExpiredMemories :execrows
DELETE FROM memories WHERE expires_at < NOW() AND merged_into IS NULL
`

func (q *Queries) DeleteExpiredMemories(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMemories)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = $1 AND tenant_id = $2
`

type DeleteMemoryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.TenantID)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at FROM memories WHERE id = $1 AND tenant_id = $2
`

type GetMemoryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error) {
	row := q.db.QueryRow(ctx, getMemory, arg.ID, arg.TenantID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemoryType,
		&i.MemoryTier,
		&i.EmployeeID,
		&i.SourceType,
		&i.SourceID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.Importance,
		&i.AccessCount,
		&i.Metadata,
		&i.ExpiresAt,
		&i.MergedInto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByEmployee = `-- name: GetProfileByEmployee :one
SELECT id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at FROM memories
WHERE tenant_id = $1
  AND employee_id = $2
  AND memory_tier = 'profile'
  AND merged_into IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetProfileByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) GetProfileByEmployee(ctx context.Context, arg GetProfileByEmployeeParams) (Memory, error) {
	row := q.db.QueryRow(ctx, getProfileByEmployee, arg.TenantID, arg.EmployeeID)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MemoryType,
		&i.MemoryTier,
		&i.EmployeeID,
		&i.SourceType,
		&i.SourceID,
		&i.Content,
		&i.Summary,
		&i.Embedding,
		&i.Importance,
		&i.AccessCount,
		&i.Metadata,
		&i.ExpiresAt,
		&i.MergedInto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAccessCount = `-- name: IncrementAccessCount :exec
UPDATE memories SET access_count = access_count + 1, updated_at = NOW() WHERE id = $1
`

func (q *Queries) IncrementAccessCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementAccessCount, id)
	return err
}

const listEmployeesWithLongTermMemories = `-- name: ListEmployeesWithLongTermMemories :many
SELECT DISTINCT employee_id FROM memories
WHERE tenant_id = $1
  AND memory_tier = 'long_term'
  AND merged_into IS NULL
  AND employee_id IS NOT NULL
`

func (q *Queries) ListEmployeesWithLongTermMemories(ctx context.Context, tenantID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithLongTermMemories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var employee_id pgtype.UUID
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesWithShortTermMemories = `-- name: ListEmployeesWithShortTermMemories :many
SELECT DISTINCT employee_id FROM memories
WHERE tenant_id = $1
  AND memory_tier = 'short_term'
  AND merged_into IS NULL
  AND employee_id IS NOT NULL
`

func (q *Queries) ListEmployeesWithShortTermMemories(ctx context.Context, tenantID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listEmployeesWithShortTermMemories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var employee_id pgtype.UUID
		if err := rows.Scan(&employee_id); err != nil {
			return nil, err
		}
		items = append(items, employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLongTermByEmployee = `-- name: ListLongTermByEmployee :many
SELECT id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at FROM memories
WHERE tenant_id = $1
  AND employee_id = $2
  AND memory_tier = 'long_term'
  AND merged_into IS NULL
ORDER BY importance DESC, created_at DESC
`

type ListLongTermByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) ListLongTermByEmployee(ctx context.Context, arg ListLongTermByEmployeeParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listLongTermByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemoryType,
			&i.MemoryTier,
			&i.EmployeeID,
			&i.SourceType,
			&i.SourceID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.Importance,
			&i.AccessCount,
			&i.Metadata,
			&i.ExpiresAt,
			&i.MergedInto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByTenant = `-- name: ListMemoriesByTenant :many
SELECT id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at FROM memories
WHERE tenant_id = $1
  AND ($2::varchar = '' OR memory_type = $2)
  AND ($3::varchar = '' OR memory_tier = $3)
  AND ($4::varchar = '' OR employee_id::text = $4)
  AND merged_into IS NULL
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListMemoriesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
	Column4  string      `json:"column_4"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListMemoriesByTenant(ctx context.Context, arg ListMemoriesByTenantParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByTenant,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemoryType,
			&i.MemoryTier,
			&i.EmployeeID,
			&i.SourceType,
			&i.SourceID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.Importance,
			&i.AccessCount,
			&i.Metadata,
			&i.ExpiresAt,
			&i.MergedInto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShortTermByEmployee = `-- name: ListShortTermByEmployee :many
SELECT id, tenant_id, memory_type, memory_tier, employee_id, source_type, source_id, content, summary, embedding, importance, access_count, metadata, expires_at, merged_into, created_at, updated_at FROM memories
WHERE tenant_id = $1
  AND employee_id = $2
  AND memory_tier = 'short_term'
  AND merged_into IS NULL
ORDER BY created_at ASC
LIMIT 200
`

type ListShortTermByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) ListShortTermByEmployee(ctx context.Context, arg ListShortTermByEmployeeParams) ([]Memory, error) {
	rows, err := q.db.Query(ctx, listShortTermByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MemoryType,
			&i.MemoryTier,
			&i.EmployeeID,
			&i.SourceType,
			&i.SourceID,
			&i.Content,
			&i.Summary,
			&i.Embedding,
			&i.Importance,
			&i.AccessCount,
			&i.Metadata,
			&i.ExpiresAt,
			&i.MergedInto,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsWithMemories = `-- name: ListTenantsWithMemories :many
SELECT DISTINCT tenant_id FROM memories WHERE merged_into IS NULL
`

func (q *Queries) ListTenantsWithMemories(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantsWithMemories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryMergedInto = `-- name: UpdateMemoryMergedInto :exec
UPDATE memories SET merged_into = $2, updated_at = NOW() WHERE id = $1
`

type UpdateMemoryMergedIntoParams struct {
	ID         pgtype.UUID `json:"id"`
	MergedInto pgtype.UUID `json:"merged_into"`
}

func (q *Queries) UpdateMemoryMergedInto(ctx context.Context, arg UpdateMemoryMergedIntoParams) error {
	_, err := q.db.Exec(ctx, updateMemoryMergedInto, arg.ID, arg.MergedInto)
	return err
}
