// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMetric = `-- name: CreateMetric :one
INSERT INTO metrics (tenant_id, name, display_name, formula, unit, source,
  refresh_frequency, target_value, alert_threshold, owner_id, owner_team_id, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, tenant_id, name, display_name, formula, unit, source, refresh_frequency, target_value, alert_threshold, owner_id, owner_team_id, tags, is_active, created_at, updated_at, external_id, external_source, external_url
`

type CreateMetricParams struct {
	TenantID         pgtype.UUID    `json:"tenant_id"`
	Name             string         `json:"name"`
	DisplayName      string         `json:"display_name"`
	Formula          string         `json:"formula"`
	Unit             pgtype.Text    `json:"unit"`
	Source           string         `json:"source"`
	RefreshFrequency pgtype.Text    `json:"refresh_frequency"`
	TargetValue      pgtype.Numeric `json:"target_value"`
	AlertThreshold   pgtype.Numeric `json:"alert_threshold"`
	OwnerID          pgtype.UUID    `json:"owner_id"`
	OwnerTeamID      pgtype.UUID    `json:"owner_team_id"`
	Tags             []byte         `json:"tags"`
}

func (q *Queries) CreateMetric(ctx context.Context, arg CreateMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, createMetric,
		arg.TenantID,
		arg.Name,
		arg.DisplayName,
		arg.Formula,
		arg.Unit,
		arg.Source,
		arg.RefreshFrequency,
		arg.TargetValue,
		arg.AlertThreshold,
		arg.OwnerID,
		arg.OwnerTeamID,
		arg.Tags,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Formula,
		&i.Unit,
		&i.Source,
		&i.RefreshFrequency,
		&i.TargetValue,
		&i.AlertThreshold,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Tags,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const deleteMetric = `-- name: DeleteMetric :exec
UPDATE metrics SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeleteMetric(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMetric, id)
	return err
}

const getLatestMetricValue = `-- name: GetLatestMetricValue :one
SELECT id, metric_id, observed_at, value, dimensions, source_ref, created_at FROM metric_values
WHERE metric_id = $1
ORDER BY observed_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMetricValue(ctx context.Context, metricID pgtype.UUID) (MetricValue, error) {
	row := q.db.QueryRow(ctx, getLatestMetricValue, metricID)
	var i MetricValue
	err := row.Scan(
		&i.ID,
		&i.MetricID,
		&i.ObservedAt,
		&i.Value,
		&i.Dimensions,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}

const getMetric = `-- name: GetMetric :one
SELECT id, tenant_id, name, display_name, formula, unit, source, refresh_frequency, target_value, alert_threshold, owner_id, owner_team_id, tags, is_active, created_at, updated_at, external_id, external_source, external_url FROM metrics WHERE id = $1
`

func (q *Queries) GetMetric(ctx context.Context, id pgtype.UUID) (Metric, error) {
	row := q.db.QueryRow(ctx, getMetric, id)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Formula,
		&i.Unit,
		&i.Source,
		&i.RefreshFrequency,
		&i.TargetValue,
		&i.AlertThreshold,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Tags,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const getMetricsWithLatestValues = `-- name: GetMetricsWithLatestValues :many
SELECT m.id, m.tenant_id, m.name, m.display_name, m.formula, m.unit,
  m.source, m.refresh_frequency, m.target_value, m.alert_threshold,
  m.owner_id, m.owner_team_id, m.tags, m.is_active, m.created_at, m.updated_at,
  mv.value AS latest_value,
  mv.observed_at AS latest_observed_at
FROM metrics m
LEFT JOIN LATERAL (
  SELECT value, observed_at
  FROM metric_values WHERE metric_id = m.id
  ORDER BY observed_at DESC LIMIT 1
) mv ON true
WHERE m.tenant_id = $1 AND m.is_active = true
ORDER BY m.name
`

type GetMetricsWithLatestValuesRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Formula          string             `json:"formula"`
	Unit             pgtype.Text        `json:"unit"`
	Source           string             `json:"source"`
	RefreshFrequency pgtype.Text        `json:"refresh_frequency"`
	TargetValue      pgtype.Numeric     `json:"target_value"`
	AlertThreshold   pgtype.Numeric     `json:"alert_threshold"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	OwnerTeamID      pgtype.UUID        `json:"owner_team_id"`
	Tags             []byte             `json:"tags"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LatestValue      pgtype.Numeric     `json:"latest_value"`
	LatestObservedAt pgtype.Timestamptz `json:"latest_observed_at"`
}

func (q *Queries) GetMetricsWithLatestValues(ctx context.Context, tenantID pgtype.UUID) ([]GetMetricsWithLatestValuesRow, error) {
	rows, err := q.db.Query(ctx, getMetricsWithLatestValues, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMetricsWithLatestValuesRow{}
	for rows.Next() {
		var i GetMetricsWithLatestValuesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Formula,
			&i.Unit,
			&i.Source,
			&i.RefreshFrequency,
			&i.TargetValue,
			&i.AlertThreshold,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Tags,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestValue,
			&i.LatestObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingestMetricValue = `-- name: IngestMetricValue :one
INSERT INTO metric_values (metric_id, observed_at, value, dimensions, source_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, metric_id, observed_at, value, dimensions, source_ref, created_at
`

type IngestMetricValueParams struct {
	MetricID   pgtype.UUID        `json:"metric_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Value      pgtype.Numeric     `json:"value"`
	Dimensions []byte             `json:"dimensions"`
	SourceRef  pgtype.Text        `json:"source_ref"`
}

func (q *Queries) IngestMetricValue(ctx context.Context, arg IngestMetricValueParams) (MetricValue, error) {
	row := q.db.QueryRow(ctx, ingestMetricValue,
		arg.MetricID,
		arg.ObservedAt,
		arg.Value,
		arg.Dimensions,
		arg.SourceRef,
	)
	var i MetricValue
	err := row.Scan(
		&i.ID,
		&i.MetricID,
		&i.ObservedAt,
		&i.Value,
		&i.Dimensions,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}

const listMetricValues = `-- name: ListMetricValues :many
SELECT id, metric_id, observed_at, value, dimensions, source_ref, created_at FROM metric_values
WHERE metric_id = $1 AND observed_at >= $2
ORDER BY observed_at DESC
LIMIT $3
`

type ListMetricValuesParams struct {
	MetricID   pgtype.UUID        `json:"metric_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListMetricValues(ctx context.Context, arg ListMetricValuesParams) ([]MetricValue, error) {
	rows, err := q.db.Query(ctx, listMetricValues, arg.MetricID, arg.ObservedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetricValue{}
	for rows.Next() {
		var i MetricValue
		if err := rows.Scan(
			&i.ID,
			&i.MetricID,
			&i.ObservedAt,
			&i.Value,
			&i.Dimensions,
			&i.SourceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetrics = `-- name: ListMetrics :many
SELECT id, tenant_id, name, display_name, formula, unit, source, refresh_frequency, target_value, alert_threshold, owner_id, owner_team_id, tags, is_active, created_at, updated_at, external_id, external_source, external_url FROM metrics
WHERE tenant_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListMetrics(ctx context.Context, tenantID pgtype.UUID) ([]Metric, error) {
	rows, err := q.db.Query(ctx, listMetrics, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Metric{}
	for rows.Next() {
		var i Metric
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.DisplayName,
			&i.Formula,
			&i.Unit,
			&i.Source,
			&i.RefreshFrequency,
			&i.TargetValue,
			&i.AlertThreshold,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Tags,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetric = `-- name: UpdateMetric :one
UPDATE metrics SET
  display_name = $2, formula = $3, unit = $4, source = $5,
  target_value = $6, alert_threshold = $7, owner_id = $8,
  tags = $9, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, display_name, formula, unit, source, refresh_frequency, target_value, alert_threshold, owner_id, owner_team_id, tags, is_active, created_at, updated_at, external_id, external_source, external_url
`

type UpdateMetricParams struct {
	ID             pgtype.UUID    `json:"id"`
	DisplayName    string         `json:"display_name"`
	Formula        string         `json:"formula"`
	Unit           pgtype.Text    `json:"unit"`
	Source         string         `json:"source"`
	TargetValue    pgtype.Numeric `json:"target_value"`
	AlertThreshold pgtype.Numeric `json:"alert_threshold"`
	OwnerID        pgtype.UUID    `json:"owner_id"`
	Tags           []byte         `json:"tags"`
}

func (q *Queries) UpdateMetric(ctx context.Context, arg UpdateMetricParams) (Metric, error) {
	row := q.db.QueryRow(ctx, updateMetric,
		arg.ID,
		arg.DisplayName,
		arg.Formula,
		arg.Unit,
		arg.Source,
		arg.TargetValue,
		arg.AlertThreshold,
		arg.OwnerID,
		arg.Tags,
	)
	var i Metric
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.DisplayName,
		&i.Formula,
		&i.Unit,
		&i.Source,
		&i.RefreshFrequency,
		&i.TargetValue,
		&i.AlertThreshold,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Tags,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const verifyMetricTenant = `-- name: VerifyMetricTenant :one
SELECT tenant_id FROM metrics WHERE id = $1
`

func (q *Queries) VerifyMetricTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyMetricTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
