// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AiRoleInstance struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	RoleID    string             `json:"role_id"`
	Title     string             `json:"title"`
	MentorID  string             `json:"mentor_id"`
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AiSuggestion struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	RoleID      string             `json:"role_id"`
	RoleTitle   string             `json:"role_title"`
	Capability  string             `json:"capability"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	ContextData []byte             `json:"context_data"`
	Status      string             `json:"status"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChaseLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	ReportDate pgtype.Date        `json:"report_date"`
	Step       int32              `json:"step"`
	Action     string             `json:"action"`
	Message    string             `json:"message"`
	ChasedAt   pgtype.Timestamptz `json:"chased_at"`
	Channel    string             `json:"channel"`
}

type Employee struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	TelegramID       pgtype.Int8        `json:"telegram_id"`
	CultureCode      string             `json:"culture_code"`
	Role             string             `json:"role"`
	InviteCode       pgtype.Text        `json:"invite_code"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SignalPhone      pgtype.Text        `json:"signal_phone"`
	SlackID          pgtype.Text        `json:"slack_id"`
	LarkID           pgtype.Text        `json:"lark_id"`
	PreferredChannel string             `json:"preferred_channel"`
	JobTitle         string             `json:"job_title"`
	Responsibilities string             `json:"responsibilities"`
	Country          string             `json:"country"`
	Language         string             `json:"language"`
}

type Memory struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	MemoryType  string             `json:"memory_type"`
	MemoryTier  string             `json:"memory_tier"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	SourceType  pgtype.Text        `json:"source_type"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Content     string             `json:"content"`
	Summary     pgtype.Text        `json:"summary"`
	Embedding   pgvector.Vector    `json:"embedding"`
	Importance  pgtype.Float8      `json:"importance"`
	AccessCount pgtype.Int4        `json:"access_count"`
	Metadata    []byte             `json:"metadata"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MergedInto  pgtype.UUID        `json:"merged_into"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Industry       string             `json:"industry"`
	Size           int32              `json:"size"`
	Stage          string             `json:"stage"`
	BusinessModel  pgtype.Text        `json:"business_model"`
	Region         pgtype.Text        `json:"region"`
	MentorID       string             `json:"mentor_id"`
	ManagementPlan []byte             `json:"management_plan"`
	PlanVersion    int32              `json:"plan_version"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Report struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	ReportDate  pgtype.Date        `json:"report_date"`
	Answers     []byte             `json:"answers"`
	Blockers    pgtype.Text        `json:"blockers"`
	Sentiment   pgtype.Text        `json:"sentiment"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	Channel     string             `json:"channel"`
}

type Summary struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	SummaryDate    pgtype.Date        `json:"summary_date"`
	Content        string             `json:"content"`
	SubmissionRate float64            `json:"submission_rate"`
	BlockersCount  int32              `json:"blockers_count"`
	KeyMetrics     []byte             `json:"key_metrics"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Timezone           string             `json:"timezone"`
	AnthropicKey       pgtype.Text        `json:"anthropic_key"`
	MentorID           string             `json:"mentor_id"`
	MentorBlend        []byte             `json:"mentor_blend"`
	BotToken           pgtype.Text        `json:"bot_token"`
	BossChatID         int64              `json:"boss_chat_id"`
	Config             []byte             `json:"config"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Plan               string             `json:"plan"`
	SlackBotToken      pgtype.Text        `json:"slack_bot_token"`
	SlackSigningSecret pgtype.Text        `json:"slack_signing_secret"`
	LarkAppID          pgtype.Text        `json:"lark_app_id"`
	LarkAppSecret      pgtype.Text        `json:"lark_app_secret"`
	SignalPhone        pgtype.Text        `json:"signal_phone"`
	EnabledChannels    []string           `json:"enabled_channels"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type WizardSession struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	MentorID       string             `json:"mentor_id"`
	CurrentStep    string             `json:"current_step"`
	Conversation   []byte             `json:"conversation"`
	CompanyProfile []byte             `json:"company_profile"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
