// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AiRoleInstance struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	RoleID    string             `json:"role_id"`
	Title     string             `json:"title"`
	MentorID  string             `json:"mentor_id"`
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AiSuggestion struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	RoleID      string             `json:"role_id"`
	RoleTitle   string             `json:"role_title"`
	Capability  string             `json:"capability"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	ContextData []byte             `json:"context_data"`
	Status      string             `json:"status"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	IsActive   bool               `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CareerLevel struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Title        string             `json:"title"`
	LevelOrder   int32              `json:"level_order"`
	Description  string             `json:"description"`
	Requirements string             `json:"requirements"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CareerPath struct {
	ID             pgtype.UUID        `json:"id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	CurrentLevelID pgtype.UUID        `json:"current_level_id"`
	TargetLevelID  pgtype.UUID        `json:"target_level_id"`
	TargetDate     pgtype.Date        `json:"target_date"`
	Notes          string             `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ChaseLog struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	ReportDate pgtype.Date        `json:"report_date"`
	Step       int32              `json:"step"`
	Action     string             `json:"action"`
	Message    string             `json:"message"`
	ChasedAt   pgtype.Timestamptz `json:"chased_at"`
	Channel    string             `json:"channel"`
}

type CommunicationEvent struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	SourceType       string             `json:"source_type"`
	SourceID         pgtype.UUID        `json:"source_id"`
	Platform         string             `json:"platform"`
	EventType        string             `json:"event_type"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	TargetID         pgtype.UUID        `json:"target_id"`
	RelatedTaskID    pgtype.UUID        `json:"related_task_id"`
	RelatedProjectID pgtype.UUID        `json:"related_project_id"`
	RelatedGoalID    pgtype.UUID        `json:"related_goal_id"`
	Payload          []byte             `json:"payload"`
	Confidence       pgtype.Numeric     `json:"confidence"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	TelegramID       pgtype.Int8        `json:"telegram_id"`
	CultureCode      string             `json:"culture_code"`
	Role             string             `json:"role"`
	InviteCode       pgtype.Text        `json:"invite_code"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SignalPhone      pgtype.Text        `json:"signal_phone"`
	SlackID          pgtype.Text        `json:"slack_id"`
	LarkID           pgtype.Text        `json:"lark_id"`
	PreferredChannel string             `json:"preferred_channel"`
	JobTitle         string             `json:"job_title"`
	Responsibilities string             `json:"responsibilities"`
	Country          string             `json:"country"`
	Language         string             `json:"language"`
	OrgUnitID        pgtype.UUID        `json:"org_unit_id"`
	ExecutionScore   pgtype.Numeric     `json:"execution_score"`
	CurrentLoad      pgtype.Text        `json:"current_load"`
	Strengths        []byte             `json:"strengths"`
	RiskFlags        []byte             `json:"risk_flags"`
	WorkScope        []byte             `json:"work_scope"`
	HalaosEmployeeID pgtype.Int8        `json:"halaos_employee_id"`
	HalaosEmployeeNo pgtype.Text        `json:"halaos_employee_no"`
}

type EmployeeSkill struct {
	ID         pgtype.UUID        `json:"id"`
	EmployeeID pgtype.UUID        `json:"employee_id"`
	SkillID    pgtype.UUID        `json:"skill_id"`
	Level      int16              `json:"level"`
	Notes      string             `json:"notes"`
	AssessedAt pgtype.Timestamptz `json:"assessed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ExecutionSignal struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SubjectType string             `json:"subject_type"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	SignalType  string             `json:"signal_type"`
	Score       pgtype.Numeric     `json:"score"`
	Reasons     []byte             `json:"reasons"`
	TimeWindow  pgtype.Text        `json:"time_window"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

type Goal struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	OwnerID      pgtype.UUID        `json:"owner_id"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Cycle        string             `json:"cycle"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Level        string             `json:"level"`
	GoalType     string             `json:"goal_type"`
	SourceSystem pgtype.Text        `json:"source_system"`
	SourceRef    pgtype.Text        `json:"source_ref"`
}

type GoalSnapshot struct {
	ID              pgtype.UUID        `json:"id"`
	GoalID          pgtype.UUID        `json:"goal_id"`
	OverallProgress pgtype.Numeric     `json:"overall_progress"`
	SnapshotDate    pgtype.Date        `json:"snapshot_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type GroupChat struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Platform       string             `json:"platform"`
	PlatformChatID string             `json:"platform_chat_id"`
	Name           string             `json:"name"`
	GroupType      string             `json:"group_type"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type HalaosEvent struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	EventType      string             `json:"event_type"`
	IdempotencyKey string             `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

type HalaosLink struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	WebhookSecret   string             `json:"webhook_secret"`
	HalaosCompanyID int64              `json:"halaos_company_id"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IncentiveRule struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	RewardModel      string             `json:"reward_model"`
	PayoutCycle      string             `json:"payout_cycle"`
	AttributionRules []byte             `json:"attribution_rules"`
	PenaltyRules     []byte             `json:"penalty_rules"`
	ScoringFormula   []byte             `json:"scoring_formula"`
	AppliesTo        []byte             `json:"applies_to"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type IncentiveScore struct {
	ID                    pgtype.UUID        `json:"id"`
	TenantID              pgtype.UUID        `json:"tenant_id"`
	RuleID                pgtype.UUID        `json:"rule_id"`
	PersonID              pgtype.UUID        `json:"person_id"`
	Period                string             `json:"period"`
	Score                 pgtype.Numeric     `json:"score"`
	ScoreBreakdown        []byte             `json:"score_breakdown"`
	PayoutWeight          pgtype.Numeric     `json:"payout_weight"`
	AttributionConfidence pgtype.Numeric     `json:"attribution_confidence"`
	Status                string             `json:"status"`
	CalculatedAt          pgtype.Timestamptz `json:"calculated_at"`
	ReviewedAt            pgtype.Timestamptz `json:"reviewed_at"`
}

type KeyResult struct {
	ID            pgtype.UUID        `json:"id"`
	GoalID        pgtype.UUID        `json:"goal_id"`
	Title         string             `json:"title"`
	Target        pgtype.Numeric     `json:"target"`
	CurrentValue  pgtype.Numeric     `json:"current_value"`
	Unit          string             `json:"unit"`
	DueDate       pgtype.Date        `json:"due_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MetricID      pgtype.UUID        `json:"metric_id"`
	BaselineValue pgtype.Numeric     `json:"baseline_value"`
	FormulaNote   pgtype.Text        `json:"formula_note"`
	Status        string             `json:"status"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
}

type Meeting struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	ManagerID   pgtype.UUID        `json:"manager_id"`
	MeetingDate pgtype.Date        `json:"meeting_date"`
	DurationMin int16              `json:"duration_min"`
	Notes       string             `json:"notes"`
	Mood        string             `json:"mood"`
	FollowUp    string             `json:"follow_up"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MeetingActionItem struct {
	ID         pgtype.UUID        `json:"id"`
	MeetingID  pgtype.UUID        `json:"meeting_id"`
	Title      string             `json:"title"`
	AssigneeID pgtype.UUID        `json:"assignee_id"`
	Status     string             `json:"status"`
	DueDate    pgtype.Date        `json:"due_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Memory struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	MemoryType  string             `json:"memory_type"`
	MemoryTier  string             `json:"memory_tier"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	SourceType  pgtype.Text        `json:"source_type"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Content     string             `json:"content"`
	Summary     pgtype.Text        `json:"summary"`
	Embedding   pgvector.Vector    `json:"embedding"`
	Importance  pgtype.Float8      `json:"importance"`
	AccessCount pgtype.Int4        `json:"access_count"`
	Metadata    []byte             `json:"metadata"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MergedInto  pgtype.UUID        `json:"merged_into"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Metric struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	Formula          string             `json:"formula"`
	Unit             pgtype.Text        `json:"unit"`
	Source           string             `json:"source"`
	RefreshFrequency pgtype.Text        `json:"refresh_frequency"`
	TargetValue      pgtype.Numeric     `json:"target_value"`
	AlertThreshold   pgtype.Numeric     `json:"alert_threshold"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	OwnerTeamID      pgtype.UUID        `json:"owner_team_id"`
	Tags             []byte             `json:"tags"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MetricValue struct {
	ID         int64              `json:"id"`
	MetricID   pgtype.UUID        `json:"metric_id"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	Value      pgtype.Numeric     `json:"value"`
	Dimensions []byte             `json:"dimensions"`
	SourceRef  pgtype.Text        `json:"source_ref"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type OnboardingSession struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Status        string             `json:"status"`
	ConfirmStep   int32              `json:"confirm_step"`
	CollectedData []byte             `json:"collected_data"`
	ProposedPlan  []byte             `json:"proposed_plan"`
	MessageCount  int32              `json:"message_count"`
	ChannelType   string             `json:"channel_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type OrgUnit struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ParentID         pgtype.UUID        `json:"parent_id"`
	Name             string             `json:"name"`
	UnitType         string             `json:"unit_type"`
	HeadRole         pgtype.Text        `json:"head_role"`
	HeadEmployeeID   pgtype.UUID        `json:"head_employee_id"`
	Responsibilities pgtype.Text        `json:"responsibilities"`
	SortOrder        int32              `json:"sort_order"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID                     pgtype.UUID        `json:"id"`
	TenantID               pgtype.UUID        `json:"tenant_id"`
	Industry               pgtype.Text        `json:"industry"`
	Size                   pgtype.Int4        `json:"size"`
	Stage                  pgtype.Text        `json:"stage"`
	BusinessModel          pgtype.Text        `json:"business_model"`
	Region                 pgtype.Text        `json:"region"`
	MentorID               string             `json:"mentor_id"`
	ManagementPlan         []byte             `json:"management_plan"`
	PlanVersion            int32              `json:"plan_version"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ManagementPainPoints   []string           `json:"management_pain_points"`
	CurrentProjects        []byte             `json:"current_projects"`
	TargetFramework        pgtype.Text        `json:"target_framework"`
	TeamStructure          []byte             `json:"team_structure"`
	CommunicationTools     []string           `json:"communication_tools"`
	CulturePreferences     []byte             `json:"culture_preferences"`
	StrategicPriorities    []byte             `json:"strategic_priorities"`
	KeyRisks               []byte             `json:"key_risks"`
	ManagementStyleWeights []byte             `json:"management_style_weights"`
	Countries              []byte             `json:"countries"`
}

type PerformanceReview struct {
	ID             pgtype.UUID        `json:"id"`
	CycleID        pgtype.UUID        `json:"cycle_id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	ReviewerID     pgtype.UUID        `json:"reviewer_id"`
	Status         string             `json:"status"`
	SelfRating     pgtype.Int2        `json:"self_rating"`
	ManagerRating  pgtype.Int2        `json:"manager_rating"`
	SelfSummary    string             `json:"self_summary"`
	ManagerSummary string             `json:"manager_summary"`
	Strengths      string             `json:"strengths"`
	Improvements   string             `json:"improvements"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	OwnerTeamID     pgtype.UUID        `json:"owner_team_id"`
	Status          string             `json:"status"`
	Priority        string             `json:"priority"`
	LinkedGoalIds   []byte             `json:"linked_goal_ids"`
	LinkedMetricIds []byte             `json:"linked_metric_ids"`
	Blockers        []byte             `json:"blockers"`
	SourceSystem    pgtype.Text        `json:"source_system"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	StartDate       pgtype.Date        `json:"start_date"`
	DueDate         pgtype.Date        `json:"due_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Recommendation struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Category         string             `json:"category"`
	Priority         string             `json:"priority"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	SuggestedActions []byte             `json:"suggested_actions"`
	Evidence         []byte             `json:"evidence"`
	Source           string             `json:"source"`
	Status           string             `json:"status"`
	TargetEntityType pgtype.Text        `json:"target_entity_type"`
	TargetEntityID   pgtype.UUID        `json:"target_entity_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ExecutedAt       pgtype.Timestamptz `json:"executed_at"`
}

type Report struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	ReportDate  pgtype.Date        `json:"report_date"`
	Answers     []byte             `json:"answers"`
	Blockers    pgtype.Text        `json:"blockers"`
	Sentiment   pgtype.Text        `json:"sentiment"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	Channel     string             `json:"channel"`
}

type ReportingLine struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ManagerID        pgtype.UUID        `json:"manager_id"`
	ReportID         pgtype.UUID        `json:"report_id"`
	RelationshipType string             `json:"relationship_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ReviewCycle struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Title     string             `json:"title"`
	Period    string             `json:"period"`
	Status    string             `json:"status"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Seat struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	SeatType  string             `json:"seat_type"`
	Title     string             `json:"title"`
	PersonaID string             `json:"persona_id"`
	Scope     string             `json:"scope"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Skill struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Summary struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	SummaryDate    pgtype.Date        `json:"summary_date"`
	Content        string             `json:"content"`
	SubmissionRate float64            `json:"submission_rate"`
	BlockersCount  int32              `json:"blockers_count"`
	KeyMetrics     []byte             `json:"key_metrics"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	GoalID         pgtype.UUID        `json:"goal_id"`
	KeyResultID    pgtype.UUID        `json:"key_result_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	OwnerTeamID    pgtype.UUID        `json:"owner_team_id"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	CreatedByAgent bool               `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	Timezone              string             `json:"timezone"`
	AnthropicKey          pgtype.Text        `json:"anthropic_key"`
	MentorID              string             `json:"mentor_id"`
	MentorBlend           []byte             `json:"mentor_blend"`
	BotToken              pgtype.Text        `json:"bot_token"`
	BossChatID            int64              `json:"boss_chat_id"`
	Config                []byte             `json:"config"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Plan                  string             `json:"plan"`
	SlackBotToken         pgtype.Text        `json:"slack_bot_token"`
	SlackSigningSecret    pgtype.Text        `json:"slack_signing_secret"`
	LarkAppID             pgtype.Text        `json:"lark_app_id"`
	LarkAppSecret         pgtype.Text        `json:"lark_app_secret"`
	SignalPhone           pgtype.Text        `json:"signal_phone"`
	EnabledChannels       []string           `json:"enabled_channels"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	BossSlackID           pgtype.Text        `json:"boss_slack_id"`
	BossLarkID            pgtype.Text        `json:"boss_lark_id"`
}

type TrainingEnrollment struct {
	ID          pgtype.UUID        `json:"id"`
	ProgramID   pgtype.UUID        `json:"program_id"`
	EmployeeID  pgtype.UUID        `json:"employee_id"`
	Status      string             `json:"status"`
	EnrolledAt  pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Score       pgtype.Int4        `json:"score"`
	Notes       string             `json:"notes"`
}

type TrainingProgram struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Category      string             `json:"category"`
	DurationHours int32              `json:"duration_hours"`
	Provider      string             `json:"provider"`
	Url           string             `json:"url"`
	IsMandatory   bool               `json:"is_mandatory"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Workflow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	Name              string             `json:"name"`
	Category          pgtype.Text        `json:"category"`
	TriggerConditions []byte             `json:"trigger_conditions"`
	Steps             []byte             `json:"steps"`
	ApprovalRules     []byte             `json:"approval_rules"`
	EscalationRules   []byte             `json:"escalation_rules"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type WorkingMemorySnapshot struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SnapshotType string             `json:"snapshot_type"`
	Content      []byte             `json:"content"`
	GeneratedBy  pgtype.Text        `json:"generated_by"`
	GeneratedAt  pgtype.Timestamptz `json:"generated_at"`
}
