// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingSession = `-- name: CreateOnboardingSession :one
INSERT INTO onboarding_sessions (tenant_id, status, channel_type)
VALUES ($1, 'onboarding', $2)
RETURNING id, tenant_id, status, confirm_step, collected_data, proposed_plan, message_count, channel_type, created_at, updated_at
`

type CreateOnboardingSessionParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChannelType string      `json:"channel_type"`
}

func (q *Queries) CreateOnboardingSession(ctx context.Context, arg CreateOnboardingSessionParams) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, createOnboardingSession, arg.TenantID, arg.ChannelType)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.ConfirmStep,
		&i.CollectedData,
		&i.ProposedPlan,
		&i.MessageCount,
		&i.ChannelType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOnboardingSession = `-- name: DeleteOnboardingSession :exec
DELETE FROM onboarding_sessions WHERE tenant_id = $1
`

func (q *Queries) DeleteOnboardingSession(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOnboardingSession, tenantID)
	return err
}

const getOnboardingSession = `-- name: GetOnboardingSession :one
SELECT id, tenant_id, status, confirm_step, collected_data, proposed_plan, message_count, channel_type, created_at, updated_at FROM onboarding_sessions WHERE tenant_id = $1
`

func (q *Queries) GetOnboardingSession(ctx context.Context, tenantID pgtype.UUID) (OnboardingSession, error) {
	row := q.db.QueryRow(ctx, getOnboardingSession, tenantID)
	var i OnboardingSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.ConfirmStep,
		&i.CollectedData,
		&i.ProposedPlan,
		&i.MessageCount,
		&i.ChannelType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByBossLarkID = `-- name: GetTenantByBossLarkID :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at, plan, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels, onboarding_completed_at, boss_slack_id, boss_lark_id FROM tenants WHERE boss_lark_id = $1 AND boss_lark_id IS NOT NULL
`

func (q *Queries) GetTenantByBossLarkID(ctx context.Context, bossLarkID pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByBossLarkID, bossLarkID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
		&i.Plan,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
		&i.OnboardingCompletedAt,
		&i.BossSlackID,
		&i.BossLarkID,
	)
	return i, err
}

const getTenantByBossSlackID = `-- name: GetTenantByBossSlackID :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at, plan, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels, onboarding_completed_at, boss_slack_id, boss_lark_id FROM tenants WHERE boss_slack_id = $1 AND boss_slack_id IS NOT NULL
`

func (q *Queries) GetTenantByBossSlackID(ctx context.Context, bossSlackID pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByBossSlackID, bossSlackID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
		&i.Plan,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
		&i.OnboardingCompletedAt,
		&i.BossSlackID,
		&i.BossLarkID,
	)
	return i, err
}

const setTenantOnboardingCompleted = `-- name: SetTenantOnboardingCompleted :exec
UPDATE tenants SET onboarding_completed_at = now() WHERE id = $1
`

func (q *Queries) SetTenantOnboardingCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setTenantOnboardingCompleted, id)
	return err
}

const updateOnboardingSession = `-- name: UpdateOnboardingSession :exec
UPDATE onboarding_sessions
SET status = $2, confirm_step = $3, collected_data = $4,
    proposed_plan = $5, message_count = $6, channel_type = $7,
    updated_at = now()
WHERE tenant_id = $1
`

type UpdateOnboardingSessionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Status        string      `json:"status"`
	ConfirmStep   int32       `json:"confirm_step"`
	CollectedData []byte      `json:"collected_data"`
	ProposedPlan  []byte      `json:"proposed_plan"`
	MessageCount  int32       `json:"message_count"`
	ChannelType   string      `json:"channel_type"`
}

func (q *Queries) UpdateOnboardingSession(ctx context.Context, arg UpdateOnboardingSessionParams) error {
	_, err := q.db.Exec(ctx, updateOnboardingSession,
		arg.TenantID,
		arg.Status,
		arg.ConfirmStep,
		arg.CollectedData,
		arg.ProposedPlan,
		arg.MessageCount,
		arg.ChannelType,
	)
	return err
}

const updateOrganizationFromOnboarding = `-- name: UpdateOrganizationFromOnboarding :exec
UPDATE organizations
SET industry = $2, size = $3, stage = $4, business_model = $5,
    management_pain_points = $6, current_projects = $7,
    target_framework = $8, team_structure = $9,
    communication_tools = $10, culture_preferences = $11,
    updated_at = now()
WHERE tenant_id = $1
`

type UpdateOrganizationFromOnboardingParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	Industry             pgtype.Text `json:"industry"`
	Size                 pgtype.Int4 `json:"size"`
	Stage                pgtype.Text `json:"stage"`
	BusinessModel        pgtype.Text `json:"business_model"`
	ManagementPainPoints []string    `json:"management_pain_points"`
	CurrentProjects      []byte      `json:"current_projects"`
	TargetFramework      pgtype.Text `json:"target_framework"`
	TeamStructure        []byte      `json:"team_structure"`
	CommunicationTools   []string    `json:"communication_tools"`
	CulturePreferences   []byte      `json:"culture_preferences"`
}

func (q *Queries) UpdateOrganizationFromOnboarding(ctx context.Context, arg UpdateOrganizationFromOnboardingParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationFromOnboarding,
		arg.TenantID,
		arg.Industry,
		arg.Size,
		arg.Stage,
		arg.BusinessModel,
		arg.ManagementPainPoints,
		arg.CurrentProjects,
		arg.TargetFramework,
		arg.TeamStructure,
		arg.CommunicationTools,
		arg.CulturePreferences,
	)
	return err
}
