// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_units.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignEmployeeToUnit = `-- name: AssignEmployeeToUnit :exec
UPDATE employees SET org_unit_id = $2 WHERE id = $1
`

type AssignEmployeeToUnitParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgUnitID pgtype.UUID `json:"org_unit_id"`
}

func (q *Queries) AssignEmployeeToUnit(ctx context.Context, arg AssignEmployeeToUnitParams) error {
	_, err := q.db.Exec(ctx, assignEmployeeToUnit, arg.ID, arg.OrgUnitID)
	return err
}

const createOrgUnit = `-- name: CreateOrgUnit :one
INSERT INTO org_units (tenant_id, parent_id, name, unit_type, head_role, responsibilities, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, parent_id, name, unit_type, head_role, head_employee_id, responsibilities, sort_order, is_active, created_at, updated_at
`

type CreateOrgUnitParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	ParentID         pgtype.UUID `json:"parent_id"`
	Name             string      `json:"name"`
	UnitType         string      `json:"unit_type"`
	HeadRole         pgtype.Text `json:"head_role"`
	Responsibilities pgtype.Text `json:"responsibilities"`
	SortOrder        int32       `json:"sort_order"`
}

func (q *Queries) CreateOrgUnit(ctx context.Context, arg CreateOrgUnitParams) (OrgUnit, error) {
	row := q.db.QueryRow(ctx, createOrgUnit,
		arg.TenantID,
		arg.ParentID,
		arg.Name,
		arg.UnitType,
		arg.HeadRole,
		arg.Responsibilities,
		arg.SortOrder,
	)
	var i OrgUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.UnitType,
		&i.HeadRole,
		&i.HeadEmployeeID,
		&i.Responsibilities,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgUnitsByTenant = `-- name: DeleteOrgUnitsByTenant :exec
DELETE FROM org_units WHERE tenant_id = $1
`

func (q *Queries) DeleteOrgUnitsByTenant(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrgUnitsByTenant, tenantID)
	return err
}

const getOrgUnit = `-- name: GetOrgUnit :one
SELECT id, tenant_id, parent_id, name, unit_type, head_role, head_employee_id, responsibilities, sort_order, is_active, created_at, updated_at FROM org_units WHERE id = $1
`

func (q *Queries) GetOrgUnit(ctx context.Context, id pgtype.UUID) (OrgUnit, error) {
	row := q.db.QueryRow(ctx, getOrgUnit, id)
	var i OrgUnit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.UnitType,
		&i.HeadRole,
		&i.HeadEmployeeID,
		&i.Responsibilities,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeesByUnit = `-- name: ListEmployeesByUnit :many
SELECT id, tenant_id, name, telegram_id, culture_code, role, invite_code, is_active, created_at, signal_phone, slack_id, lark_id, preferred_channel, job_title, responsibilities, country, language, org_unit_id FROM employees WHERE org_unit_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListEmployeesByUnit(ctx context.Context, orgUnitID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByUnit, orgUnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.SignalPhone,
			&i.SlackID,
			&i.LarkID,
			&i.PreferredChannel,
			&i.JobTitle,
			&i.Responsibilities,
			&i.Country,
			&i.Language,
			&i.OrgUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUnits = `-- name: ListOrgUnits :many
SELECT id, tenant_id, parent_id, name, unit_type, head_role, head_employee_id, responsibilities, sort_order, is_active, created_at, updated_at FROM org_units WHERE tenant_id = $1 AND is_active = true ORDER BY sort_order, name
`

func (q *Queries) ListOrgUnits(ctx context.Context, tenantID pgtype.UUID) ([]OrgUnit, error) {
	rows, err := q.db.Query(ctx, listOrgUnits, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgUnit{}
	for rows.Next() {
		var i OrgUnit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.UnitType,
			&i.HeadRole,
			&i.HeadEmployeeID,
			&i.Responsibilities,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrgUnit = `-- name: SoftDeleteOrgUnit :exec
UPDATE org_units SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteOrgUnit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrgUnit, id)
	return err
}

const updateOrgUnit = `-- name: UpdateOrgUnit :exec
UPDATE org_units
SET name = $2, unit_type = $3, parent_id = $4, head_role = $5,
    head_employee_id = $6, responsibilities = $7, updated_at = now()
WHERE id = $1
`

type UpdateOrgUnitParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	UnitType         string      `json:"unit_type"`
	ParentID         pgtype.UUID `json:"parent_id"`
	HeadRole         pgtype.Text `json:"head_role"`
	HeadEmployeeID   pgtype.UUID `json:"head_employee_id"`
	Responsibilities pgtype.Text `json:"responsibilities"`
}

func (q *Queries) UpdateOrgUnit(ctx context.Context, arg UpdateOrgUnitParams) error {
	_, err := q.db.Exec(ctx, updateOrgUnit,
		arg.ID,
		arg.Name,
		arg.UnitType,
		arg.ParentID,
		arg.HeadRole,
		arg.HeadEmployeeID,
		arg.Responsibilities,
	)
	return err
}
