// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, plan_version, status, created_at, updated_at, management_pain_points, current_projects, target_framework, team_structure, communication_tools, culture_preferences, strategic_priorities, key_risks, management_style_weights, countries
`

type CreateOrganizationParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Industry       pgtype.Text `json:"industry"`
	Size           pgtype.Int4 `json:"size"`
	Stage          pgtype.Text `json:"stage"`
	BusinessModel  pgtype.Text `json:"business_model"`
	Region         pgtype.Text `json:"region"`
	MentorID       string      `json:"mentor_id"`
	ManagementPlan []byte      `json:"management_plan"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.TenantID,
		arg.Industry,
		arg.Size,
		arg.Stage,
		arg.BusinessModel,
		arg.Region,
		arg.MentorID,
		arg.ManagementPlan,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Industry,
		&i.Size,
		&i.Stage,
		&i.BusinessModel,
		&i.Region,
		&i.MentorID,
		&i.ManagementPlan,
		&i.PlanVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagementPainPoints,
		&i.CurrentProjects,
		&i.TargetFramework,
		&i.TeamStructure,
		&i.CommunicationTools,
		&i.CulturePreferences,
		&i.StrategicPriorities,
		&i.KeyRisks,
		&i.ManagementStyleWeights,
		&i.Countries,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE tenant_id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, tenantID)
	return err
}

const getOrganizationByTenant = `-- name: GetOrganizationByTenant :one
SELECT id, tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, plan_version, status, created_at, updated_at, management_pain_points, current_projects, target_framework, team_structure, communication_tools, culture_preferences, strategic_priorities, key_risks, management_style_weights, countries FROM organizations WHERE tenant_id = $1
`

func (q *Queries) GetOrganizationByTenant(ctx context.Context, tenantID pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByTenant, tenantID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Industry,
		&i.Size,
		&i.Stage,
		&i.BusinessModel,
		&i.Region,
		&i.MentorID,
		&i.ManagementPlan,
		&i.PlanVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagementPainPoints,
		&i.CurrentProjects,
		&i.TargetFramework,
		&i.TeamStructure,
		&i.CommunicationTools,
		&i.CulturePreferences,
		&i.StrategicPriorities,
		&i.KeyRisks,
		&i.ManagementStyleWeights,
		&i.Countries,
	)
	return i, err
}

const updateOrganizationContext = `-- name: UpdateOrganizationContext :exec
UPDATE organizations
SET
    strategic_priorities = COALESCE($2, strategic_priorities),
    key_risks            = COALESCE($3, key_risks),
    management_style_weights = COALESCE($4, management_style_weights),
    updated_at           = now()
WHERE tenant_id = $1
`

type UpdateOrganizationContextParams struct {
	TenantID               pgtype.UUID `json:"tenant_id"`
	StrategicPriorities    []byte      `json:"strategic_priorities"`
	KeyRisks               []byte      `json:"key_risks"`
	ManagementStyleWeights []byte      `json:"management_style_weights"`
}

func (q *Queries) UpdateOrganizationContext(ctx context.Context, arg UpdateOrganizationContextParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationContext,
		arg.TenantID,
		arg.StrategicPriorities,
		arg.KeyRisks,
		arg.ManagementStyleWeights,
	)
	return err
}

const updateOrganizationPlan = `-- name: UpdateOrganizationPlan :exec
UPDATE organizations SET management_plan = $2, plan_version = plan_version + 1, updated_at = now() WHERE tenant_id = $1
`

type UpdateOrganizationPlanParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ManagementPlan []byte      `json:"management_plan"`
}

func (q *Queries) UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationPlan, arg.TenantID, arg.ManagementPlan)
	return err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :exec
UPDATE organizations SET status = $2, updated_at = now() WHERE tenant_id = $1
`

type UpdateOrganizationStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationStatus, arg.TenantID, arg.Status)
	return err
}

const upsertOrganization = `-- name: UpsertOrganization :one
INSERT INTO organizations (
    tenant_id, industry, size, stage, business_model, mentor_id,
    management_plan, status, management_pain_points, current_projects,
    target_framework, team_structure, communication_tools, culture_preferences
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'draft', $8, $9, $10, $11, $12, $13
)
ON CONFLICT (tenant_id) DO UPDATE SET
    industry = EXCLUDED.industry,
    size = EXCLUDED.size,
    stage = EXCLUDED.stage,
    business_model = EXCLUDED.business_model,
    mentor_id = EXCLUDED.mentor_id,
    management_plan = EXCLUDED.management_plan,
    plan_version = organizations.plan_version + 1,
    status = 'draft',
    management_pain_points = EXCLUDED.management_pain_points,
    current_projects = EXCLUDED.current_projects,
    target_framework = EXCLUDED.target_framework,
    team_structure = EXCLUDED.team_structure,
    communication_tools = EXCLUDED.communication_tools,
    culture_preferences = EXCLUDED.culture_preferences,
    updated_at = NOW()
RETURNING id, tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, plan_version, status, created_at, updated_at, management_pain_points, current_projects, target_framework, team_structure, communication_tools, culture_preferences, strategic_priorities, key_risks, management_style_weights, countries
`

type UpsertOrganizationParams struct {
	TenantID             pgtype.UUID `json:"tenant_id"`
	Industry             pgtype.Text `json:"industry"`
	Size                 pgtype.Int4 `json:"size"`
	Stage                pgtype.Text `json:"stage"`
	BusinessModel        pgtype.Text `json:"business_model"`
	MentorID             string      `json:"mentor_id"`
	ManagementPlan       []byte      `json:"management_plan"`
	ManagementPainPoints []string    `json:"management_pain_points"`
	CurrentProjects      []byte      `json:"current_projects"`
	TargetFramework      pgtype.Text `json:"target_framework"`
	TeamStructure        []byte      `json:"team_structure"`
	CommunicationTools   []string    `json:"communication_tools"`
	CulturePreferences   []byte      `json:"culture_preferences"`
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, upsertOrganization,
		arg.TenantID,
		arg.Industry,
		arg.Size,
		arg.Stage,
		arg.BusinessModel,
		arg.MentorID,
		arg.ManagementPlan,
		arg.ManagementPainPoints,
		arg.CurrentProjects,
		arg.TargetFramework,
		arg.TeamStructure,
		arg.CommunicationTools,
		arg.CulturePreferences,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Industry,
		&i.Size,
		&i.Stage,
		&i.BusinessModel,
		&i.Region,
		&i.MentorID,
		&i.ManagementPlan,
		&i.PlanVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManagementPainPoints,
		&i.CurrentProjects,
		&i.TargetFramework,
		&i.TeamStructure,
		&i.CommunicationTools,
		&i.CulturePreferences,
		&i.StrategicPriorities,
		&i.KeyRisks,
		&i.ManagementStyleWeights,
		&i.Countries,
	)
	return i, err
}
