// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, plan_version, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Industry       string      `json:"industry"`
	Size           int32       `json:"size"`
	Stage          string      `json:"stage"`
	BusinessModel  pgtype.Text `json:"business_model"`
	Region         pgtype.Text `json:"region"`
	MentorID       string      `json:"mentor_id"`
	ManagementPlan []byte      `json:"management_plan"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.TenantID,
		arg.Industry,
		arg.Size,
		arg.Stage,
		arg.BusinessModel,
		arg.Region,
		arg.MentorID,
		arg.ManagementPlan,
		arg.Status,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Industry,
		&i.Size,
		&i.Stage,
		&i.BusinessModel,
		&i.Region,
		&i.MentorID,
		&i.ManagementPlan,
		&i.PlanVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE tenant_id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, tenantID)
	return err
}

const getOrganizationByTenant = `-- name: GetOrganizationByTenant :one
SELECT id, tenant_id, industry, size, stage, business_model, region, mentor_id, management_plan, plan_version, status, created_at, updated_at FROM organizations WHERE tenant_id = $1
`

func (q *Queries) GetOrganizationByTenant(ctx context.Context, tenantID pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByTenant, tenantID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Industry,
		&i.Size,
		&i.Stage,
		&i.BusinessModel,
		&i.Region,
		&i.MentorID,
		&i.ManagementPlan,
		&i.PlanVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationPlan = `-- name: UpdateOrganizationPlan :exec
UPDATE organizations SET management_plan = $2, plan_version = plan_version + 1, updated_at = now() WHERE tenant_id = $1
`

type UpdateOrganizationPlanParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ManagementPlan []byte      `json:"management_plan"`
}

func (q *Queries) UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationPlan, arg.TenantID, arg.ManagementPlan)
	return err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :exec
UPDATE organizations SET status = $2, updated_at = now() WHERE tenant_id = $1
`

type UpdateOrganizationStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationStatus, arg.TenantID, arg.Status)
	return err
}
