// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (tenant_id, name, description, owner_id, owner_team_id,
  status, priority, linked_goal_ids, linked_metric_ids, source_system, source_ref,
  start_date, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, name, description, owner_id, owner_team_id, status, priority, linked_goal_ids, linked_metric_ids, blockers, source_system, source_ref, start_date, due_date, created_at, updated_at, external_id, external_source, external_url
`

type CreateProjectParams struct {
	TenantID        pgtype.UUID `json:"tenant_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	OwnerID         pgtype.UUID `json:"owner_id"`
	OwnerTeamID     pgtype.UUID `json:"owner_team_id"`
	Status          string      `json:"status"`
	Priority        string      `json:"priority"`
	LinkedGoalIds   []byte      `json:"linked_goal_ids"`
	LinkedMetricIds []byte      `json:"linked_metric_ids"`
	SourceSystem    pgtype.Text `json:"source_system"`
	SourceRef       pgtype.Text `json:"source_ref"`
	StartDate       pgtype.Date `json:"start_date"`
	DueDate         pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.OwnerTeamID,
		arg.Status,
		arg.Priority,
		arg.LinkedGoalIds,
		arg.LinkedMetricIds,
		arg.SourceSystem,
		arg.SourceRef,
		arg.StartDate,
		arg.DueDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.LinkedGoalIds,
		&i.LinkedMetricIds,
		&i.Blockers,
		&i.SourceSystem,
		&i.SourceRef,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, tenant_id, name, description, owner_id, owner_team_id, status, priority, linked_goal_ids, linked_metric_ids, blockers, source_system, source_ref, start_date, due_date, created_at, updated_at, external_id, external_source, external_url FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.LinkedGoalIds,
		&i.LinkedMetricIds,
		&i.Blockers,
		&i.SourceSystem,
		&i.SourceRef,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const listBlockedProjects = `-- name: ListBlockedProjects :many
SELECT id, tenant_id, name, description, owner_id, owner_team_id, status, priority, linked_goal_ids, linked_metric_ids, blockers, source_system, source_ref, start_date, due_date, created_at, updated_at, external_id, external_source, external_url FROM projects
WHERE tenant_id = $1 AND status = 'blocked'
ORDER BY priority, created_at
`

func (q *Queries) ListBlockedProjects(ctx context.Context, tenantID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listBlockedProjects, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Status,
			&i.Priority,
			&i.LinkedGoalIds,
			&i.LinkedMetricIds,
			&i.Blockers,
			&i.SourceSystem,
			&i.SourceRef,
			&i.StartDate,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.tenant_id, p.name, p.description, p.owner_id, p.owner_team_id, p.status, p.priority, p.linked_goal_ids, p.linked_metric_ids, p.blockers, p.source_system, p.source_ref, p.start_date, p.due_date, p.created_at, p.updated_at, p.external_id, p.external_source, p.external_url,
  e.name AS owner_name,
  ou.name AS team_name
FROM projects p
LEFT JOIN employees e ON p.owner_id = e.id
LEFT JOIN org_units ou ON p.owner_team_id = ou.id
WHERE p.tenant_id = $1
ORDER BY p.created_at DESC
`

type ListProjectsRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	OwnerTeamID     pgtype.UUID        `json:"owner_team_id"`
	Status          string             `json:"status"`
	Priority        string             `json:"priority"`
	LinkedGoalIds   []byte             `json:"linked_goal_ids"`
	LinkedMetricIds []byte             `json:"linked_metric_ids"`
	Blockers        []byte             `json:"blockers"`
	SourceSystem    pgtype.Text        `json:"source_system"`
	SourceRef       pgtype.Text        `json:"source_ref"`
	StartDate       pgtype.Date        `json:"start_date"`
	DueDate         pgtype.Date        `json:"due_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ExternalID      pgtype.Text        `json:"external_id"`
	ExternalSource  pgtype.Text        `json:"external_source"`
	ExternalUrl     pgtype.Text        `json:"external_url"`
	OwnerName       pgtype.Text        `json:"owner_name"`
	TeamName        pgtype.Text        `json:"team_name"`
}

func (q *Queries) ListProjects(ctx context.Context, tenantID pgtype.UUID) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Status,
			&i.Priority,
			&i.LinkedGoalIds,
			&i.LinkedMetricIds,
			&i.Blockers,
			&i.SourceSystem,
			&i.SourceRef,
			&i.StartDate,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
			&i.OwnerName,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
  name = $2, description = $3, status = $4, priority = $5,
  owner_id = $6, blockers = $7, due_date = $8, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, description, owner_id, owner_team_id, status, priority, linked_goal_ids, linked_metric_ids, blockers, source_system, source_ref, start_date, due_date, created_at, updated_at, external_id, external_source, external_url
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Blockers    []byte      `json:"blockers"`
	DueDate     pgtype.Date `json:"due_date"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.OwnerID,
		arg.Blockers,
		arg.DueDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.LinkedGoalIds,
		&i.LinkedMetricIds,
		&i.Blockers,
		&i.SourceSystem,
		&i.SourceRef,
		&i.StartDate,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const verifyProjectTenant = `-- name: VerifyProjectTenant :one
SELECT tenant_id FROM projects WHERE id = $1
`

func (q *Queries) VerifyProjectTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyProjectTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
