// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingRecommendations = `-- name: CountPendingRecommendations :one
SELECT count(*) FROM recommendations
WHERE tenant_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingRecommendations(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRecommendations, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO recommendations (
    tenant_id, category, priority, title, description,
    suggested_actions, evidence, source, target_entity_type,
    target_entity_id, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, category, priority, title, description, suggested_actions, evidence, source, status, target_entity_type, target_entity_id, expires_at, created_at, reviewed_at, executed_at
`

type CreateRecommendationParams struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Category         string             `json:"category"`
	Priority         string             `json:"priority"`
	Title            string             `json:"title"`
	Description      string             `json:"description"`
	SuggestedActions []byte             `json:"suggested_actions"`
	Evidence         []byte             `json:"evidence"`
	Source           string             `json:"source"`
	TargetEntityType pgtype.Text        `json:"target_entity_type"`
	TargetEntityID   pgtype.UUID        `json:"target_entity_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, createRecommendation,
		arg.TenantID,
		arg.Category,
		arg.Priority,
		arg.Title,
		arg.Description,
		arg.SuggestedActions,
		arg.Evidence,
		arg.Source,
		arg.TargetEntityType,
		arg.TargetEntityID,
		arg.ExpiresAt,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Category,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SuggestedActions,
		&i.Evidence,
		&i.Source,
		&i.Status,
		&i.TargetEntityType,
		&i.TargetEntityID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ExecutedAt,
	)
	return i, err
}

const deleteRecommendation = `-- name: DeleteRecommendation :exec
DELETE FROM recommendations
WHERE id = $1 AND tenant_id = $2 AND status IN ('dismissed', 'expired')
`

type DeleteRecommendationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRecommendation(ctx context.Context, arg DeleteRecommendationParams) error {
	_, err := q.db.Exec(ctx, deleteRecommendation, arg.ID, arg.TenantID)
	return err
}

const expireOldRecommendations = `-- name: ExpireOldRecommendations :exec
UPDATE recommendations
SET status = 'expired'
WHERE tenant_id = $1
  AND status = 'pending'
  AND expires_at < now()
`

func (q *Queries) ExpireOldRecommendations(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expireOldRecommendations, tenantID)
	return err
}

const findDuplicateOrgRecommendation = `-- name: FindDuplicateOrgRecommendation :one
SELECT id, priority FROM recommendations
WHERE tenant_id = $1
  AND category = $2
  AND target_entity_id IS NULL
  AND title = $3
  AND status = 'pending'
  AND created_at > now() - interval '72 hours'
LIMIT 1
`

type FindDuplicateOrgRecommendationParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Category string      `json:"category"`
	Title    string      `json:"title"`
}

type FindDuplicateOrgRecommendationRow struct {
	ID       pgtype.UUID `json:"id"`
	Priority string      `json:"priority"`
}

func (q *Queries) FindDuplicateOrgRecommendation(ctx context.Context, arg FindDuplicateOrgRecommendationParams) (FindDuplicateOrgRecommendationRow, error) {
	row := q.db.QueryRow(ctx, findDuplicateOrgRecommendation, arg.TenantID, arg.Category, arg.Title)
	var i FindDuplicateOrgRecommendationRow
	err := row.Scan(&i.ID, &i.Priority)
	return i, err
}

const findDuplicateRecommendation = `-- name: FindDuplicateRecommendation :one
SELECT id, priority FROM recommendations
WHERE tenant_id = $1
  AND category = $2
  AND target_entity_type IS NOT DISTINCT FROM $3
  AND target_entity_id IS NOT DISTINCT FROM $4
  AND status = 'pending'
  AND created_at > now() - interval '72 hours'
LIMIT 1
`

type FindDuplicateRecommendationParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Category         string      `json:"category"`
	TargetEntityType pgtype.Text `json:"target_entity_type"`
	TargetEntityID   pgtype.UUID `json:"target_entity_id"`
}

type FindDuplicateRecommendationRow struct {
	ID       pgtype.UUID `json:"id"`
	Priority string      `json:"priority"`
}

func (q *Queries) FindDuplicateRecommendation(ctx context.Context, arg FindDuplicateRecommendationParams) (FindDuplicateRecommendationRow, error) {
	row := q.db.QueryRow(ctx, findDuplicateRecommendation,
		arg.TenantID,
		arg.Category,
		arg.TargetEntityType,
		arg.TargetEntityID,
	)
	var i FindDuplicateRecommendationRow
	err := row.Scan(&i.ID, &i.Priority)
	return i, err
}

const getRecommendation = `-- name: GetRecommendation :one
SELECT id, tenant_id, category, priority, title, description, suggested_actions, evidence, source, status, target_entity_type, target_entity_id, expires_at, created_at, reviewed_at, executed_at FROM recommendations
WHERE id = $1 AND tenant_id = $2
`

type GetRecommendationParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetRecommendation(ctx context.Context, arg GetRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, getRecommendation, arg.ID, arg.TenantID)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Category,
		&i.Priority,
		&i.Title,
		&i.Description,
		&i.SuggestedActions,
		&i.Evidence,
		&i.Source,
		&i.Status,
		&i.TargetEntityType,
		&i.TargetEntityID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ExecutedAt,
	)
	return i, err
}

const getRecommendationSummary = `-- name: GetRecommendationSummary :many
SELECT id, tenant_id, category, priority, title, description, suggested_actions, evidence, source, status, target_entity_type, target_entity_id, expires_at, created_at, reviewed_at, executed_at FROM recommendations
WHERE tenant_id = $1 AND status = 'pending'
ORDER BY
  CASE priority
    WHEN 'critical' THEN 1
    WHEN 'high' THEN 2
    WHEN 'medium' THEN 3
    WHEN 'low' THEN 4
  END,
  created_at DESC
LIMIT 3
`

func (q *Queries) GetRecommendationSummary(ctx context.Context, tenantID pgtype.UUID) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, getRecommendationSummary, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recommendation{}
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Category,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.SuggestedActions,
			&i.Evidence,
			&i.Source,
			&i.Status,
			&i.TargetEntityType,
			&i.TargetEntityID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, mentor_id FROM tenants
`

type ListActiveTenantsRow struct {
	ID       pgtype.UUID `json:"id"`
	MentorID string      `json:"mentor_id"`
}

func (q *Queries) ListActiveTenants(ctx context.Context) ([]ListActiveTenantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTenantsRow{}
	for rows.Next() {
		var i ListActiveTenantsRow
		if err := rows.Scan(&i.ID, &i.MentorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendations = `-- name: ListRecommendations :many
SELECT id, tenant_id, category, priority, title, description, suggested_actions, evidence, source, status, target_entity_type, target_entity_id, expires_at, created_at, reviewed_at, executed_at FROM recommendations
WHERE tenant_id = $1
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR category = $3)
ORDER BY
  CASE priority
    WHEN 'critical' THEN 1
    WHEN 'high' THEN 2
    WHEN 'medium' THEN 3
    WHEN 'low' THEN 4
  END,
  created_at DESC
LIMIT $4 OFFSET $5
`

type ListRecommendationsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Column2  string      `json:"column_2"`
	Column3  string      `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListRecommendations(ctx context.Context, arg ListRecommendationsParams) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendations,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recommendation{}
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Category,
			&i.Priority,
			&i.Title,
			&i.Description,
			&i.SuggestedActions,
			&i.Evidence,
			&i.Source,
			&i.Status,
			&i.TargetEntityType,
			&i.TargetEntityID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecommendationStatus = `-- name: UpdateRecommendationStatus :exec
UPDATE recommendations
SET status = $3, reviewed_at = now(),
    executed_at = CASE WHEN $3 = 'executed' THEN now() ELSE executed_at END
WHERE id = $1 AND tenant_id = $2
`

type UpdateRecommendationStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateRecommendationStatus(ctx context.Context, arg UpdateRecommendationStatusParams) error {
	_, err := q.db.Exec(ctx, updateRecommendationStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}
