// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportsByEmployeeDate = `-- name: CountReportsByEmployeeDate :one
SELECT count(*) FROM reports WHERE employee_id = $1 AND report_date = $2
`

type CountReportsByEmployeeDateParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) CountReportsByEmployeeDate(ctx context.Context, arg CountReportsByEmployeeDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByEmployeeDate, arg.EmployeeID, arg.ReportDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReportsByTenantDate = `-- name: CountReportsByTenantDate :one
SELECT COUNT(*) FROM reports WHERE tenant_id = $1 AND report_date = $2
`

type CountReportsByTenantDateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) CountReportsByTenantDate(ctx context.Context, arg CountReportsByTenantDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByTenantDate, arg.TenantID, arg.ReportDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (tenant_id, employee_id, report_date, answers, blockers, sentiment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, employee_id, report_date, answers, blockers, sentiment, submitted_at
`

type CreateReportParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
	Answers    []byte      `json:"answers"`
	Blockers   pgtype.Text `json:"blockers"`
	Sentiment  pgtype.Text `json:"sentiment"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TenantID,
		arg.EmployeeID,
		arg.ReportDate,
		arg.Answers,
		arg.Blockers,
		arg.Sentiment,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ReportDate,
		&i.Answers,
		&i.Blockers,
		&i.Sentiment,
		&i.SubmittedAt,
	)
	return i, err
}

const getConsecutiveMissDays = `-- name: GetConsecutiveMissDays :one
SELECT COUNT(*) as missed_days FROM generate_series(
    CURRENT_DATE - INTERVAL '7 days', CURRENT_DATE - INTERVAL '1 day', '1 day'
) d(day)
WHERE d.day::date NOT IN (
    SELECT r.report_date FROM reports r WHERE r.employee_id = $1 AND r.report_date >= CURRENT_DATE - INTERVAL '7 days'
)
AND d.day::date >= (
    COALESCE(
        (SELECT MAX(r2.report_date) FROM reports r2 WHERE r2.employee_id = $1 AND r2.report_date >= CURRENT_DATE - INTERVAL '7 days'),
        CURRENT_DATE - INTERVAL '7 days'
    )
)
`

func (q *Queries) GetConsecutiveMissDays(ctx context.Context, employeeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getConsecutiveMissDays, employeeID)
	var missed_days int64
	err := row.Scan(&missed_days)
	return missed_days, err
}

const getEmployeeReportStreak = `-- name: GetEmployeeReportStreak :one
SELECT COUNT(*) as missed_days FROM generate_series(
    CURRENT_DATE - INTERVAL '7 days', CURRENT_DATE - INTERVAL '1 day', '1 day'
) d(day)
WHERE NOT EXISTS (
    SELECT 1 FROM reports WHERE employee_id = $1 AND report_date = d.day::date
)
`

func (q *Queries) GetEmployeeReportStreak(ctx context.Context, employeeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEmployeeReportStreak, employeeID)
	var missed_days int64
	err := row.Scan(&missed_days)
	return missed_days, err
}

const getEmployeeSubmissionHistory = `-- name: GetEmployeeSubmissionHistory :many
SELECT report_date, sentiment FROM reports
WHERE employee_id = $1 AND report_date >= CURRENT_DATE - INTERVAL '30 days'
ORDER BY report_date DESC
`

type GetEmployeeSubmissionHistoryRow struct {
	ReportDate pgtype.Date `json:"report_date"`
	Sentiment  pgtype.Text `json:"sentiment"`
}

func (q *Queries) GetEmployeeSubmissionHistory(ctx context.Context, employeeID pgtype.UUID) ([]GetEmployeeSubmissionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeSubmissionHistory, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeeSubmissionHistoryRow{}
	for rows.Next() {
		var i GetEmployeeSubmissionHistoryRow
		if err := rows.Scan(&i.ReportDate, &i.Sentiment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestReportByEmployee = `-- name: GetLatestReportByEmployee :one
SELECT id, tenant_id, employee_id, report_date, answers, blockers, sentiment, submitted_at FROM reports
WHERE employee_id = $1 AND report_date = $2
ORDER BY submitted_at DESC LIMIT 1
`

type GetLatestReportByEmployeeParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) GetLatestReportByEmployee(ctx context.Context, arg GetLatestReportByEmployeeParams) (Report, error) {
	row := q.db.QueryRow(ctx, getLatestReportByEmployee, arg.EmployeeID, arg.ReportDate)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ReportDate,
		&i.Answers,
		&i.Blockers,
		&i.Sentiment,
		&i.SubmittedAt,
	)
	return i, err
}

const getRecentSentiments = `-- name: GetRecentSentiments :many
SELECT sentiment FROM reports
WHERE employee_id = $1 AND sentiment IS NOT NULL
AND report_date >= CURRENT_DATE - INTERVAL '7 days'
ORDER BY report_date DESC
LIMIT $2
`

type GetRecentSentimentsParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) GetRecentSentiments(ctx context.Context, arg GetRecentSentimentsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getRecentSentiments, arg.EmployeeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var sentiment pgtype.Text
		if err := rows.Scan(&sentiment); err != nil {
			return nil, err
		}
		items = append(items, sentiment)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReportsByTenantDate = `-- name: GetReportsByTenantDate :many
SELECT r.id, r.tenant_id, r.employee_id, r.report_date, r.answers, r.blockers, r.sentiment, r.submitted_at, e.name as employee_name FROM reports r
JOIN employees e ON r.employee_id = e.id
WHERE r.tenant_id = $1 AND r.report_date = $2
ORDER BY r.submitted_at
`

type GetReportsByTenantDateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

type GetReportsByTenantDateRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	ReportDate   pgtype.Date        `json:"report_date"`
	Answers      []byte             `json:"answers"`
	Blockers     pgtype.Text        `json:"blockers"`
	Sentiment    pgtype.Text        `json:"sentiment"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) GetReportsByTenantDate(ctx context.Context, arg GetReportsByTenantDateParams) ([]GetReportsByTenantDateRow, error) {
	rows, err := q.db.Query(ctx, getReportsByTenantDate, arg.TenantID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReportsByTenantDateRow{}
	for rows.Next() {
		var i GetReportsByTenantDateRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ReportDate,
			&i.Answers,
			&i.Blockers,
			&i.Sentiment,
			&i.SubmittedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubmittedDaysLast7 = `-- name: GetSubmittedDaysLast7 :one
SELECT COUNT(DISTINCT report_date) FROM reports
WHERE employee_id = $1 AND report_date >= CURRENT_DATE - INTERVAL '7 days'
`

func (q *Queries) GetSubmittedDaysLast7(ctx context.Context, employeeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSubmittedDaysLast7, employeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateReportAnalysis = `-- name: UpdateReportAnalysis :exec
UPDATE reports SET blockers = $2, sentiment = $3
WHERE id = $1
`

type UpdateReportAnalysisParams struct {
	ID        pgtype.UUID `json:"id"`
	Blockers  pgtype.Text `json:"blockers"`
	Sentiment pgtype.Text `json:"sentiment"`
}

func (q *Queries) UpdateReportAnalysis(ctx context.Context, arg UpdateReportAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateReportAnalysis, arg.ID, arg.Blockers, arg.Sentiment)
	return err
}
