// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reporting_lines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReportingLine = `-- name: CreateReportingLine :one
INSERT INTO reporting_lines (tenant_id, manager_id, report_id, relationship_type)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, manager_id, report_id, relationship_type, created_at
`

type CreateReportingLineParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	ManagerID        pgtype.UUID `json:"manager_id"`
	ReportID         pgtype.UUID `json:"report_id"`
	RelationshipType string      `json:"relationship_type"`
}

func (q *Queries) CreateReportingLine(ctx context.Context, arg CreateReportingLineParams) (ReportingLine, error) {
	row := q.db.QueryRow(ctx, createReportingLine,
		arg.TenantID,
		arg.ManagerID,
		arg.ReportID,
		arg.RelationshipType,
	)
	var i ReportingLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ManagerID,
		&i.ReportID,
		&i.RelationshipType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReportingLine = `-- name: DeleteReportingLine :exec
DELETE FROM reporting_lines WHERE id = $1
`

func (q *Queries) DeleteReportingLine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReportingLine, id)
	return err
}

const getDirectReports = `-- name: GetDirectReports :many
SELECT e.id, e.tenant_id, e.name, e.telegram_id, e.culture_code, e.role, e.invite_code, e.is_active, e.created_at, e.signal_phone, e.slack_id, e.lark_id, e.preferred_channel, e.job_title, e.responsibilities, e.country, e.language, e.org_unit_id, e.execution_score, e.current_load, e.strengths, e.risk_flags, e.work_scope, e.halaos_employee_id, e.halaos_employee_no FROM employees e
JOIN reporting_lines rl ON rl.report_id = e.id
WHERE rl.manager_id = $1 AND rl.relationship_type = 'direct'
ORDER BY e.name
`

func (q *Queries) GetDirectReports(ctx context.Context, managerID pgtype.UUID) ([]Employee, error) {
	rows, err := q.db.Query(ctx, getDirectReports, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TelegramID,
			&i.CultureCode,
			&i.Role,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.SignalPhone,
			&i.SlackID,
			&i.LarkID,
			&i.PreferredChannel,
			&i.JobTitle,
			&i.Responsibilities,
			&i.Country,
			&i.Language,
			&i.OrgUnitID,
			&i.ExecutionScore,
			&i.CurrentLoad,
			&i.Strengths,
			&i.RiskFlags,
			&i.WorkScope,
			&i.HalaosEmployeeID,
			&i.HalaosEmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getManager = `-- name: GetManager :one
SELECT e.id, e.tenant_id, e.name, e.telegram_id, e.culture_code, e.role, e.invite_code, e.is_active, e.created_at, e.signal_phone, e.slack_id, e.lark_id, e.preferred_channel, e.job_title, e.responsibilities, e.country, e.language, e.org_unit_id, e.execution_score, e.current_load, e.strengths, e.risk_flags, e.work_scope, e.halaos_employee_id, e.halaos_employee_no FROM employees e
JOIN reporting_lines rl ON rl.manager_id = e.id
WHERE rl.report_id = $1 AND rl.relationship_type = 'direct'
LIMIT 1
`

func (q *Queries) GetManager(ctx context.Context, reportID pgtype.UUID) (Employee, error) {
	row := q.db.QueryRow(ctx, getManager, reportID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TelegramID,
		&i.CultureCode,
		&i.Role,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.SignalPhone,
		&i.SlackID,
		&i.LarkID,
		&i.PreferredChannel,
		&i.JobTitle,
		&i.Responsibilities,
		&i.Country,
		&i.Language,
		&i.OrgUnitID,
		&i.ExecutionScore,
		&i.CurrentLoad,
		&i.Strengths,
		&i.RiskFlags,
		&i.WorkScope,
		&i.HalaosEmployeeID,
		&i.HalaosEmployeeNo,
	)
	return i, err
}

const listReportingLines = `-- name: ListReportingLines :many
SELECT rl.id, rl.tenant_id, rl.manager_id, rl.report_id, rl.relationship_type, rl.created_at,
  mgr.name AS manager_name,
  rpt.name AS report_name
FROM reporting_lines rl
JOIN employees mgr ON rl.manager_id = mgr.id
JOIN employees rpt ON rl.report_id = rpt.id
WHERE rl.tenant_id = $1
ORDER BY mgr.name, rpt.name
`

type ListReportingLinesRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ManagerID        pgtype.UUID        `json:"manager_id"`
	ReportID         pgtype.UUID        `json:"report_id"`
	RelationshipType string             `json:"relationship_type"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ManagerName      string             `json:"manager_name"`
	ReportName       string             `json:"report_name"`
}

func (q *Queries) ListReportingLines(ctx context.Context, tenantID pgtype.UUID) ([]ListReportingLinesRow, error) {
	rows, err := q.db.Query(ctx, listReportingLines, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportingLinesRow{}
	for rows.Next() {
		var i ListReportingLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ManagerID,
			&i.ReportID,
			&i.RelationshipType,
			&i.CreatedAt,
			&i.ManagerName,
			&i.ReportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyReportingLineTenant = `-- name: VerifyReportingLineTenant :one
SELECT tenant_id FROM reporting_lines WHERE id = $1
`

func (q *Queries) VerifyReportingLineTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyReportingLineTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
