// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportsByTenantDate = `-- name: CountReportsByTenantDate :one
SELECT COUNT(*) FROM reports WHERE tenant_id = $1 AND report_date = $2
`

type CountReportsByTenantDateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

func (q *Queries) CountReportsByTenantDate(ctx context.Context, arg CountReportsByTenantDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByTenantDate, arg.TenantID, arg.ReportDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (tenant_id, employee_id, report_date, answers, blockers, sentiment)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, employee_id, report_date, answers, blockers, sentiment, submitted_at
`

type CreateReportParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReportDate pgtype.Date `json:"report_date"`
	Answers    []byte      `json:"answers"`
	Blockers   pgtype.Text `json:"blockers"`
	Sentiment  pgtype.Text `json:"sentiment"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.TenantID,
		arg.EmployeeID,
		arg.ReportDate,
		arg.Answers,
		arg.Blockers,
		arg.Sentiment,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.ReportDate,
		&i.Answers,
		&i.Blockers,
		&i.Sentiment,
		&i.SubmittedAt,
	)
	return i, err
}

const getEmployeeReportStreak = `-- name: GetEmployeeReportStreak :one
SELECT COUNT(*) as missed_days FROM generate_series(
    CURRENT_DATE - INTERVAL '7 days', CURRENT_DATE - INTERVAL '1 day', '1 day'
) d(day)
WHERE NOT EXISTS (
    SELECT 1 FROM reports WHERE employee_id = $1 AND report_date = d.day::date
)
`

func (q *Queries) GetEmployeeReportStreak(ctx context.Context, employeeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getEmployeeReportStreak, employeeID)
	var missed_days int64
	err := row.Scan(&missed_days)
	return missed_days, err
}

const getReportsByTenantDate = `-- name: GetReportsByTenantDate :many
SELECT r.id, r.tenant_id, r.employee_id, r.report_date, r.answers, r.blockers, r.sentiment, r.submitted_at, e.name as employee_name FROM reports r
JOIN employees e ON r.employee_id = e.id
WHERE r.tenant_id = $1 AND r.report_date = $2
ORDER BY r.submitted_at
`

type GetReportsByTenantDateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ReportDate pgtype.Date `json:"report_date"`
}

type GetReportsByTenantDateRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	ReportDate   pgtype.Date        `json:"report_date"`
	Answers      []byte             `json:"answers"`
	Blockers     pgtype.Text        `json:"blockers"`
	Sentiment    pgtype.Text        `json:"sentiment"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) GetReportsByTenantDate(ctx context.Context, arg GetReportsByTenantDateParams) ([]GetReportsByTenantDateRow, error) {
	rows, err := q.db.Query(ctx, getReportsByTenantDate, arg.TenantID, arg.ReportDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReportsByTenantDateRow{}
	for rows.Next() {
		var i GetReportsByTenantDateRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.ReportDate,
			&i.Answers,
			&i.Blockers,
			&i.Sentiment,
			&i.SubmittedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
