// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
INSERT INTO performance_reviews (cycle_id, employee_id, reviewer_id)
VALUES ($1, $2, $3)
RETURNING id, cycle_id, employee_id, reviewer_id, status, self_rating, manager_rating, self_summary, manager_summary, strengths, improvements, submitted_at, acknowledged_at, created_at, updated_at
`

type CreateReviewParams struct {
	CycleID    pgtype.UUID `json:"cycle_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	ReviewerID pgtype.UUID `json:"reviewer_id"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, createReview, arg.CycleID, arg.EmployeeID, arg.ReviewerID)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.ManagerRating,
		&i.SelfSummary,
		&i.ManagerSummary,
		&i.Strengths,
		&i.Improvements,
		&i.SubmittedAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewCycle = `-- name: CreateReviewCycle :one
INSERT INTO review_cycles (tenant_id, title, period, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, title, period, status, start_date, end_date, created_at, updated_at
`

type CreateReviewCycleParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Title     string      `json:"title"`
	Period    string      `json:"period"`
	Status    string      `json:"status"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateReviewCycle(ctx context.Context, arg CreateReviewCycleParams) (ReviewCycle, error) {
	row := q.db.QueryRow(ctx, createReviewCycle,
		arg.TenantID,
		arg.Title,
		arg.Period,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i ReviewCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Period,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM performance_reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const deleteReviewCycle = `-- name: DeleteReviewCycle :exec
DELETE FROM review_cycles WHERE id = $1 AND tenant_id = $2
`

type DeleteReviewCycleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteReviewCycle(ctx context.Context, arg DeleteReviewCycleParams) error {
	_, err := q.db.Exec(ctx, deleteReviewCycle, arg.ID, arg.TenantID)
	return err
}

const getReview = `-- name: GetReview :one
SELECT pr.id, pr.cycle_id, pr.employee_id, pr.reviewer_id, pr.status, pr.self_rating, pr.manager_rating, pr.self_summary, pr.manager_summary, pr.strengths, pr.improvements, pr.submitted_at, pr.acknowledged_at, pr.created_at, pr.updated_at, e.name AS employee_name
FROM performance_reviews pr
JOIN employees e ON e.id = pr.employee_id
WHERE pr.id = $1
`

type GetReviewRow struct {
	ID             pgtype.UUID        `json:"id"`
	CycleID        pgtype.UUID        `json:"cycle_id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	ReviewerID     pgtype.UUID        `json:"reviewer_id"`
	Status         string             `json:"status"`
	SelfRating     pgtype.Int2        `json:"self_rating"`
	ManagerRating  pgtype.Int2        `json:"manager_rating"`
	SelfSummary    string             `json:"self_summary"`
	ManagerSummary string             `json:"manager_summary"`
	Strengths      string             `json:"strengths"`
	Improvements   string             `json:"improvements"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EmployeeName   string             `json:"employee_name"`
}

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.CycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.ManagerRating,
		&i.SelfSummary,
		&i.ManagerSummary,
		&i.Strengths,
		&i.Improvements,
		&i.SubmittedAt,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeName,
	)
	return i, err
}

const getReviewCycle = `-- name: GetReviewCycle :one
SELECT id, tenant_id, title, period, status, start_date, end_date, created_at, updated_at FROM review_cycles
WHERE id = $1 AND tenant_id = $2
`

type GetReviewCycleParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetReviewCycle(ctx context.Context, arg GetReviewCycleParams) (ReviewCycle, error) {
	row := q.db.QueryRow(ctx, getReviewCycle, arg.ID, arg.TenantID)
	var i ReviewCycle
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Period,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewCycles = `-- name: ListReviewCycles :many
SELECT id, tenant_id, title, period, status, start_date, end_date, created_at, updated_at FROM review_cycles
WHERE tenant_id = $1
ORDER BY start_date DESC
`

func (q *Queries) ListReviewCycles(ctx context.Context, tenantID pgtype.UUID) ([]ReviewCycle, error) {
	rows, err := q.db.Query(ctx, listReviewCycles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewCycle{}
	for rows.Next() {
		var i ReviewCycle
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Period,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByCycle = `-- name: ListReviewsByCycle :many
SELECT pr.id, pr.cycle_id, pr.employee_id, pr.reviewer_id, pr.status, pr.self_rating, pr.manager_rating, pr.self_summary, pr.manager_summary, pr.strengths, pr.improvements, pr.submitted_at, pr.acknowledged_at, pr.created_at, pr.updated_at, e.name AS employee_name, r.name AS reviewer_name
FROM performance_reviews pr
JOIN employees e ON e.id = pr.employee_id
LEFT JOIN employees r ON r.id = pr.reviewer_id
WHERE pr.cycle_id = $1
ORDER BY e.name
`

type ListReviewsByCycleRow struct {
	ID             pgtype.UUID        `json:"id"`
	CycleID        pgtype.UUID        `json:"cycle_id"`
	EmployeeID     pgtype.UUID        `json:"employee_id"`
	ReviewerID     pgtype.UUID        `json:"reviewer_id"`
	Status         string             `json:"status"`
	SelfRating     pgtype.Int2        `json:"self_rating"`
	ManagerRating  pgtype.Int2        `json:"manager_rating"`
	SelfSummary    string             `json:"self_summary"`
	ManagerSummary string             `json:"manager_summary"`
	Strengths      string             `json:"strengths"`
	Improvements   string             `json:"improvements"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	EmployeeName   string             `json:"employee_name"`
	ReviewerName   pgtype.Text        `json:"reviewer_name"`
}

func (q *Queries) ListReviewsByCycle(ctx context.Context, cycleID pgtype.UUID) ([]ListReviewsByCycleRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByCycleRow{}
	for rows.Next() {
		var i ListReviewsByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.EmployeeID,
			&i.ReviewerID,
			&i.Status,
			&i.SelfRating,
			&i.ManagerRating,
			&i.SelfSummary,
			&i.ManagerSummary,
			&i.Strengths,
			&i.Improvements,
			&i.SubmittedAt,
			&i.AcknowledgedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeName,
			&i.ReviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE performance_reviews
SET status = $2, self_rating = $3, manager_rating = $4,
    self_summary = $5, manager_summary = $6,
    strengths = $7, improvements = $8,
    submitted_at = CASE WHEN $2 = 'submitted' THEN now() ELSE submitted_at END,
    acknowledged_at = CASE WHEN $2 = 'acknowledged' THEN now() ELSE acknowledged_at END,
    updated_at = now()
WHERE id = $1
`

type UpdateReviewParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	SelfRating     pgtype.Int2 `json:"self_rating"`
	ManagerRating  pgtype.Int2 `json:"manager_rating"`
	SelfSummary    string      `json:"self_summary"`
	ManagerSummary string      `json:"manager_summary"`
	Strengths      string      `json:"strengths"`
	Improvements   string      `json:"improvements"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.Exec(ctx, updateReview,
		arg.ID,
		arg.Status,
		arg.SelfRating,
		arg.ManagerRating,
		arg.SelfSummary,
		arg.ManagerSummary,
		arg.Strengths,
		arg.Improvements,
	)
	return err
}

const updateReviewCycle = `-- name: UpdateReviewCycle :exec
UPDATE review_cycles
SET title = $3, status = $4, start_date = $5, end_date = $6, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateReviewCycleParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Title     string      `json:"title"`
	Status    string      `json:"status"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateReviewCycle(ctx context.Context, arg UpdateReviewCycleParams) error {
	_, err := q.db.Exec(ctx, updateReviewCycle,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const verifyReviewCycleTenant = `-- name: VerifyReviewCycleTenant :one
SELECT tenant_id FROM review_cycles WHERE id = $1
`

func (q *Queries) VerifyReviewCycleTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyReviewCycleTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
