// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeat = `-- name: CreateSeat :one
INSERT INTO seats (tenant_id, seat_type, title, persona_id, scope)
VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at
`

type CreateSeatParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	SeatType  string      `json:"seat_type"`
	Title     string      `json:"title"`
	PersonaID string      `json:"persona_id"`
	Scope     string      `json:"scope"`
}

func (q *Queries) CreateSeat(ctx context.Context, arg CreateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, createSeat,
		arg.TenantID,
		arg.SeatType,
		arg.Title,
		arg.PersonaID,
		arg.Scope,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SeatType,
		&i.Title,
		&i.PersonaID,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeat = `-- name: DeleteSeat :exec
DELETE FROM seats WHERE id = $1
`

func (q *Queries) DeleteSeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSeat, id)
	return err
}

const getSeatByID = `-- name: GetSeatByID :one
SELECT id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at FROM seats WHERE id = $1
`

func (q *Queries) GetSeatByID(ctx context.Context, id pgtype.UUID) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByID, id)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SeatType,
		&i.Title,
		&i.PersonaID,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatByType = `-- name: GetSeatByType :one
SELECT id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at FROM seats WHERE tenant_id = $1 AND seat_type = $2
`

type GetSeatByTypeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SeatType string      `json:"seat_type"`
}

func (q *Queries) GetSeatByType(ctx context.Context, arg GetSeatByTypeParams) (Seat, error) {
	row := q.db.QueryRow(ctx, getSeatByType, arg.TenantID, arg.SeatType)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SeatType,
		&i.Title,
		&i.PersonaID,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSeatsByTenant = `-- name: ListActiveSeatsByTenant :many
SELECT id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at FROM seats WHERE tenant_id = $1 AND is_active = true ORDER BY seat_type
`

func (q *Queries) ListActiveSeatsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listActiveSeatsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SeatType,
			&i.Title,
			&i.PersonaID,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsByTenant = `-- name: ListSeatsByTenant :many
SELECT id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at FROM seats WHERE tenant_id = $1 ORDER BY seat_type
`

func (q *Queries) ListSeatsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listSeatsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SeatType,
			&i.Title,
			&i.PersonaID,
			&i.Scope,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeat = `-- name: UpdateSeat :one
UPDATE seats SET title = $2, persona_id = $3, scope = $4, updated_at = now()
WHERE id = $1 RETURNING id, tenant_id, seat_type, title, persona_id, scope, is_active, created_at, updated_at
`

type UpdateSeatParams struct {
	ID        pgtype.UUID `json:"id"`
	Title     string      `json:"title"`
	PersonaID string      `json:"persona_id"`
	Scope     string      `json:"scope"`
}

func (q *Queries) UpdateSeat(ctx context.Context, arg UpdateSeatParams) (Seat, error) {
	row := q.db.QueryRow(ctx, updateSeat,
		arg.ID,
		arg.Title,
		arg.PersonaID,
		arg.Scope,
	)
	var i Seat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SeatType,
		&i.Title,
		&i.PersonaID,
		&i.Scope,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
