// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (tenant_id, name, category, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, category, description, created_at
`

type CreateSkillParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.Description,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployeeSkill = `-- name: DeleteEmployeeSkill :exec
DELETE FROM employee_skills WHERE employee_id = $1 AND skill_id = $2
`

type DeleteEmployeeSkillParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	SkillID    pgtype.UUID `json:"skill_id"`
}

func (q *Queries) DeleteEmployeeSkill(ctx context.Context, arg DeleteEmployeeSkillParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeeSkill, arg.EmployeeID, arg.SkillID)
	return err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1 AND tenant_id = $2
`

type DeleteSkillParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.TenantID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, tenant_id, name, category, description, created_at FROM skills WHERE id = $1 AND tenant_id = $2
`

type GetSkillParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.TenantID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillMatrix = `-- name: GetSkillMatrix :many
SELECT e.id AS employee_id, e.name AS employee_name,
       s.id AS skill_id, s.name AS skill_name, s.category,
       COALESCE(es.level, 0)::int AS level
FROM employees e
CROSS JOIN skills s
LEFT JOIN employee_skills es ON es.employee_id = e.id AND es.skill_id = s.id
WHERE e.tenant_id = $1 AND s.tenant_id = $1 AND e.is_active = true
ORDER BY e.name, s.category, s.name
`

type GetSkillMatrixRow struct {
	EmployeeID   pgtype.UUID `json:"employee_id"`
	EmployeeName string      `json:"employee_name"`
	SkillID      pgtype.UUID `json:"skill_id"`
	SkillName    string      `json:"skill_name"`
	Category     string      `json:"category"`
	Level        int32       `json:"level"`
}

func (q *Queries) GetSkillMatrix(ctx context.Context, tenantID pgtype.UUID) ([]GetSkillMatrixRow, error) {
	rows, err := q.db.Query(ctx, getSkillMatrix, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSkillMatrixRow{}
	for rows.Next() {
		var i GetSkillMatrixRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeName,
			&i.SkillID,
			&i.SkillName,
			&i.Category,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeSkills = `-- name: ListEmployeeSkills :many
SELECT es.id, es.employee_id, es.skill_id, es.level, es.notes, es.assessed_at, es.created_at, s.name AS skill_name, s.category AS skill_category
FROM employee_skills es
JOIN skills s ON s.id = es.skill_id
WHERE es.employee_id = $1
ORDER BY s.category, s.name
`

type ListEmployeeSkillsRow struct {
	ID            pgtype.UUID        `json:"id"`
	EmployeeID    pgtype.UUID        `json:"employee_id"`
	SkillID       pgtype.UUID        `json:"skill_id"`
	Level         int16              `json:"level"`
	Notes         string             `json:"notes"`
	AssessedAt    pgtype.Timestamptz `json:"assessed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SkillName     string             `json:"skill_name"`
	SkillCategory string             `json:"skill_category"`
}

func (q *Queries) ListEmployeeSkills(ctx context.Context, employeeID pgtype.UUID) ([]ListEmployeeSkillsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeSkills, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeSkillsRow{}
	for rows.Next() {
		var i ListEmployeeSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.SkillID,
			&i.Level,
			&i.Notes,
			&i.AssessedAt,
			&i.CreatedAt,
			&i.SkillName,
			&i.SkillCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT s.id, s.tenant_id, s.name, s.category, s.description, s.created_at, COUNT(es.id)::int AS employee_count
FROM skills s
LEFT JOIN employee_skills es ON es.skill_id = s.id
WHERE s.tenant_id = $1
GROUP BY s.id
ORDER BY s.category, s.name
`

type ListSkillsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	Description   string             `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EmployeeCount int32              `json:"employee_count"`
}

func (q *Queries) ListSkills(ctx context.Context, tenantID pgtype.UUID) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsRow{}
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
			&i.EmployeeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmployeeSkill = `-- name: SetEmployeeSkill :one
INSERT INTO employee_skills (employee_id, skill_id, level, notes, assessed_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (employee_id, skill_id)
DO UPDATE SET level = EXCLUDED.level, notes = EXCLUDED.notes, assessed_at = now()
RETURNING id, employee_id, skill_id, level, notes, assessed_at, created_at
`

type SetEmployeeSkillParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	SkillID    pgtype.UUID `json:"skill_id"`
	Level      int16       `json:"level"`
	Notes      string      `json:"notes"`
}

func (q *Queries) SetEmployeeSkill(ctx context.Context, arg SetEmployeeSkillParams) (EmployeeSkill, error) {
	row := q.db.QueryRow(ctx, setEmployeeSkill,
		arg.EmployeeID,
		arg.SkillID,
		arg.Level,
		arg.Notes,
	)
	var i EmployeeSkill
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.SkillID,
		&i.Level,
		&i.Notes,
		&i.AssessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE skills
SET name = $3, category = $4, description = $5
WHERE id = $1 AND tenant_id = $2
`

type UpdateSkillParams struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.Exec(ctx, updateSkill,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.Description,
	)
	return err
}

const verifySkillTenant = `-- name: VerifySkillTenant :one
SELECT tenant_id FROM skills WHERE id = $1
`

func (q *Queries) VerifySkillTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifySkillTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
