// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (tenant_id, summary_date, content, submission_rate, blockers_count, key_metrics)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, summary_date, content, submission_rate, blockers_count, key_metrics, created_at
`

type CreateSummaryParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	SummaryDate    pgtype.Date `json:"summary_date"`
	Content        string      `json:"content"`
	SubmissionRate float64     `json:"submission_rate"`
	BlockersCount  int32       `json:"blockers_count"`
	KeyMetrics     []byte      `json:"key_metrics"`
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.TenantID,
		arg.SummaryDate,
		arg.Content,
		arg.SubmissionRate,
		arg.BlockersCount,
		arg.KeyMetrics,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SummaryDate,
		&i.Content,
		&i.SubmissionRate,
		&i.BlockersCount,
		&i.KeyMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSummary = `-- name: GetLatestSummary :one
SELECT id, tenant_id, summary_date, content, submission_rate, blockers_count, key_metrics, created_at FROM summaries WHERE tenant_id = $1 ORDER BY summary_date DESC LIMIT 1
`

func (q *Queries) GetLatestSummary(ctx context.Context, tenantID pgtype.UUID) (Summary, error) {
	row := q.db.QueryRow(ctx, getLatestSummary, tenantID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SummaryDate,
		&i.Content,
		&i.SubmissionRate,
		&i.BlockersCount,
		&i.KeyMetrics,
		&i.CreatedAt,
	)
	return i, err
}

const getSummary = `-- name: GetSummary :one
SELECT id, tenant_id, summary_date, content, submission_rate, blockers_count, key_metrics, created_at FROM summaries WHERE tenant_id = $1 AND summary_date = $2
`

type GetSummaryParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	SummaryDate pgtype.Date `json:"summary_date"`
}

func (q *Queries) GetSummary(ctx context.Context, arg GetSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, getSummary, arg.TenantID, arg.SummaryDate)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SummaryDate,
		&i.Content,
		&i.SubmissionRate,
		&i.BlockersCount,
		&i.KeyMetrics,
		&i.CreatedAt,
	)
	return i, err
}
