// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, COUNT(*)::int AS count
FROM tasks WHERE tenant_id = $1
GROUP BY status
`

type CountTasksByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) CountTasksByStatus(ctx context.Context, tenantID pgtype.UUID) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.Query(ctx, countTasksByStatus, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountTasksByStatusRow{}
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, project_id, goal_id, key_result_id, title,
  description, owner_id, owner_team_id, status, priority, due_at,
  source_system, source_ref, created_by_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, tenant_id, project_id, goal_id, key_result_id, title, description, owner_id, owner_team_id, status, priority, due_at, source_system, source_ref, created_by_agent, created_at, updated_at, external_id, external_source, external_url
`

type CreateTaskParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	GoalID         pgtype.UUID        `json:"goal_id"`
	KeyResultID    pgtype.UUID        `json:"key_result_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	OwnerTeamID    pgtype.UUID        `json:"owner_team_id"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	CreatedByAgent bool               `json:"created_by_agent"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TenantID,
		arg.ProjectID,
		arg.GoalID,
		arg.KeyResultID,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.OwnerTeamID,
		arg.Status,
		arg.Priority,
		arg.DueAt,
		arg.SourceSystem,
		arg.SourceRef,
		arg.CreatedByAgent,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.GoalID,
		&i.KeyResultID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SourceSystem,
		&i.SourceRef,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, project_id, goal_id, key_result_id, title, description, owner_id, owner_team_id, status, priority, due_at, source_system, source_ref, created_by_agent, created_at, updated_at, external_id, external_source, external_url FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.GoalID,
		&i.KeyResultID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SourceSystem,
		&i.SourceRef,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const listOverdueTasks = `-- name: ListOverdueTasks :many
SELECT t.id, t.tenant_id, t.project_id, t.goal_id, t.key_result_id, t.title, t.description, t.owner_id, t.owner_team_id, t.status, t.priority, t.due_at, t.source_system, t.source_ref, t.created_by_agent, t.created_at, t.updated_at, t.external_id, t.external_source, t.external_url, e.name AS owner_name
FROM tasks t
LEFT JOIN employees e ON t.owner_id = e.id
WHERE t.tenant_id = $1
  AND t.status NOT IN ('done', 'cancelled')
  AND t.due_at < now()
ORDER BY t.due_at
`

type ListOverdueTasksRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	GoalID         pgtype.UUID        `json:"goal_id"`
	KeyResultID    pgtype.UUID        `json:"key_result_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	OwnerTeamID    pgtype.UUID        `json:"owner_team_id"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	CreatedByAgent bool               `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ExternalID     pgtype.Text        `json:"external_id"`
	ExternalSource pgtype.Text        `json:"external_source"`
	ExternalUrl    pgtype.Text        `json:"external_url"`
	OwnerName      pgtype.Text        `json:"owner_name"`
}

func (q *Queries) ListOverdueTasks(ctx context.Context, tenantID pgtype.UUID) ([]ListOverdueTasksRow, error) {
	rows, err := q.db.Query(ctx, listOverdueTasks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueTasksRow{}
	for rows.Next() {
		var i ListOverdueTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.GoalID,
			&i.KeyResultID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.SourceSystem,
			&i.SourceRef,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.tenant_id, t.project_id, t.goal_id, t.key_result_id, t.title, t.description, t.owner_id, t.owner_team_id, t.status, t.priority, t.due_at, t.source_system, t.source_ref, t.created_by_agent, t.created_at, t.updated_at, t.external_id, t.external_source, t.external_url,
  e.name AS owner_name,
  p.name AS project_name
FROM tasks t
LEFT JOIN employees e ON t.owner_id = e.id
LEFT JOIN projects p ON t.project_id = p.id
WHERE t.tenant_id = $1
ORDER BY
  CASE t.priority
    WHEN 'critical' THEN 0
    WHEN 'high' THEN 1
    WHEN 'medium' THEN 2
    WHEN 'low' THEN 3
    ELSE 4
  END,
  t.due_at NULLS LAST
`

type ListTasksRow struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	GoalID         pgtype.UUID        `json:"goal_id"`
	KeyResultID    pgtype.UUID        `json:"key_result_id"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	OwnerTeamID    pgtype.UUID        `json:"owner_team_id"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	SourceSystem   pgtype.Text        `json:"source_system"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	CreatedByAgent bool               `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ExternalID     pgtype.Text        `json:"external_id"`
	ExternalSource pgtype.Text        `json:"external_source"`
	ExternalUrl    pgtype.Text        `json:"external_url"`
	OwnerName      pgtype.Text        `json:"owner_name"`
	ProjectName    pgtype.Text        `json:"project_name"`
}

func (q *Queries) ListTasks(ctx context.Context, tenantID pgtype.UUID) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.GoalID,
			&i.KeyResultID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.SourceSystem,
			&i.SourceRef,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
			&i.OwnerName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByOwner = `-- name: ListTasksByOwner :many
SELECT id, tenant_id, project_id, goal_id, key_result_id, title, description, owner_id, owner_team_id, status, priority, due_at, source_system, source_ref, created_by_agent, created_at, updated_at, external_id, external_source, external_url FROM tasks
WHERE owner_id = $1 AND status NOT IN ('done', 'cancelled')
ORDER BY due_at NULLS LAST
`

func (q *Queries) ListTasksByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProjectID,
			&i.GoalID,
			&i.KeyResultID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.OwnerTeamID,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.SourceSystem,
			&i.SourceRef,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalID,
			&i.ExternalSource,
			&i.ExternalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
  title = $2, status = $3, priority = $4, owner_id = $5,
  due_at = $6, description = $7, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, project_id, goal_id, key_result_id, title, description, owner_id, owner_team_id, status, priority, due_at, source_system, source_ref, created_by_agent, created_at, updated_at, external_id, external_source, external_url
`

type UpdateTaskParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.Priority,
		arg.OwnerID,
		arg.DueAt,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProjectID,
		&i.GoalID,
		&i.KeyResultID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.OwnerTeamID,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.SourceSystem,
		&i.SourceRef,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalID,
		&i.ExternalSource,
		&i.ExternalUrl,
	)
	return i, err
}

const verifyTaskTenant = `-- name: VerifyTaskTenant :one
SELECT tenant_id FROM tasks WHERE id = $1
`

func (q *Queries) VerifyTaskTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyTaskTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
