// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, timezone, anthropic_key, mentor_id, bot_token, boss_chat_id, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at, plan, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels
`

type CreateTenantParams struct {
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	AnthropicKey pgtype.Text `json:"anthropic_key"`
	MentorID     string      `json:"mentor_id"`
	BotToken     pgtype.Text `json:"bot_token"`
	BossChatID   int64       `json:"boss_chat_id"`
	Config       []byte      `json:"config"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Timezone,
		arg.AnthropicKey,
		arg.MentorID,
		arg.BotToken,
		arg.BossChatID,
		arg.Config,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
		&i.Plan,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at, plan, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
		&i.Plan,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
	)
	return i, err
}

const getTenantByBossChatID = `-- name: GetTenantByBossChatID :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at, plan, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels FROM tenants WHERE boss_chat_id = $1
`

func (q *Queries) GetTenantByBossChatID(ctx context.Context, bossChatID int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByBossChatID, bossChatID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
		&i.Plan,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
	)
	return i, err
}

const getTenantChannelConfig = `-- name: GetTenantChannelConfig :one
SELECT id, slack_bot_token, slack_signing_secret, lark_app_id, lark_app_secret, signal_phone, enabled_channels
FROM tenants WHERE id = $1
`

type GetTenantChannelConfigRow struct {
	ID                 pgtype.UUID `json:"id"`
	SlackBotToken      pgtype.Text `json:"slack_bot_token"`
	SlackSigningSecret pgtype.Text `json:"slack_signing_secret"`
	LarkAppID          pgtype.Text `json:"lark_app_id"`
	LarkAppSecret      pgtype.Text `json:"lark_app_secret"`
	SignalPhone        pgtype.Text `json:"signal_phone"`
	EnabledChannels    []string    `json:"enabled_channels"`
}

func (q *Queries) GetTenantChannelConfig(ctx context.Context, id pgtype.UUID) (GetTenantChannelConfigRow, error) {
	row := q.db.QueryRow(ctx, getTenantChannelConfig, id)
	var i GetTenantChannelConfigRow
	err := row.Scan(
		&i.ID,
		&i.SlackBotToken,
		&i.SlackSigningSecret,
		&i.LarkAppID,
		&i.LarkAppSecret,
		&i.SignalPhone,
		&i.EnabledChannels,
	)
	return i, err
}

const updateTenantChannels = `-- name: UpdateTenantChannels :exec
UPDATE tenants
SET slack_bot_token = $2, slack_signing_secret = $3,
    lark_app_id = $4, lark_app_secret = $5,
    signal_phone = $6, enabled_channels = $7
WHERE id = $1
`

type UpdateTenantChannelsParams struct {
	ID                 pgtype.UUID `json:"id"`
	SlackBotToken      pgtype.Text `json:"slack_bot_token"`
	SlackSigningSecret pgtype.Text `json:"slack_signing_secret"`
	LarkAppID          pgtype.Text `json:"lark_app_id"`
	LarkAppSecret      pgtype.Text `json:"lark_app_secret"`
	SignalPhone        pgtype.Text `json:"signal_phone"`
	EnabledChannels    []string    `json:"enabled_channels"`
}

func (q *Queries) UpdateTenantChannels(ctx context.Context, arg UpdateTenantChannelsParams) error {
	_, err := q.db.Exec(ctx, updateTenantChannels,
		arg.ID,
		arg.SlackBotToken,
		arg.SlackSigningSecret,
		arg.LarkAppID,
		arg.LarkAppSecret,
		arg.SignalPhone,
		arg.EnabledChannels,
	)
	return err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :exec
UPDATE tenants SET config = $2 WHERE id = $1
`

type UpdateTenantConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	Config []byte      `json:"config"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) error {
	_, err := q.db.Exec(ctx, updateTenantConfig, arg.ID, arg.Config)
	return err
}

const updateTenantMentor = `-- name: UpdateTenantMentor :exec
UPDATE tenants SET mentor_id = $2, mentor_blend = $3 WHERE id = $1
`

type UpdateTenantMentorParams struct {
	ID          pgtype.UUID `json:"id"`
	MentorID    string      `json:"mentor_id"`
	MentorBlend []byte      `json:"mentor_blend"`
}

func (q *Queries) UpdateTenantMentor(ctx context.Context, arg UpdateTenantMentorParams) error {
	_, err := q.db.Exec(ctx, updateTenantMentor, arg.ID, arg.MentorID, arg.MentorBlend)
	return err
}

const updateTenantNameTimezone = `-- name: UpdateTenantNameTimezone :exec
UPDATE tenants SET name = $2, timezone = $3 WHERE id = $1
`

type UpdateTenantNameTimezoneParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Timezone string      `json:"timezone"`
}

func (q *Queries) UpdateTenantNameTimezone(ctx context.Context, arg UpdateTenantNameTimezoneParams) error {
	_, err := q.db.Exec(ctx, updateTenantNameTimezone, arg.ID, arg.Name, arg.Timezone)
	return err
}
