// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, timezone, anthropic_key, mentor_id, bot_token, boss_chat_id, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at
`

type CreateTenantParams struct {
	Name         string      `json:"name"`
	Timezone     string      `json:"timezone"`
	AnthropicKey pgtype.Text `json:"anthropic_key"`
	MentorID     string      `json:"mentor_id"`
	BotToken     pgtype.Text `json:"bot_token"`
	BossChatID   int64       `json:"boss_chat_id"`
	Config       []byte      `json:"config"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Timezone,
		arg.AnthropicKey,
		arg.MentorID,
		arg.BotToken,
		arg.BossChatID,
		arg.Config,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByBossChatID = `-- name: GetTenantByBossChatID :one
SELECT id, name, timezone, anthropic_key, mentor_id, mentor_blend, bot_token, boss_chat_id, config, created_at FROM tenants WHERE boss_chat_id = $1
`

func (q *Queries) GetTenantByBossChatID(ctx context.Context, bossChatID int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByBossChatID, bossChatID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Timezone,
		&i.AnthropicKey,
		&i.MentorID,
		&i.MentorBlend,
		&i.BotToken,
		&i.BossChatID,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :exec
UPDATE tenants SET config = $2 WHERE id = $1
`

type UpdateTenantConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	Config []byte      `json:"config"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) error {
	_, err := q.db.Exec(ctx, updateTenantConfig, arg.ID, arg.Config)
	return err
}

const updateTenantMentor = `-- name: UpdateTenantMentor :exec
UPDATE tenants SET mentor_id = $2, mentor_blend = $3 WHERE id = $1
`

type UpdateTenantMentorParams struct {
	ID          pgtype.UUID `json:"id"`
	MentorID    string      `json:"mentor_id"`
	MentorBlend []byte      `json:"mentor_blend"`
}

func (q *Queries) UpdateTenantMentor(ctx context.Context, arg UpdateTenantMentorParams) error {
	_, err := q.db.Exec(ctx, updateTenantMentor, arg.ID, arg.MentorID, arg.MentorBlend)
	return err
}
