// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO training_enrollments (program_id, employee_id)
VALUES ($1, $2)
RETURNING id, program_id, employee_id, status, enrolled_at, completed_at, score, notes
`

type CreateEnrollmentParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (TrainingEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment, arg.ProgramID, arg.EmployeeID)
	var i TrainingEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.EmployeeID,
		&i.Status,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.Score,
		&i.Notes,
	)
	return i, err
}

const createTrainingProgram = `-- name: CreateTrainingProgram :one
INSERT INTO training_programs (tenant_id, title, description, category, duration_hours, provider, url, is_mandatory)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, title, description, category, duration_hours, provider, url, is_mandatory, status, created_at, updated_at
`

type CreateTrainingProgramParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Category      string      `json:"category"`
	DurationHours int32       `json:"duration_hours"`
	Provider      string      `json:"provider"`
	Url           string      `json:"url"`
	IsMandatory   bool        `json:"is_mandatory"`
}

func (q *Queries) CreateTrainingProgram(ctx context.Context, arg CreateTrainingProgramParams) (TrainingProgram, error) {
	row := q.db.QueryRow(ctx, createTrainingProgram,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.DurationHours,
		arg.Provider,
		arg.Url,
		arg.IsMandatory,
	)
	var i TrainingProgram
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.DurationHours,
		&i.Provider,
		&i.Url,
		&i.IsMandatory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM training_enrollments WHERE id = $1
`

func (q *Queries) DeleteEnrollment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollment, id)
	return err
}

const deleteTrainingProgram = `-- name: DeleteTrainingProgram :exec
DELETE FROM training_programs WHERE id = $1
`

func (q *Queries) DeleteTrainingProgram(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrainingProgram, id)
	return err
}

const getTrainingProgram = `-- name: GetTrainingProgram :one
SELECT id, tenant_id, title, description, category, duration_hours, provider, url, is_mandatory, status, created_at, updated_at FROM training_programs WHERE id = $1
`

func (q *Queries) GetTrainingProgram(ctx context.Context, id pgtype.UUID) (TrainingProgram, error) {
	row := q.db.QueryRow(ctx, getTrainingProgram, id)
	var i TrainingProgram
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.DurationHours,
		&i.Provider,
		&i.Url,
		&i.IsMandatory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeeEnrollments = `-- name: ListEmployeeEnrollments :many
SELECT te.id, te.program_id, te.employee_id, te.status, te.enrolled_at, te.completed_at, te.score, te.notes, tp.title AS program_title, tp.category AS program_category
FROM training_enrollments te
JOIN training_programs tp ON tp.id = te.program_id
WHERE te.employee_id = $1
ORDER BY te.enrolled_at DESC
`

type ListEmployeeEnrollmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProgramID       pgtype.UUID        `json:"program_id"`
	EmployeeID      pgtype.UUID        `json:"employee_id"`
	Status          string             `json:"status"`
	EnrolledAt      pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Score           pgtype.Int4        `json:"score"`
	Notes           string             `json:"notes"`
	ProgramTitle    string             `json:"program_title"`
	ProgramCategory string             `json:"program_category"`
}

func (q *Queries) ListEmployeeEnrollments(ctx context.Context, employeeID pgtype.UUID) ([]ListEmployeeEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeEnrollments, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeEnrollmentsRow{}
	for rows.Next() {
		var i ListEmployeeEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.EmployeeID,
			&i.Status,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.Score,
			&i.Notes,
			&i.ProgramTitle,
			&i.ProgramCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT te.id, te.program_id, te.employee_id, te.status, te.enrolled_at, te.completed_at, te.score, te.notes, e.name AS employee_name
FROM training_enrollments te
JOIN employees e ON e.id = te.employee_id
WHERE te.program_id = $1
ORDER BY te.enrolled_at DESC
`

type ListEnrollmentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	ProgramID    pgtype.UUID        `json:"program_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	Status       string             `json:"status"`
	EnrolledAt   pgtype.Timestamptz `json:"enrolled_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Score        pgtype.Int4        `json:"score"`
	Notes        string             `json:"notes"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListEnrollments(ctx context.Context, programID pgtype.UUID) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrollmentsRow{}
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.EmployeeID,
			&i.Status,
			&i.EnrolledAt,
			&i.CompletedAt,
			&i.Score,
			&i.Notes,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingPrograms = `-- name: ListTrainingPrograms :many
SELECT tp.id, tp.tenant_id, tp.title, tp.description, tp.category, tp.duration_hours, tp.provider, tp.url, tp.is_mandatory, tp.status, tp.created_at, tp.updated_at,
       COUNT(te.id) AS enrollment_count,
       COUNT(te.id) FILTER (WHERE te.status = 'completed') AS completed_count
FROM training_programs tp
LEFT JOIN training_enrollments te ON te.program_id = tp.id
WHERE tp.tenant_id = $1
GROUP BY tp.id
ORDER BY tp.created_at DESC
`

type ListTrainingProgramsRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Category        string             `json:"category"`
	DurationHours   int32              `json:"duration_hours"`
	Provider        string             `json:"provider"`
	Url             string             `json:"url"`
	IsMandatory     bool               `json:"is_mandatory"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EnrollmentCount int64              `json:"enrollment_count"`
	CompletedCount  int64              `json:"completed_count"`
}

func (q *Queries) ListTrainingPrograms(ctx context.Context, tenantID pgtype.UUID) ([]ListTrainingProgramsRow, error) {
	rows, err := q.db.Query(ctx, listTrainingPrograms, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingProgramsRow{}
	for rows.Next() {
		var i ListTrainingProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.DurationHours,
			&i.Provider,
			&i.Url,
			&i.IsMandatory,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollmentCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollment = `-- name: UpdateEnrollment :one
UPDATE training_enrollments SET
    status = $2,
    completed_at = CASE WHEN $2 = 'completed' THEN NOW() ELSE completed_at END,
    score = $3,
    notes = $4
WHERE id = $1
RETURNING id, program_id, employee_id, status, enrolled_at, completed_at, score, notes
`

type UpdateEnrollmentParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Score  pgtype.Int4 `json:"score"`
	Notes  string      `json:"notes"`
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (TrainingEnrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollment,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.Notes,
	)
	var i TrainingEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.EmployeeID,
		&i.Status,
		&i.EnrolledAt,
		&i.CompletedAt,
		&i.Score,
		&i.Notes,
	)
	return i, err
}

const updateTrainingProgram = `-- name: UpdateTrainingProgram :one
UPDATE training_programs SET
    title = $2,
    description = $3,
    category = $4,
    duration_hours = $5,
    provider = $6,
    url = $7,
    is_mandatory = $8,
    status = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, title, description, category, duration_hours, provider, url, is_mandatory, status, created_at, updated_at
`

type UpdateTrainingProgramParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Category      string      `json:"category"`
	DurationHours int32       `json:"duration_hours"`
	Provider      string      `json:"provider"`
	Url           string      `json:"url"`
	IsMandatory   bool        `json:"is_mandatory"`
	Status        string      `json:"status"`
}

func (q *Queries) UpdateTrainingProgram(ctx context.Context, arg UpdateTrainingProgramParams) (TrainingProgram, error) {
	row := q.db.QueryRow(ctx, updateTrainingProgram,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.DurationHours,
		arg.Provider,
		arg.Url,
		arg.IsMandatory,
		arg.Status,
	)
	var i TrainingProgram
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.DurationHours,
		&i.Provider,
		&i.Url,
		&i.IsMandatory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyTrainingProgramTenant = `-- name: VerifyTrainingProgramTenant :one
SELECT tenant_id FROM training_programs WHERE id = $1
`

func (q *Queries) VerifyTrainingProgramTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyTrainingProgramTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
