// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wizard_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWizardSession = `-- name: CreateWizardSession :one
INSERT INTO wizard_sessions (tenant_id, mentor_id, current_step, conversation, company_profile)
VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, mentor_id, current_step, conversation, company_profile, created_at, updated_at
`

type CreateWizardSessionParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	MentorID       string      `json:"mentor_id"`
	CurrentStep    string      `json:"current_step"`
	Conversation   []byte      `json:"conversation"`
	CompanyProfile []byte      `json:"company_profile"`
}

func (q *Queries) CreateWizardSession(ctx context.Context, arg CreateWizardSessionParams) (WizardSession, error) {
	row := q.db.QueryRow(ctx, createWizardSession,
		arg.TenantID,
		arg.MentorID,
		arg.CurrentStep,
		arg.Conversation,
		arg.CompanyProfile,
	)
	var i WizardSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MentorID,
		&i.CurrentStep,
		&i.Conversation,
		&i.CompanyProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWizardSessions = `-- name: DeleteWizardSessions :exec
DELETE FROM wizard_sessions WHERE tenant_id = $1
`

func (q *Queries) DeleteWizardSessions(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWizardSessions, tenantID)
	return err
}

const getLatestWizardSession = `-- name: GetLatestWizardSession :one
SELECT id, tenant_id, mentor_id, current_step, conversation, company_profile, created_at, updated_at FROM wizard_sessions WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestWizardSession(ctx context.Context, tenantID pgtype.UUID) (WizardSession, error) {
	row := q.db.QueryRow(ctx, getLatestWizardSession, tenantID)
	var i WizardSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MentorID,
		&i.CurrentStep,
		&i.Conversation,
		&i.CompanyProfile,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWizardSession = `-- name: UpdateWizardSession :exec
UPDATE wizard_sessions SET current_step = $2, conversation = $3, company_profile = $4, updated_at = now() WHERE id = $1
`

type UpdateWizardSessionParams struct {
	ID             pgtype.UUID `json:"id"`
	CurrentStep    string      `json:"current_step"`
	Conversation   []byte      `json:"conversation"`
	CompanyProfile []byte      `json:"company_profile"`
}

func (q *Queries) UpdateWizardSession(ctx context.Context, arg UpdateWizardSessionParams) error {
	_, err := q.db.Exec(ctx, updateWizardSession,
		arg.ID,
		arg.CurrentStep,
		arg.Conversation,
		arg.CompanyProfile,
	)
	return err
}
