// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (tenant_id, name, category, trigger_conditions, steps,
  approval_rules, escalation_rules)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, category, trigger_conditions, steps, approval_rules, escalation_rules, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	Name              string      `json:"name"`
	Category          pgtype.Text `json:"category"`
	TriggerConditions []byte      `json:"trigger_conditions"`
	Steps             []byte      `json:"steps"`
	ApprovalRules     []byte      `json:"approval_rules"`
	EscalationRules   []byte      `json:"escalation_rules"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.TenantID,
		arg.Name,
		arg.Category,
		arg.TriggerConditions,
		arg.Steps,
		arg.ApprovalRules,
		arg.EscalationRules,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.TriggerConditions,
		&i.Steps,
		&i.ApprovalRules,
		&i.EscalationRules,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
UPDATE workflows SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, tenant_id, name, category, trigger_conditions, steps, approval_rules, escalation_rules, is_active, created_at, updated_at FROM workflows WHERE id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.TriggerConditions,
		&i.Steps,
		&i.ApprovalRules,
		&i.EscalationRules,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, tenant_id, name, category, trigger_conditions, steps, approval_rules, escalation_rules, is_active, created_at, updated_at FROM workflows
WHERE tenant_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListWorkflows(ctx context.Context, tenantID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Category,
			&i.TriggerConditions,
			&i.Steps,
			&i.ApprovalRules,
			&i.EscalationRules,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows SET
  name = $2, category = $3, trigger_conditions = $4, steps = $5,
  approval_rules = $6, escalation_rules = $7, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, name, category, trigger_conditions, steps, approval_rules, escalation_rules, is_active, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	Category          pgtype.Text `json:"category"`
	TriggerConditions []byte      `json:"trigger_conditions"`
	Steps             []byte      `json:"steps"`
	ApprovalRules     []byte      `json:"approval_rules"`
	EscalationRules   []byte      `json:"escalation_rules"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.TriggerConditions,
		arg.Steps,
		arg.ApprovalRules,
		arg.EscalationRules,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Category,
		&i.TriggerConditions,
		&i.Steps,
		&i.ApprovalRules,
		&i.EscalationRules,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyWorkflowTenant = `-- name: VerifyWorkflowTenant :one
SELECT tenant_id FROM workflows WHERE id = $1
`

func (q *Queries) VerifyWorkflowTenant(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyWorkflowTenant, id)
	var tenant_id pgtype.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
