// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: working_memory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkingMemorySnapshot = `-- name: CreateWorkingMemorySnapshot :one
INSERT INTO working_memory_snapshots (tenant_id, snapshot_type, content, generated_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, snapshot_type, content, generated_by, generated_at
`

type CreateWorkingMemorySnapshotParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SnapshotType string      `json:"snapshot_type"`
	Content      []byte      `json:"content"`
	GeneratedBy  pgtype.Text `json:"generated_by"`
}

func (q *Queries) CreateWorkingMemorySnapshot(ctx context.Context, arg CreateWorkingMemorySnapshotParams) (WorkingMemorySnapshot, error) {
	row := q.db.QueryRow(ctx, createWorkingMemorySnapshot,
		arg.TenantID,
		arg.SnapshotType,
		arg.Content,
		arg.GeneratedBy,
	)
	var i WorkingMemorySnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotType,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}

const deleteOldSnapshots = `-- name: DeleteOldSnapshots :exec
DELETE FROM working_memory_snapshots
WHERE tenant_id = $1 AND generated_at < $2
`

type DeleteOldSnapshotsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

func (q *Queries) DeleteOldSnapshots(ctx context.Context, arg DeleteOldSnapshotsParams) error {
	_, err := q.db.Exec(ctx, deleteOldSnapshots, arg.TenantID, arg.GeneratedAt)
	return err
}

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, tenant_id, snapshot_type, content, generated_by, generated_at FROM working_memory_snapshots
WHERE tenant_id = $1 AND snapshot_type = $2
ORDER BY generated_at DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	SnapshotType string      `json:"snapshot_type"`
}

func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (WorkingMemorySnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, arg.TenantID, arg.SnapshotType)
	var i WorkingMemorySnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotType,
		&i.Content,
		&i.GeneratedBy,
		&i.GeneratedAt,
	)
	return i, err
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, tenant_id, snapshot_type, content, generated_by, generated_at FROM working_memory_snapshots
WHERE tenant_id = $1
  AND generated_at >= $2
ORDER BY generated_at DESC
LIMIT $3
`

type ListSnapshotsParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]WorkingMemorySnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots, arg.TenantID, arg.GeneratedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkingMemorySnapshot{}
	for rows.Next() {
		var i WorkingMemorySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SnapshotType,
			&i.Content,
			&i.GeneratedBy,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
