// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: world_model.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveBlockersByTenant = `-- name: CountActiveBlockersByTenant :one
SELECT COUNT(*) FROM world_model_blockers
WHERE tenant_id = $1 AND status IN ('active', 'recurring')
`

func (q *Queries) CountActiveBlockersByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBlockersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGrowthEventsByTenant = `-- name: CountGrowthEventsByTenant :one
SELECT COUNT(*) FROM world_model_growth_events
WHERE tenant_id = $1 AND detected_at > now() - INTERVAL '30 days'
`

func (q *Queries) CountGrowthEventsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGrowthEventsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRelationshipsByTenant = `-- name: CountRelationshipsByTenant :one
SELECT COUNT(*) FROM world_model_relationships
WHERE tenant_id = $1 AND strength >= 0.2
`

func (q *Queries) CountRelationshipsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelationshipsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSkillsByTenant = `-- name: CountSkillsByTenant :one

SELECT COUNT(DISTINCT skill_name) FROM world_model_skills
WHERE tenant_id = $1 AND confidence >= 0.2
`

// ===== Overview Aggregation =====
func (q *Queries) CountSkillsByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSkillsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGrowthEvent = `-- name: CreateGrowthEvent :one

INSERT INTO world_model_growth_events (tenant_id, employee_id, event_type, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, employee_id, event_type, description, detected_at
`

type CreateGrowthEventParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EmployeeID  pgtype.UUID `json:"employee_id"`
	EventType   string      `json:"event_type"`
	Description string      `json:"description"`
}

// ===== Growth Events =====
func (q *Queries) CreateGrowthEvent(ctx context.Context, arg CreateGrowthEventParams) (WorldModelGrowthEvent, error) {
	row := q.db.QueryRow(ctx, createGrowthEvent,
		arg.TenantID,
		arg.EmployeeID,
		arg.EventType,
		arg.Description,
	)
	var i WorldModelGrowthEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.EventType,
		&i.Description,
		&i.DetectedAt,
	)
	return i, err
}

const createWorldModelBlocker = `-- name: CreateWorldModelBlocker :one

INSERT INTO world_model_blockers (tenant_id, employee_id, category, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, employee_id, category, description, status, first_seen_at, resolved_at, recurrence_count
`

type CreateWorldModelBlockerParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EmployeeID  pgtype.UUID `json:"employee_id"`
	Category    string      `json:"category"`
	Description string      `json:"description"`
}

// ===== Blockers =====
func (q *Queries) CreateWorldModelBlocker(ctx context.Context, arg CreateWorldModelBlockerParams) (WorldModelBlocker, error) {
	row := q.db.QueryRow(ctx, createWorldModelBlocker,
		arg.TenantID,
		arg.EmployeeID,
		arg.Category,
		arg.Description,
	)
	var i WorldModelBlocker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.FirstSeenAt,
		&i.ResolvedAt,
		&i.RecurrenceCount,
	)
	return i, err
}

const createWorldModelInsight = `-- name: CreateWorldModelInsight :one

INSERT INTO world_model_insights (tenant_id, dimension, insight_text, evidence, confidence, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, dimension, insight_text, evidence, confidence, generated_at, expires_at
`

type CreateWorldModelInsightParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Dimension   string             `json:"dimension"`
	InsightText string             `json:"insight_text"`
	Evidence    []byte             `json:"evidence"`
	Confidence  pgtype.Numeric     `json:"confidence"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// ===== Insights =====
func (q *Queries) CreateWorldModelInsight(ctx context.Context, arg CreateWorldModelInsightParams) (WorldModelInsight, error) {
	row := q.db.QueryRow(ctx, createWorldModelInsight,
		arg.TenantID,
		arg.Dimension,
		arg.InsightText,
		arg.Evidence,
		arg.Confidence,
		arg.ExpiresAt,
	)
	var i WorldModelInsight
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Dimension,
		&i.InsightText,
		&i.Evidence,
		&i.Confidence,
		&i.GeneratedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const decayRelationshipStrength = `-- name: DecayRelationshipStrength :exec
UPDATE world_model_relationships
SET strength = GREATEST(0.05,
  strength * POWER(0.95, EXTRACT(EPOCH FROM (now() - last_seen_at)) / 604800.0)
)
WHERE tenant_id = $1
`

func (q *Queries) DecayRelationshipStrength(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decayRelationshipStrength, tenantID)
	return err
}

const decaySkillConfidence = `-- name: DecaySkillConfidence :exec
UPDATE world_model_skills
SET confidence = GREATEST(0.05,
  confidence * POWER(0.95, EXTRACT(EPOCH FROM (now() - last_seen_at)) / 604800.0)
  * LEAST(mention_count::numeric / 5.0, 2.0)
)
WHERE tenant_id = $1
`

func (q *Queries) DecaySkillConfidence(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, decaySkillConfidence, tenantID)
	return err
}

const expireOldInsights = `-- name: ExpireOldInsights :exec
DELETE FROM world_model_insights
WHERE expires_at < now()
`

func (q *Queries) ExpireOldInsights(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldInsights)
	return err
}

const findKnowledgeSilos = `-- name: FindKnowledgeSilos :many

SELECT s.skill_name, s.employee_id, e.name as employee_name, s.confidence, s.mention_count
FROM world_model_skills s
JOIN employees e ON s.employee_id = e.id
WHERE s.tenant_id = $1
  AND s.confidence > 0.7
  AND s.skill_name IN (
    SELECT skill_name FROM world_model_skills
    WHERE tenant_id = $1 AND confidence > 0.5
    GROUP BY skill_name HAVING count(*) = 1
  )
ORDER BY s.confidence DESC
`

type FindKnowledgeSilosRow struct {
	SkillName    string         `json:"skill_name"`
	EmployeeID   pgtype.UUID    `json:"employee_id"`
	EmployeeName string         `json:"employee_name"`
	Confidence   pgtype.Numeric `json:"confidence"`
	MentionCount int32          `json:"mention_count"`
}

// ===== Recommender Triggers =====
// Skills where only 1 employee has confidence > 0.5 and that employee has confidence > 0.7
func (q *Queries) FindKnowledgeSilos(ctx context.Context, tenantID pgtype.UUID) ([]FindKnowledgeSilosRow, error) {
	rows, err := q.db.Query(ctx, findKnowledgeSilos, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindKnowledgeSilosRow{}
	for rows.Next() {
		var i FindKnowledgeSilosRow
		if err := rows.Scan(
			&i.SkillName,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Confidence,
			&i.MentionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSimilarBlocker = `-- name: FindSimilarBlocker :one
SELECT id, tenant_id, employee_id, category, description, status, first_seen_at, resolved_at, recurrence_count FROM world_model_blockers
WHERE tenant_id = $1 AND employee_id = $2 AND category = $3 AND status != 'resolved'
ORDER BY first_seen_at DESC
LIMIT 1
`

type FindSimilarBlockerParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
	Category   string      `json:"category"`
}

func (q *Queries) FindSimilarBlocker(ctx context.Context, arg FindSimilarBlockerParams) (WorldModelBlocker, error) {
	row := q.db.QueryRow(ctx, findSimilarBlocker, arg.TenantID, arg.EmployeeID, arg.Category)
	var i WorldModelBlocker
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.FirstSeenAt,
		&i.ResolvedAt,
		&i.RecurrenceCount,
	)
	return i, err
}

const findSkillMatchForBlocker = `-- name: FindSkillMatchForBlocker :many
SELECT s.employee_id, e.name as employee_name, s.skill_name, s.confidence, s.proficiency
FROM world_model_skills s
JOIN employees e ON s.employee_id = e.id
WHERE s.tenant_id = $1
  AND s.skill_name ILIKE '%' || $2 || '%'
  AND s.confidence > 0.6
  AND s.employee_id != $3
ORDER BY s.confidence DESC
LIMIT 3
`

type FindSkillMatchForBlockerParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Column2    pgtype.Text `json:"column_2"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

type FindSkillMatchForBlockerRow struct {
	EmployeeID   pgtype.UUID    `json:"employee_id"`
	EmployeeName string         `json:"employee_name"`
	SkillName    string         `json:"skill_name"`
	Confidence   pgtype.Numeric `json:"confidence"`
	Proficiency  string         `json:"proficiency"`
}

// Find employees who have a skill matching a blocker category (excluding the blocked employee)
func (q *Queries) FindSkillMatchForBlocker(ctx context.Context, arg FindSkillMatchForBlockerParams) ([]FindSkillMatchForBlockerRow, error) {
	rows, err := q.db.Query(ctx, findSkillMatchForBlocker, arg.TenantID, arg.Column2, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSkillMatchForBlockerRow{}
	for rows.Next() {
		var i FindSkillMatchForBlockerRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeName,
			&i.SkillName,
			&i.Confidence,
			&i.Proficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBlockersByEmployee = `-- name: GetActiveBlockersByEmployee :many
SELECT category, description, recurrence_count
FROM world_model_blockers
WHERE tenant_id = $1 AND employee_id = $2 AND status IN ('active', 'recurring')
ORDER BY recurrence_count DESC
`

type GetActiveBlockersByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

type GetActiveBlockersByEmployeeRow struct {
	Category        string `json:"category"`
	Description     string `json:"description"`
	RecurrenceCount int32  `json:"recurrence_count"`
}

// Active blockers for a specific employee (used by compound_risk trigger)
func (q *Queries) GetActiveBlockersByEmployee(ctx context.Context, arg GetActiveBlockersByEmployeeParams) ([]GetActiveBlockersByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, getActiveBlockersByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveBlockersByEmployeeRow{}
	for rows.Next() {
		var i GetActiveBlockersByEmployeeRow
		if err := rows.Scan(&i.Category, &i.Description, &i.RecurrenceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockerCategoryBreakdown = `-- name: GetBlockerCategoryBreakdown :many
SELECT category, COUNT(*) as count
FROM world_model_blockers
WHERE tenant_id = $1 AND status IN ('active', 'recurring')
GROUP BY category
ORDER BY count DESC
`

type GetBlockerCategoryBreakdownRow struct {
	Category string `json:"category"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetBlockerCategoryBreakdown(ctx context.Context, tenantID pgtype.UUID) ([]GetBlockerCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getBlockerCategoryBreakdown, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockerCategoryBreakdownRow{}
	for rows.Next() {
		var i GetBlockerCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEscalatingBlockers = `-- name: GetEscalatingBlockers :many
SELECT b.id, b.employee_id, e.name as employee_name, b.category, b.description,
       b.recurrence_count, b.first_seen_at
FROM world_model_blockers b
JOIN employees e ON b.employee_id = e.id
WHERE b.tenant_id = $1 AND b.status IN ('active', 'recurring') AND b.recurrence_count >= 3
ORDER BY b.recurrence_count DESC
`

type GetEscalatingBlockersRow struct {
	ID              pgtype.UUID        `json:"id"`
	EmployeeID      pgtype.UUID        `json:"employee_id"`
	EmployeeName    string             `json:"employee_name"`
	Category        string             `json:"category"`
	Description     string             `json:"description"`
	RecurrenceCount int32              `json:"recurrence_count"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
}

// Blockers with recurrence >= 3 that are still active
func (q *Queries) GetEscalatingBlockers(ctx context.Context, tenantID pgtype.UUID) ([]GetEscalatingBlockersRow, error) {
	rows, err := q.db.Query(ctx, getEscalatingBlockers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEscalatingBlockersRow{}
	for rows.Next() {
		var i GetEscalatingBlockersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EmployeeName,
			&i.Category,
			&i.Description,
			&i.RecurrenceCount,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentGrowthEventsForTenant = `-- name: GetRecentGrowthEventsForTenant :many
SELECT g.employee_id, e.name as employee_name, g.event_type, g.description, g.detected_at
FROM world_model_growth_events g
JOIN employees e ON g.employee_id = e.id
WHERE g.tenant_id = $1 AND g.detected_at > now() - INTERVAL '7 days'
ORDER BY g.detected_at DESC
LIMIT 20
`

type GetRecentGrowthEventsForTenantRow struct {
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	EmployeeName string             `json:"employee_name"`
	EventType    string             `json:"event_type"`
	Description  string             `json:"description"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
}

// Growth events in the last 7 days for recommendation context
func (q *Queries) GetRecentGrowthEventsForTenant(ctx context.Context, tenantID pgtype.UUID) ([]GetRecentGrowthEventsForTenantRow, error) {
	rows, err := q.db.Query(ctx, getRecentGrowthEventsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentGrowthEventsForTenantRow{}
	for rows.Next() {
		var i GetRecentGrowthEventsForTenantRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeName,
			&i.EventType,
			&i.Description,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementBlockerRecurrence = `-- name: IncrementBlockerRecurrence :exec
UPDATE world_model_blockers
SET recurrence_count = recurrence_count + 1, status = 'recurring', resolved_at = NULL
WHERE id = $1
`

func (q *Queries) IncrementBlockerRecurrence(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementBlockerRecurrence, id)
	return err
}

const listActiveBlockersByTenant = `-- name: ListActiveBlockersByTenant :many
SELECT b.id, b.tenant_id, b.employee_id, b.category, b.description, b.status, b.first_seen_at, b.resolved_at, b.recurrence_count, e.name as employee_name
FROM world_model_blockers b
JOIN employees e ON b.employee_id = e.id
WHERE b.tenant_id = $1 AND b.status IN ('active', 'recurring')
ORDER BY b.recurrence_count DESC, b.first_seen_at DESC
`

type ListActiveBlockersByTenantRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	EmployeeID      pgtype.UUID        `json:"employee_id"`
	Category        string             `json:"category"`
	Description     string             `json:"description"`
	Status          string             `json:"status"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	RecurrenceCount int32              `json:"recurrence_count"`
	EmployeeName    string             `json:"employee_name"`
}

func (q *Queries) ListActiveBlockersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveBlockersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveBlockersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBlockersByTenantRow{}
	for rows.Next() {
		var i ListActiveBlockersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.FirstSeenAt,
			&i.ResolvedAt,
			&i.RecurrenceCount,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveInsightsByTenant = `-- name: ListActiveInsightsByTenant :many
SELECT id, tenant_id, dimension, insight_text, evidence, confidence, generated_at, expires_at FROM world_model_insights
WHERE tenant_id = $1 AND expires_at > now()
ORDER BY confidence DESC, generated_at DESC
`

func (q *Queries) ListActiveInsightsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]WorldModelInsight, error) {
	rows, err := q.db.Query(ctx, listActiveInsightsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorldModelInsight{}
	for rows.Next() {
		var i WorldModelInsight
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Dimension,
			&i.InsightText,
			&i.Evidence,
			&i.Confidence,
			&i.GeneratedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockersByEmployee = `-- name: ListBlockersByEmployee :many
SELECT id, tenant_id, employee_id, category, description, status, first_seen_at, resolved_at, recurrence_count FROM world_model_blockers
WHERE tenant_id = $1 AND employee_id = $2
ORDER BY first_seen_at DESC
LIMIT 20
`

type ListBlockersByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) ListBlockersByEmployee(ctx context.Context, arg ListBlockersByEmployeeParams) ([]WorldModelBlocker, error) {
	rows, err := q.db.Query(ctx, listBlockersByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorldModelBlocker{}
	for rows.Next() {
		var i WorldModelBlocker
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.FirstSeenAt,
			&i.ResolvedAt,
			&i.RecurrenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrowthEventsByEmployee = `-- name: ListGrowthEventsByEmployee :many
SELECT id, tenant_id, employee_id, event_type, description, detected_at FROM world_model_growth_events
WHERE tenant_id = $1 AND employee_id = $2
ORDER BY detected_at DESC
`

type ListGrowthEventsByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) ListGrowthEventsByEmployee(ctx context.Context, arg ListGrowthEventsByEmployeeParams) ([]WorldModelGrowthEvent, error) {
	rows, err := q.db.Query(ctx, listGrowthEventsByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorldModelGrowthEvent{}
	for rows.Next() {
		var i WorldModelGrowthEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.EventType,
			&i.Description,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrowthEventsByTenant = `-- name: ListGrowthEventsByTenant :many
SELECT g.id, g.tenant_id, g.employee_id, g.event_type, g.description, g.detected_at, e.name as employee_name
FROM world_model_growth_events g
JOIN employees e ON g.employee_id = e.id
WHERE g.tenant_id = $1
ORDER BY g.detected_at DESC
LIMIT 50
`

type ListGrowthEventsByTenantRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	EventType    string             `json:"event_type"`
	Description  string             `json:"description"`
	DetectedAt   pgtype.Timestamptz `json:"detected_at"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListGrowthEventsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListGrowthEventsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listGrowthEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrowthEventsByTenantRow{}
	for rows.Next() {
		var i ListGrowthEventsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.EventType,
			&i.Description,
			&i.DetectedAt,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByEmployee = `-- name: ListRelationshipsByEmployee :many
SELECT r.id, r.tenant_id, r.employee_a_id, r.employee_b_id, r.relation_type, r.context, r.strength, r.last_seen_at, r.interaction_count, ea.name as employee_a_name, eb.name as employee_b_name
FROM world_model_relationships r
JOIN employees ea ON r.employee_a_id = ea.id
JOIN employees eb ON r.employee_b_id = eb.id
WHERE r.tenant_id = $1 AND (r.employee_a_id = $2 OR r.employee_b_id = $2) AND r.strength >= 0.2
ORDER BY r.strength DESC
`

type ListRelationshipsByEmployeeParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EmployeeAID pgtype.UUID `json:"employee_a_id"`
}

type ListRelationshipsByEmployeeRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	EmployeeAID      pgtype.UUID        `json:"employee_a_id"`
	EmployeeBID      pgtype.UUID        `json:"employee_b_id"`
	RelationType     string             `json:"relation_type"`
	Context          pgtype.Text        `json:"context"`
	Strength         pgtype.Numeric     `json:"strength"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	InteractionCount int32              `json:"interaction_count"`
	EmployeeAName    string             `json:"employee_a_name"`
	EmployeeBName    string             `json:"employee_b_name"`
}

func (q *Queries) ListRelationshipsByEmployee(ctx context.Context, arg ListRelationshipsByEmployeeParams) ([]ListRelationshipsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByEmployee, arg.TenantID, arg.EmployeeAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationshipsByEmployeeRow{}
	for rows.Next() {
		var i ListRelationshipsByEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeAID,
			&i.EmployeeBID,
			&i.RelationType,
			&i.Context,
			&i.Strength,
			&i.LastSeenAt,
			&i.InteractionCount,
			&i.EmployeeAName,
			&i.EmployeeBName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByTenant = `-- name: ListRelationshipsByTenant :many
SELECT r.id, r.tenant_id, r.employee_a_id, r.employee_b_id, r.relation_type, r.context, r.strength, r.last_seen_at, r.interaction_count, ea.name as employee_a_name, eb.name as employee_b_name
FROM world_model_relationships r
JOIN employees ea ON r.employee_a_id = ea.id
JOIN employees eb ON r.employee_b_id = eb.id
WHERE r.tenant_id = $1 AND r.strength >= 0.2
ORDER BY r.strength DESC
`

type ListRelationshipsByTenantRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	EmployeeAID      pgtype.UUID        `json:"employee_a_id"`
	EmployeeBID      pgtype.UUID        `json:"employee_b_id"`
	RelationType     string             `json:"relation_type"`
	Context          pgtype.Text        `json:"context"`
	Strength         pgtype.Numeric     `json:"strength"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	InteractionCount int32              `json:"interaction_count"`
	EmployeeAName    string             `json:"employee_a_name"`
	EmployeeBName    string             `json:"employee_b_name"`
}

func (q *Queries) ListRelationshipsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListRelationshipsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationshipsByTenantRow{}
	for rows.Next() {
		var i ListRelationshipsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeAID,
			&i.EmployeeBID,
			&i.RelationType,
			&i.Context,
			&i.Strength,
			&i.LastSeenAt,
			&i.InteractionCount,
			&i.EmployeeAName,
			&i.EmployeeBName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByEmployee = `-- name: ListSkillsByEmployee :many
SELECT id, tenant_id, employee_id, skill_name, proficiency, source, confidence, first_seen_at, last_seen_at, mention_count FROM world_model_skills
WHERE tenant_id = $1 AND employee_id = $2 AND confidence >= 0.2
ORDER BY confidence DESC
`

type ListSkillsByEmployeeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EmployeeID pgtype.UUID `json:"employee_id"`
}

func (q *Queries) ListSkillsByEmployee(ctx context.Context, arg ListSkillsByEmployeeParams) ([]WorldModelSkill, error) {
	rows, err := q.db.Query(ctx, listSkillsByEmployee, arg.TenantID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorldModelSkill{}
	for rows.Next() {
		var i WorldModelSkill
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.SkillName,
			&i.Proficiency,
			&i.Source,
			&i.Confidence,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.MentionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByTenant = `-- name: ListSkillsByTenant :many
SELECT s.id, s.tenant_id, s.employee_id, s.skill_name, s.proficiency, s.source, s.confidence, s.first_seen_at, s.last_seen_at, s.mention_count, e.name as employee_name
FROM world_model_skills s
JOIN employees e ON s.employee_id = e.id
WHERE s.tenant_id = $1 AND s.confidence >= 0.2
ORDER BY s.confidence DESC, s.mention_count DESC
`

type ListSkillsByTenantRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	SkillName    string             `json:"skill_name"`
	Proficiency  string             `json:"proficiency"`
	Source       string             `json:"source"`
	Confidence   pgtype.Numeric     `json:"confidence"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	MentionCount int32              `json:"mention_count"`
	EmployeeName string             `json:"employee_name"`
}

func (q *Queries) ListSkillsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListSkillsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listSkillsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsByTenantRow{}
	for rows.Next() {
		var i ListSkillsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmployeeID,
			&i.SkillName,
			&i.Proficiency,
			&i.Source,
			&i.Confidence,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.MentionCount,
			&i.EmployeeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveBlocker = `-- name: ResolveBlocker :exec
UPDATE world_model_blockers
SET status = 'resolved', resolved_at = now()
WHERE id = $1
`

func (q *Queries) ResolveBlocker(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resolveBlocker, id)
	return err
}

const upsertWorldModelRelationship = `-- name: UpsertWorldModelRelationship :one

INSERT INTO world_model_relationships (tenant_id, employee_a_id, employee_b_id, relation_type, context, strength)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, employee_a_id, employee_b_id, relation_type)
DO UPDATE SET
  context = EXCLUDED.context,
  strength = LEAST(1.0, world_model_relationships.strength + 0.1),
  last_seen_at = now(),
  interaction_count = world_model_relationships.interaction_count + 1
RETURNING id, tenant_id, employee_a_id, employee_b_id, relation_type, context, strength, last_seen_at, interaction_count
`

type UpsertWorldModelRelationshipParams struct {
	TenantID     pgtype.UUID    `json:"tenant_id"`
	EmployeeAID  pgtype.UUID    `json:"employee_a_id"`
	EmployeeBID  pgtype.UUID    `json:"employee_b_id"`
	RelationType string         `json:"relation_type"`
	Context      pgtype.Text    `json:"context"`
	Strength     pgtype.Numeric `json:"strength"`
}

// ===== Relationships =====
func (q *Queries) UpsertWorldModelRelationship(ctx context.Context, arg UpsertWorldModelRelationshipParams) (WorldModelRelationship, error) {
	row := q.db.QueryRow(ctx, upsertWorldModelRelationship,
		arg.TenantID,
		arg.EmployeeAID,
		arg.EmployeeBID,
		arg.RelationType,
		arg.Context,
		arg.Strength,
	)
	var i WorldModelRelationship
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeAID,
		&i.EmployeeBID,
		&i.RelationType,
		&i.Context,
		&i.Strength,
		&i.LastSeenAt,
		&i.InteractionCount,
	)
	return i, err
}

const upsertWorldModelSkill = `-- name: UpsertWorldModelSkill :one


INSERT INTO world_model_skills (tenant_id, employee_id, skill_name, proficiency, source, confidence, mention_count)
VALUES ($1, $2, $3, $4, $5, $6, 1)
ON CONFLICT (tenant_id, employee_id, skill_name)
DO UPDATE SET
  proficiency = EXCLUDED.proficiency,
  confidence = GREATEST(world_model_skills.confidence, EXCLUDED.confidence),
  last_seen_at = now(),
  mention_count = world_model_skills.mention_count + 1
RETURNING id, tenant_id, employee_id, skill_name, proficiency, source, confidence, first_seen_at, last_seen_at, mention_count
`

type UpsertWorldModelSkillParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	EmployeeID  pgtype.UUID    `json:"employee_id"`
	SkillName   string         `json:"skill_name"`
	Proficiency string         `json:"proficiency"`
	Source      string         `json:"source"`
	Confidence  pgtype.Numeric `json:"confidence"`
}

// sql/queries/world_model.sql
// ===== Skills =====
func (q *Queries) UpsertWorldModelSkill(ctx context.Context, arg UpsertWorldModelSkillParams) (WorldModelSkill, error) {
	row := q.db.QueryRow(ctx, upsertWorldModelSkill,
		arg.TenantID,
		arg.EmployeeID,
		arg.SkillName,
		arg.Proficiency,
		arg.Source,
		arg.Confidence,
	)
	var i WorldModelSkill
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmployeeID,
		&i.SkillName,
		&i.Proficiency,
		&i.Source,
		&i.Confidence,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.MentionCount,
	)
	return i, err
}
