package brain

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// CompanyProfile holds the collected information about a company.
type CompanyProfile struct {
	Industry      string   `json:"industry"`
	Size          int      `json:"size"`
	Stage         string   `json:"stage"`
	BusinessModel string   `json:"business_model,omitempty"`
	Region        string   `json:"region,omitempty"`
	PainPoints    []string `json:"pain_points,omitempty"`
}

// ManagementPlan is the complete management plan generated by a mentor.
type ManagementPlan struct {
	Framework         string                 `json:"management_framework"`
	OrgDesign         OrgDesign              `json:"org_design"`
	CulturePrinciples []string               `json:"culture_principles"`
	Policies          map[string]interface{} `json:"policies"`
	KPISystem         []KPIDefinition        `json:"kpi_system"`
	DailyQuestions    map[string][]string    `json:"daily_questions"`
	MeetingCadence    []MeetingRule          `json:"meeting_cadence"`
	AlertRules        []AlertRule            `json:"alert_rules"`
	Reasoning         string                 `json:"reasoning"`
}

// OrgDesign describes the organizational structure.
type OrgDesign struct {
	Philosophy    string        `json:"philosophy"`
	StructureType string        `json:"structure_type"`
	Units         []OrgUnit     `json:"units"`
	SupportRoles  []SupportRole `json:"support_roles,omitempty"`
}

// OrgUnit is a single organizational unit (team, department, amoeba, etc.).
type OrgUnit struct {
	Name       string   `json:"name"`
	LeaderType string   `json:"leader_type"`
	LeaderRole string   `json:"leader_role"`
	Size       int      `json:"size,omitempty"`
	KPIs       []string `json:"kpis,omitempty"`
}

// SupportRole is a cross-cutting support role (C-level, advisor, etc.).
type SupportRole struct {
	Title string `json:"title"`
	Type  string `json:"type"`
	Scope string `json:"scope"`
}

// KPIDefinition defines a single KPI metric.
type KPIDefinition struct {
	Name      string `json:"name"`
	Target    string `json:"target"`
	Frequency string `json:"frequency"`
	Owner     string `json:"owner"`
}

// MeetingRule defines a recurring meeting.
type MeetingRule struct {
	Name      string `json:"name"`
	Frequency string `json:"frequency"`
	Duration  string `json:"duration"`
	Attendees string `json:"attendees"`
	Purpose   string `json:"purpose"`
}

// AlertRule defines an automated alert condition.
type AlertRule struct {
	Condition string `json:"condition"`
	Action    string `json:"action"`
	Message   string `json:"message"`
}

// OrgEngine generates management plans using a mentor's philosophy.
type OrgEngine struct {
	llm *AnthropicClient
}

// NewOrgEngine creates a new organization engine.
func NewOrgEngine(llm *AnthropicClient) *OrgEngine {
	return &OrgEngine{llm: llm}
}

// GeneratePlan creates a complete management plan based on mentor philosophy and company profile.
func (e *OrgEngine) GeneratePlan(ctx context.Context, mentor *MentorConfig, profile CompanyProfile) (*ManagementPlan, error) {
	if mentor == nil {
		return nil, fmt.Errorf("mentor config is required")
	}

	systemPrompt := buildOrgSystemPrompt(mentor)
	userPrompt := buildOrgUserPrompt(profile)

	resp, err := e.llm.ChatLong(ctx, systemPrompt, userPrompt)
	if err != nil {
		return nil, fmt.Errorf("LLM generate plan: %w", err)
	}

	plan, err := parseManagementPlan(resp)
	if err != nil {
		return nil, fmt.Errorf("parse plan: %w", err)
	}

	return plan, nil
}

// AdjustPlan modifies an existing plan based on user feedback.
func (e *OrgEngine) AdjustPlan(ctx context.Context, mentor *MentorConfig, currentPlan *ManagementPlan, feedback string) (*ManagementPlan, error) {
	if mentor == nil {
		return nil, fmt.Errorf("mentor config is required")
	}
	if currentPlan == nil {
		return nil, fmt.Errorf("current plan is required")
	}

	planJSON, err := json.Marshal(currentPlan)
	if err != nil {
		return nil, fmt.Errorf("marshal current plan: %w", err)
	}

	systemPrompt := buildOrgSystemPrompt(mentor) + "\n\n当前管理方案 (请在此基础上修改):\n" + string(planJSON)

	resp, err := e.llm.ChatLong(ctx, systemPrompt, "用户反馈："+feedback+"\n\n请根据反馈修改方案，返回完整的修改后方案 JSON。")
	if err != nil {
		return nil, fmt.Errorf("LLM adjust plan: %w", err)
	}

	plan, err := parseManagementPlan(resp)
	if err != nil {
		return nil, fmt.Errorf("parse adjusted plan: %w", err)
	}

	return plan, nil
}

// buildOrgSystemPrompt creates the system prompt for management plan generation.
func buildOrgSystemPrompt(mentor *MentorConfig) string {
	return fmt.Sprintf(`你是 %s（%s），管理哲学：%s

%s

你正在为一家公司设计完整的管理体系。你有 **完全的自由** 决定：
- 管理框架（OKR / KPI / 阿米巴 / Scrum / 混合 / 你认为合适的任何方式）
- 组织结构（扁平 / 层级 / 矩阵 / 阿米巴 / 轮值 / 自定义）
- 是否需要 C-level（小团队可能不需要，你来决定）
- 哪些角色用 AI 代理、哪些必须真人
- 企业文化、会议节奏、KPI 体系、预警规则
- 每个角色的 daily check-in 问题（不是一刀切）

重要：根据这家公司的实际情况设计，不要默认套用传统企业结构。

用以下 JSON 格式回复（不要包含其他文本）:
{
  "management_framework": "你选择的管理框架",
  "org_design": {
    "philosophy": "组织设计哲学",
    "structure_type": "结构类型",
    "units": [
      {"name": "单元名", "leader_type": "leader类型", "leader_role": "角色", "size": 5, "kpis": ["kpi1"]}
    ],
    "support_roles": [
      {"title": "角色名", "type": "human/ai", "scope": "职责范围"}
    ]
  },
  "culture_principles": ["原则1", "原则2"],
  "policies": {"key": "value"},
  "kpi_system": [
    {"name": "KPI名", "target": "目标", "frequency": "频率", "owner": "负责人"}
  ],
  "daily_questions": {
    "role_name": ["问题1", "问题2", "问题3"]
  },
  "meeting_cadence": [
    {"name": "会议名", "frequency": "频率", "duration": "时长", "attendees": "参与者", "purpose": "目的"}
  ],
  "alert_rules": [
    {"condition": "条件", "action": "动作", "message": "消息"}
  ],
  "reasoning": "你的设计理由"
}`, mentor.NameEn, mentor.Company, mentor.Philosophy, mentor.Strategy.SystemPrompt)
}

// buildOrgUserPrompt creates the user prompt from a company profile.
func buildOrgUserPrompt(profile CompanyProfile) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("请为以下公司设计管理体系：\n\n"))
	sb.WriteString(fmt.Sprintf("行业：%s\n", profile.Industry))
	sb.WriteString(fmt.Sprintf("团队规模：%d 人\n", profile.Size))
	sb.WriteString(fmt.Sprintf("公司阶段：%s\n", profile.Stage))

	if profile.BusinessModel != "" {
		sb.WriteString(fmt.Sprintf("商业模式：%s\n", profile.BusinessModel))
	}
	if profile.Region != "" {
		sb.WriteString(fmt.Sprintf("地区：%s\n", profile.Region))
	}
	if len(profile.PainPoints) > 0 {
		sb.WriteString(fmt.Sprintf("痛点/挑战：%s\n", strings.Join(profile.PainPoints, "、")))
	}

	return sb.String()
}

// parseManagementPlan extracts a ManagementPlan from an LLM response string.
func parseManagementPlan(resp string) (*ManagementPlan, error) {
	resp = strings.TrimSpace(resp)

	// Strip markdown code fences
	if strings.HasPrefix(resp, "```") {
		lines := strings.Split(resp, "\n")
		if len(lines) > 2 {
			resp = strings.Join(lines[1:len(lines)-1], "\n")
		}
	}

	// Find JSON boundaries
	start := strings.Index(resp, "{")
	end := strings.LastIndex(resp, "}")
	if start < 0 || end <= start {
		return nil, fmt.Errorf("no JSON object found in response")
	}
	resp = resp[start : end+1]

	var plan ManagementPlan
	if err := json.Unmarshal([]byte(resp), &plan); err != nil {
		return nil, fmt.Errorf("unmarshal plan: %w (response: %.300s)", err, resp)
	}

	return &plan, nil
}
